### ISSUE TITLE
Property editor not being used for frm:select [SPR-5818]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#10488]
**[john@johnandkerri.com](https://jira.spring.io/secure/ViewProfile.jspa?name=johndstein)** opened **[SPR-5818](https://jira.spring.io/browse/SPR-5818?redirect=false)** and commented

As of spring v 2.5.6, for frm:select tags toString is still being called by org.springframework.web.servlet.tags.form.SelectedValueComparator.isSelected method instead of my custom property editor. the editor is called on save, but not on display of jsp page.

this is similar to http://jira.springframework.org/browse/SPR-4164 which reported as fixed by 2.5.2.

    <frm:select path="food.type" items="${foodTypes}" itemLabel="name"
    	itemValue="id"></frm:select>

06/10 12:15:01 [http-8080-Processor24] DEBUG net.aileron.data.entity.rez.FoodType.toString(FoodType.java:100)
java.lang.RuntimeException
at net.aileron.data.entity.rez.FoodType.toString(FoodType.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.hibernate.proxy.pojo.cglib.CGLIBLazyInitializer.invoke(CGLIBLazyInitializer.java:157)
at net.aileron.data.entity.rez.FoodType$$EnhancerByCGLIB$$74e31005.toString(\<generated>)
at org.springframework.util.ObjectUtils.nullSafeToString(ObjectUtils.java:547)
at org.springframework.util.ObjectUtils.getDisplayString(ObjectUtils.java:493)
at org.springframework.web.servlet.tags.form.SelectedValueComparator.exhaustiveCompare(SelectedValueComparator.java:181)
at org.springframework.web.servlet.tags.form.SelectedValueComparator.isSelected(SelectedValueComparator.java:105)
at org.springframework.web.servlet.tags.form.OptionWriter.isOptionSelected(OptionWriter.java:233)
at org.springframework.web.servlet.tags.form.OptionWriter.renderOption(OptionWriter.java:210)
at org.springframework.web.servlet.tags.form.OptionWriter.doRenderFromCollection(OptionWriter.java:192)
at org.springframework.web.servlet.tags.form.OptionWriter.renderFromCollection(OptionWriter.java:177)
at org.springframework.web.servlet.tags.form.OptionWriter.writeOptions(OptionWriter.java:132)
at org.springframework.web.servlet.tags.form.SelectTag.writeTagContent(SelectTag.java:216)

---
No further details from [SPR-5818](https://jira.spring.io/browse/SPR-5818?redirect=false)

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
