### ISSUE TITLE
ProxyFactoryBean getObject called before setInterceptorNames, silently creating an invalid proxy [SPR-7582]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#12238]
**[nigel magnay](https://jira.spring.io/secure/ViewProfile.jspa?name=magnayn)** opened **[SPR-7582](https://jira.spring.io/browse/SPR-7582?redirect=false)** and commented

We have an application that uses a fairly standard pattern to declare a proxy for a bean:

```xml
    <bean id="AService" name="aService" class="org.springframework.aop.framework.ProxyFactoryBean">
    	<property name="target"><ref bean="AServiceTXN"/></property>
    	<property name="interceptorNames">
    		<list>
    		   <value>Interceptor1</value>
                           <value>Interceptor2</value>  
                            ...
                           <value>InterceptorN</value>
    		</list>
    	</property>
    </bean>
```

The instantiation order causes this bean to be being created in response to an unrelated autowiring request, e.g:

```java
@Autowired(required=false)
List<SomeOther> someOthers;
```

Which is internally executing `getBeanNamesForType()`.

This causes a chain of objects to be created, and the `ProxyFactoryBean` for `AService` to be called with `getObject()`.

However, this `getObject()` call is in advance of Spring having set the `interceptorNames`. Thus the proxy is created, and the `advisorChainInitialized` variable set to `true` with no interceptor names.

There's several things here

1. I don't see why spring is calling `getObject` on an uninitialized factory; it ought to have set the properties first. I don't believe there are circular dependencies here (since it is initiated by a request to find all instances of an unrelated class). I can remove the problem (for one bean, but this applies to many) by creating a derived type of `ProxyFactoryBean` that sets the target and `interceptorNames` on construction... but this seems to be a nasty workaround as I'd have to set it for many, many beans. If it believes there to be a circular dependency I'd expect an exception.
2. If `setInterceptorNames` finds that `advisorChainInitialized == true`, it ought to throw an exception, since it is clearly too late to influence the interception chain (so for example security interceptors mysteriously fail to work).

---

**Affects:** 2.5.6

**Attachments:**
- [spring-SPR-7582-workaround.patch](https://jira.spring.io/secure/attachment/17467/spring-SPR-7582-workaround.patch) (_1.71 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1477

2 votes, 3 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by marijnm** [comment]
This is still an issue

**Comment by sbrannen** [comment]
@marijnm, would you be willing to provide a simple example project that demonstrates the issue -- for example, if the form of a GitHub repository or ZIP file that we can download and use to reproduce the issue?

**Comment by mp5er** [comment]
I'm facing the same problem. Detailed description: https://stackoverflow.com/questions/66133760/spring-proxyfactorybean-interceptor-advice-sometimes-not-called-missing

Spring version: 5.1.15.RELEASE

**Comment by mp5er** [comment]
I'm facing the same problem. Detailed description: https://stackoverflow.com/questions/66133760/spring-proxyfactorybean-interceptor-advice-sometimes-not-called-missing

The ProxyFactoryBean also tries multiple times to create the Proxy while it's not initialized: 

```
org.springframework.beans.factory.FactoryBeanNotInitializedException: Cannot determine target class for proxy
	at org.springframework.aop.framework.ProxyFactoryBean.getSingletonInstance(ProxyFactoryBean.java:322)
	at org.springframework.aop.framework.ProxyFactoryBean.getObject(ProxyFactoryBean.java:252)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:135)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1674)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1248)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:303)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:676)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1340)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1186)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:303)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1674)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1426)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
.....
```

After the first call of `getObject` the `advisorChainInitialized` is set to true and the adivces are not added.

Spring version: 5.1.15.RELEASE
OS: Linux
JDK: OpenJDK 11.0.9
