### ISSUE TITLE
JavaMailSenderImpl misses a synchronized block for sending mails [SPR-7914]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#12569]
**[Michael Wyraz](https://jira.spring.io/secure/ViewProfile.jspa?name=micw)** opened **[SPR-7914](https://jira.spring.io/browse/SPR-7914?redirect=false)** and commented

In JavaMailSenderImpl.doSend everything after
Transport transport = getTransport(getSession());
until
finally {
transport.close();
}
has to be in a synchronized(transport) block.

The reason is that JavaMail (at least the sun implementation) requires this. Otherwise connecting fails if assertions are enabled:
java.lang.AssertionError
at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:1578)
at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1369)
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:412)
at javax.mail.Service.connect(Service.java:248)
[...]

The failing code in the implementation is:
protected int readServerResponse() throws MessagingException {
assert Thread.holdsLock(this);

Probably ignoring this will result in strange race conditions. At least it avoids sending of mail with assertions enabled.

---

**Affects:** 2.5.6

1 votes, 4 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
