### ISSUE TITLE
PropertyBatchUpdateException hide undescriptive errors [SPR-7968]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#12623]
**[Jerome Lacoste](https://jira.spring.io/secure/ViewProfile.jspa?name=lacostej)** opened **[SPR-7968](https://jira.spring.io/browse/SPR-7968?redirect=false)** and commented

We're using 3.0.5 but I don't think the code has been updated

One of our BeanFactory isn't behaving properly and throwing a NullPointerException when lazy instantiating an object.
That object is used as a property into another object.

This cause the following stacktrace:

```
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1361)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:900)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:455)

Caused byProperyBatchUpdateException [...] nested PropertyAccessExceptions are:

...
Error creating bean with name '...': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
```

As the stack trace is 'eaten' by the PropertyBatchUpdateException, this forced us to add some logging to the factory after the fact.

Might be interesting to do something there. Implementing getCause() in PropertyBatchUpdateException maybe ?

---

**Affects:** 3.1 M1

1 votes, 2 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
