### ISSUE TITLE
Can't create JaxWsPortProxyFactoryBean caused by an unknown WebServiceFeature specification type [SPR-8739]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#13381]
**[Sven W](https://jira.spring.io/secure/ViewProfile.jspa?name=svenw)** opened **[SPR-8739](https://jira.spring.io/browse/SPR-8739?redirect=false)** and commented

With an update to Spring 3.0.6.RELEASE we are facing with a strange problem by using the class JaxWsPortProxyFactoryBean to consume a web service as part of a web application(based on Wicket). When we start to deploy the the application to our application server (Glassfish v2) we are getting the following exception:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.remoting.jaxws.JaxWsPortProxyFactoryBean#b01950' defined in ServletContext resource [/WEB-INF/resultsAggregationContext.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Unknown WebServiceFeature specification type: class $Proxy119
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:270)
        ... 122 more
Caused by: java.lang.IllegalArgumentException: Unknown WebServiceFeature specification type: class $Proxy119
        at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor$FeaturePortProvider.convertWebServiceFeature(JaxWsPortClientInterceptor.java:563)
        at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor$FeaturePortProvider.getPortStub(JaxWsPortClientInterceptor.java:539)
        at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.getPortStub(JaxWsPortClientInterceptor.java:410)
        at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.prepare(JaxWsPortClientInterceptor.java:337)
        at org.springframework.remoting.jaxws.JaxWsPortClientInterceptor.afterPropertiesSet(JaxWsPortClientInterceptor.java:316)
        at org.springframework.remoting.jaxws.JaxWsPortProxyFactoryBean.afterPropertiesSet(JaxWsPortProxyFactoryBean.java:42)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
        ... 125 more
```

A short research reveals that all defined spring beans of the applicationContext.xml are handled as features at least the beans will be set with "setWebServiceFeatures".
As a workaround we extended the bean configurations and setting an empty list/array:

```
<bean id="service" class="org.springframework.remoting.jaxws.JaxWsPortProxyFactoryBean">
   ...
   <property name="webServiceFeatures">
      <list></list>
    </property>
</bean>
```

I'm not sure if it is really a bug or we are doing something wrong in our environment? The change
came in with the version 3.0.3(https://jira.springsource.org/browse/SPR-5712). The service classes
are automatically generated with JAW-WS and doesn't contain any specific annotation to define a feature
and the beans are not defined as inline beans.

Many thanks in advance for your support!

Best regards
Sven Walter

---

**Affects:** 3.0.6

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
