### ISSUE TITLE
DataSourceTransactionManager assumes that connection is not in transaction but nothing ensures it [SPR-8870]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#13511]
**[Leonid](https://jira.spring.io/secure/ViewProfile.jspa?name=leonidos@gmail.com)** opened **[SPR-8870](https://jira.spring.io/browse/SPR-8870?redirect=false)** and commented

DataSourceTransactionManager.doBegin() assumes that connection it passes to DataSourceUtils.prepareConnectionForTransaction() is not in transaction but really nothing does guaranntee it. In case of PostgreSQL this causes an exception:

org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
at org.postgresql.jdbc2.AbstractJdbc2Connection.setTransactionIsolation(AbstractJdbc2Connection.java:783)
at org.apache.commons.dbcp.DelegatingConnection.setTransactionIsolation(DelegatingConnection.java:380)
at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.setTransactionIsolation(PoolingDataSource.java:343)
at org.apache.commons.dbcp.DelegatingConnection.setTransactionIsolation(DelegatingConnection.java:380)
at org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction(DataSourceUtils.java:174)
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:210)
... 38 more

---

1 votes, 2 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
