### ISSUE TITLE
@Autowired with required=false on List<T> hides that fact that autowiring is not possible [SPR-10081]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#14714]
**[Piotr Findeisen](https://jira.spring.io/secure/ViewProfile.jspa?name=pofin)** opened **[SPR-10081](https://jira.spring.io/browse/SPR-10081?redirect=false)** and commented

Until #14713 is done, it is not possible to `@Autowire` a field declared as `List<T>` where `T` is a generic type parameter specified by subclass.

If you have such a field, you will get an exception like this:

```
Caused by: org.springframework.beans.FatalBeanException: No element type declared for collection [java.util.List]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:772)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:735)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:478)
```

However, if the field is marked as `@Atuwored(required=false)`, then Spring hides the information that it did not try to autowire the field at all.

```java
Class<?> elementType = descriptor.getCollectionType();
if (elementType == null) { // <- we failed to resolve collection type
	if (descriptor.isRequired()) { // <!- ... hide the problem if not required
		throw new FatalBeanException("No element type declared for collection [" + type.getName() + "]");
	}
	return null;
}

```

---

**Affects:** 3.1.2

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
