### ISSUE TITLE
Exclude bean-invocations from the Spring-internal synchronization [SPR-10123]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#14756]
**[Barnabas Bodnar](https://jira.spring.io/secure/ViewProfile.jspa?name=bbodnar)** opened **[SPR-10123](https://jira.spring.io/browse/SPR-10123?redirect=false)** and commented

During the instantiation/initialization of beans in Spring is even bean-code (eg. implementations of org.springframework.beans.factory.InitializingBean.afterPropertiesSet()) invoked within synchronized code-blocks. As the bean-code may invoke further application-related synchronized code, nesting of synchronization and consequently deadlocks can arise, even at a correct concurrency-related design on the application-level (however, not considering the Spring-internal synchronization).

Currently, such deadlocks can only be avoided, if the application-developer takes account also for the Spring-internal synchronization, which should - in my opinion - not be a requirement (not to mention the complexity of such solutions). Therefore, the Spring-internal synchronization should preferably **not** include invocations of bean-code.

The attached project demonstrates a deadlock of the mentioned sort (works with all the released Spring-versions from 3.0 to 3.2).

```
Found one Java-level deadlock:
=============================
"pool-1-thread-2":
  waiting to lock monitor 0x00007f1980004968 (object 0x00000007d7161470, a demo.spring.Singleton1),
  which is held by "pool-1-thread-1"
"pool-1-thread-1":
  waiting to lock monitor 0x00007f1980005f10 (object 0x00000007d6caa148, a java.util.concurrent.ConcurrentHashMap),
  which is held by "pool-1-thread-2"

Java stack information for the threads listed above:
===================================================
"pool-1-thread-2":
	at demo.spring.Singleton1.getLazily(Singleton1.java:19)
	- waiting to lock <0x00000007d7161470> (a demo.spring.Singleton1)
	at demo.spring.Singleton2.afterPropertiesSet(Singleton2.java:18)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	- locked <0x00000007d6caa148> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:270)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at demo.spring.Main$2.call(Main.java:31)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
"pool-1-thread-1":
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:182)
	- waiting to lock <0x00000007d6caa148> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:468)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:338)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:316)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:257)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at demo.spring.Singleton1.getLazily(Singleton1.java:20)
	- locked <0x00000007d7161470> (a demo.spring.Singleton1)
	at demo.spring.Main$1.call(Main.java:24)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)

Found 1 deadlock.
```

---

**Affects:** 3.2 GA

**Attachments:**
- [deadlock-at-singleton-instantiation.zip](https://jira.spring.io/secure/attachment/20829/deadlock-at-singleton-instantiation.zip) (_5.71 kB_)

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
