### ISSUE TITLE
spring-aop introduction into Groovy class don't work [SPR-10287]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#14921]
**[Wujek](https://jira.spring.io/secure/ViewProfile.jspa?name=wujek.srujek@gmail.com)** opened **[SPR-10287](https://jira.spring.io/browse/SPR-10287?redirect=false)** and commented

Attached a simple Groovy 2.1.0 and Gradle 1.4 project. Introducing types into Java classes works fine, but into Groovy classes does not, although the bean can be cast to the introduced interface type (Runnable in this case). The exception is:

> Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: test.service.PersonServiceGroovy.run() is applicable for argument types: () values: []
> Possible solutions: grep(), dump(), find(), any(), print(java.io.PrintWriter), grep(java.lang.Object)
> at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
> at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:51)
> at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
> at Main.run(Main.groovy:8)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:601)
> at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
> at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
> at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
> at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
> at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
> at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
> at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
> at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
> at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
> at Main.main(Main.groovy)

---

**Affects:** 3.2.1

**Attachments:**
- [aop_introduction_groovy.tgz](https://jira.spring.io/secure/attachment/20942/aop_introduction_groovy.tgz) (_46.12 kB_)

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
