### ISSUE TITLE
Allow for @DeclareParents.defaultImpl to be optional, as suggested in AspectJ's javadoc [SPR-10286]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#14920]
**[Wujek](https://jira.spring.io/secure/ViewProfile.jspa?name=wujek.srujek@gmail.com)** opened **[SPR-10286](https://jira.spring.io/browse/SPR-10286?redirect=false)** and commented

If one doesn't specify the defaultImpl value, the application explodes at runtime with the following:

> Caught: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'personService' defined in class path resource [beans.xml]: BeanPostProcessor before instantiation of bean failed; nested exception is java.lang.IllegalStateException: defaultImpl must be set on DeclareParents
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'personService' defined in class path resource [beans.xml]: BeanPostProcessor before instantiation of bean failed; nested exception is java.lang.IllegalStateException: defaultImpl must be set on DeclareParents
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:457)
> at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
> at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
> at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
> at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
> at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:626)
> at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
> at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
> at org.springframework.context.support.ClassPathXmlApplicationContext.\<init>(ClassPathXmlApplicationContext.java:139)
> at org.springframework.context.support.ClassPathXmlApplicationContext.\<init>(ClassPathXmlApplicationContext.java:83)
> at Main.run(Main.groovy:4)
> at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
> Caused by: java.lang.IllegalStateException: defaultImpl must be set on DeclareParents
> at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getDeclareParentsAdvisor(ReflectiveAspectJAdvisorFactory.java:159)
> at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:119)
> at org.springframework.aop.aspectj.annotation.BeanFactoryAspectJAdvisorsBuilder.buildAspectJAdvisors(BeanFactoryAspectJAdvisorsBuilder.java:109)
> at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:87)
> at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:108)
> at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:276)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:894)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:866)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:451)
> ... 11 more

whereas the code for `@DefaultParents` (at least in version 3.2.1.RELEASE) says it is optional:

```
/**
 * Optional class defining default implementation
 * of interface members (equivalent to defining
 * a set of interface member ITDs for the
 * public methods of the interface).
 */
Class defaultImpl() default DeclareParents.class;
```

The code at the place that throws the exception has a comment:

```
if (DeclareParents.class.equals(declareParents.defaultImpl())) {
    // This is what comes back if it wasn't set. This seems bizarre...
    // TODO this restriction possibly should be relaxed
    throw new IllegalStateException("defaultImpl must be set on DeclareParents");
}
```

This should be made consistent across the documentation and code.

---

**Affects:** 3.2.1

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
