### ISSUE TITLE
Spring remote over JMS not work in Rest service [SPR-10535]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#15165]
**[tu nguyen khac](https://jira.spring.io/secure/ViewProfile.jspa?name=tuyuri)** opened **[SPR-10535](https://jira.spring.io/browse/SPR-10535?redirect=false)** and commented

when i run REST (Spring web app) and try make a remoting over JMS
i get exception : ( if i run in java base application every thing okie, with same config )

org.springframework.remoting.RemoteInvocationFailureException: Invocation of method
[public abstract java.lang.Long pageview.contract.CategoryDomainService.getPageViewByDomainCategory(com.vcc.pageview.request.DomainCategoryRequest)]
failed in JMS invoker remote service at queue [queue://categoryDomainQueue]; nested exception is java.lang.NoSuchMethodException:
$Proxy8.getPageViewByDomainCategory(com.vcc.pageview.request.DomainCategoryRequest)
at org.springframework.jms.remoting.JmsInvokerClientInterceptor.invoke(JmsInvokerClientInterceptor.java:214)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
at $Proxy8.getPageViewByDomainCategory(Unknown Source)
at pageview.domain.category.CategoryDomainDataService.getPageViewByDomainPageId(CategoryDomainDataService.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)

---

**Affects:** 3.2.2

**Attachments:**
- [SpringRestService.rar](https://jira.spring.io/secure/attachment/21188/SpringRestService.rar) (_7.31 kB_)

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
