### ISSUE TITLE
Spring cannot find bean aliased with placeholder [SPR-11018]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#15646]
**[Robert Kristofic](https://jira.spring.io/secure/ViewProfile.jspa?name=donroberto)** opened **[SPR-11018](https://jira.spring.io/browse/SPR-11018?redirect=false)** and commented

I have following configuration snippet:

```
<alias name="${jfos.timeService}TimeService" alias="timeService" />
	
<bean id="localTimeService" class="plaut.jfos.framework.shared.TimeDefaultService" />

<bean id="remoteTimeService"
		class="plaut.jfos.framework.transport.http.client.JfosHttpInvokerProxyFactoryBean"
    	p:serviceUrl="${jfos.server.url}/RemoteTimeService"
    	p:serviceInterface="plaut.jfos.framework.services.TimeService"
    	p:httpInvokerRequestExecutor-ref="defaultRequestExecutor" 
    />
```

Up to version 3.0.6 everything is OK, from version 3.0.7 (tested also on 3.2.4) I have following exception (no bean found):

```
[testng] Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private plaut.jfos.module.core.services.DatabaseConfigService plaut.jfos.framework.shared.CurrencyHelper.databaseConfigService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseConfigService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private plaut.jfos.framework.services.TimeService plaut.jfos.module.core.client.DatabaseConfigProvider.timeService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [plaut.jfos.framework.services.TimeService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=timeService)}
[testng] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:514)
[testng] 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
[testng] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:285)
[testng] 	... 43 more
```

---

**Affects:** 3.0.7

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/df7b661702a91e352e61d39a2ec5d56f7ad76d66, https://github.com/spring-projects/spring-framework/commit/e9a24da2253ea23a90f65d52f8dcf2ed3b15afc3

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
