### ISSUE TITLE
SpEl can not parse Long [SPR-11021]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#15649]
**[Sven Smets](https://jira.spring.io/secure/ViewProfile.jspa?name=sven)** opened **[SPR-11021](https://jira.spring.io/browse/SPR-11021?redirect=false)** and commented

When I use this tag

```
 <form:input path="myMap[${entry.key}]..." />
Map<Long, MyViewModel> myMap;```
 
and entry.key is bigger then an int (ex. 5,000,000,000), I get following error
```

org.springframework.expression.spel.SpelParseException: EL1035E:(pos 14): The value '5000000000' cannot be parsed as an int
at org.springframework.expression.spel.ast.Literal.getIntLiteral(Literal.java:79)
at org.springframework.expression.spel.standard.InternalSpelExpressionParser.maybeEatLiteral(InternalSpelExpressionParser.java:688)...```

In the maybeEatLiteral method it seems that Long should be supported, but int is chosen.

```
 
private boolean maybeEatLiteral()
  {
    Token t = peekToken();
    if (t == null) {
      return false;
    }
    if (t.kind == TokenKind.LITERAL_INT)
      push(Literal.getIntLiteral(t.data, toPos(t), 10));
    else if (t.kind == TokenKind.LITERAL_LONG)
      push(Literal.getLongLiteral(t.data, toPos(t), 10));
    else if (t.kind == TokenKind.LITERAL_HEXINT)
      push(Literal.getIntLiteral(t.data, toPos(t), 16));
    else if (t.kind == TokenKind.LITERAL_HEXLONG)
      push(Literal.getLongLiteral(t.data, toPos(t), 16));
    else if (t.kind == TokenKind.LITERAL_REAL)
      push(Literal.getRealLiteral(t.data, toPos(t), false));
    else if (t.kind == TokenKind.LITERAL_REAL_FLOAT)
      push(Literal.getRealLiteral(t.data, toPos(t), true));
    else if (peekIdentifierToken("true"))
      push(new BooleanLiteral(t.data, toPos(t), true));
    else if (peekIdentifierToken("false"))
      push(new BooleanLiteral(t.data, toPos(t), false));
    else if (t.kind == TokenKind.LITERAL_STRING)
      push(new StringLiteral(t.data, toPos(t), t.data));
    else {
      return false;
    }
    nextToken();
    return true;
  }
```

When I add an L to make it a java Long -> 5000000000L

```
<form:input path="myMap[${entry.key}L]..." />
```

I got an other error:

```
 java.lang.IllegalArgumentException: The field type is required
at org.springframework.util.Assert.notNull(Assert.java:112)
at org.springframework.webflow.mvc.view.ConvertingPropertyEditorAdapter.<init>(ConvertingPropertyEditorAdapter.java:48)
at org.springframework.webflow.mvc.view.BindingModel.findSpringConvertingPropertyEditor(BindingModel.java:277)
at org.springframework.webflow.mvc.view.BindingModel.findEditor(BindingModel.java:183)
at org.springframework.web.servlet.support.BindStatus.<init>(BindStatus.java:125)
at org.springframework.web.servlet.tags.form.AbstractDataBoundFormElementTag.getBindStatus(AbstractDataBoundFormElementTag.java:179)
at org.springframework.web.servlet.tags.form.AbstractDataBoundFormElementTag.getPropertyPath(AbstractDataBoundFormElementTag.java:199)... ```
 
```

---

**Affects:** 3.2.2, 3.2.4

**Reference URL:** http://stackoverflow.com/questions/19540206/hashmap-in-spring-form

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
