### ISSUE TITLE
@Bean and @Value with external property file causes bean creation mis-ordering [SPR-12873]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#17471]
**[Simon Wong](https://jira.spring.io/secure/ViewProfile.jspa?name=simonwg)** opened **[SPR-12873](https://jira.spring.io/browse/SPR-12873?redirect=false)** and commented

I tried to modify the Spring Security Sample to reproduce this issue. Please refer to the attachment.

```
@Bean
ServiceProperties serviceProperties(@Value("#{casProp.casServiceUrl}") String casServiceUrl) {
  // ....
}
```

I have externalized the CAS Service URL in a property file cas.properties. It could be resolved through `@Value` annotation through the property bean name called "casProp".

When I am using SPF <= 4.1.2, everything works fine. But the resolution failed in latest SPF version

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.cas.web.CasAuthenticationEntryPoint]: Factory method 'casAuthenticationEntryPoint' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceProperties' defined in class path resource [org/springframework/security/samples/config/SecurityConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: service cannot be empty.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceProperties' defined in class path resource [org/springframework/security/samples/config/SecurityConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: service cannot be empty.
```

I suspect that SPF >= 4.1.3 has bean creation ordering issue. The `@Bean` is called prior to `@Value` in method parameter.

---

**Affects:** 4.1.3, 4.1.4, 4.1.5, 4.1.6

**Attachments:**
- [cas-sample-jc.zip](https://jira.spring.io/secure/attachment/22721/cas-sample-jc.zip) (_3.39 kB_)
- [SPR-123873.zip](https://jira.spring.io/secure/attachment/22747/SPR-123873.zip) (_6.17 kB_)

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
