### ISSUE TITLE
Compatibility with Hibernate ORM 5.0 Final - create instance of entityManagerFactory [SPR-13391]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#17972]
**[Florian](https://jira.spring.io/secure/ViewProfile.jspa?name=flodes7)** opened **[SPR-13391](https://jira.spring.io/browse/SPR-13391?redirect=false)** and commented

Hello,

Spring can not instantiate the bean EntityManagerFactory with the final version of Hibernate ORM 5.0
Looking at the sources of Hibernate 5.0 RC3 / RC4, I realize that resolvePropertyAccessStrategy method has an additional parameter: containerClass (type: class)
https://github.com/hibernate/hibernate-orm/blob/c622d391990969a7d776cf06f565c5934c0d8be4/hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java

Errors :
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [applicationContextDb.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.hibernate.property.access.spi.PropertyAccessStrategyResolver.resolvePropertyAccessStrategy(Ljava/lang/String;Lorg/hibernate/EntityMode;)Lorg/hibernate/property/access/spi/PropertyAccessStrategy;
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1045)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:824)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
at org.springframework.context.support.ClassPathXmlApplicationContext.\<init>(ClassPathXmlApplicationContext.java:139)
at org.springframework.context.support.ClassPathXmlApplicationContext.\<init>(ClassPathXmlApplicationContext.java:83)

---

**Affects:** 4.2 GA

**Attachments:**
- [applicationContext.xml](https://jira.spring.io/secure/attachment/22996/applicationContext.xml) (_1005 bytes_)
- [applicationContextDataSource.xml](https://jira.spring.io/secure/attachment/22997/applicationContextDataSource.xml) (_693 bytes_)
- [applicationContextDb.xml](https://jira.spring.io/secure/attachment/22995/applicationContextDb.xml) (_1.14 kB_)

**Issue Links:**
- #17594 Compatibility with Hibernate ORM 5.0 GA

0 votes, 5 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
