### ISSUE TITLE
@Cacheable "condition" throwing an exception when one of the arguments is null [SPR-14173]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18745]
**[Lev Bornovalov](https://jira.spring.io/secure/ViewProfile.jspa?name=lbornov2)** opened **[SPR-14173](https://jira.spring.io/browse/SPR-14173?redirect=false)** and commented

Imagine the following method:

```
    @Override
	@Transactional(readOnly=true)
    @Cacheable(value="myCache",  key="{ #searchBean, #from, #size, #language}", condition="#searchBean.findInCache")
public List<Element> findBeans(final ElementSearchBean searchBean, final int from, final int size, final Language language) {
	}
```

Now imagine passing null as the searchBean.  You will get the following exception:

```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 0): Property or field 'findInCache' cannot be found on null
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:220) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:374) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
```

I disagree with this non-failsafe implementation.  Passing in "null" implies that the condition didn't pass,  And exception should **not** be thrown, IMHO.  Instead, no caching should be applied, as the condition didn't pass.

---

**Affects:** 4.2.5

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
