### ISSUE TITLE
PathMatchingResourcePatternResolver throws IOException inappropriately [SPR-14194]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18767]
**[Archie Cobbs](https://jira.spring.io/secure/ViewProfile.jspa?name=archie172)** opened **[SPR-14194](https://jira.spring.io/browse/SPR-14194?redirect=false)** and commented

This code:

```
public class Test {
    public static void main(String[] args) throws Throwable {
        new PathMatchingResourcePatternResolver()
          .getResources("classpath:java/lang/*.class");
    }
}
```

results in this exception:

```
Exception in thread "main" java.io.FileNotFoundException: class path resource [java/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:413)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
```

This seems to be a bug, or am I missing something obvious?

See also #16080.

---

**Affects:** 4.1.9

**Issue Links:**
- #16080 Option to have PathMatchingResourcePatternResolver not throw a FileNotFoundException when not a single file was matched

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
