### ISSUE TITLE
@AliasFor does not allow for deprecation of attributes [SPR-14280]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#18852]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[SPR-14280](https://jira.spring.io/browse/SPR-14280?redirect=false)** and commented

The validation of `@AliasFor` seems to disallow a simple use case where an attribute is deprecated and replaced by one with a different name. Example:

```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface FeignClient {
	@AliasFor("name")
	String value() default "";

	@Deprecated
	@AliasFor("value")
	String serviceId() default "";

	@AliasFor("value")
	String name() default "";
}
```

`context.getBeansWithAnnotation(...)` throws an exception if any beans have this annotation because it claims the aliases are invalid:

```
org.springframework.core.annotation.AnnotationConfigurationException: Attribute [value] in annotation [org.springframework.cloud.netflix.feign.FeignClient] must be declared as an @AliasFor [serviceId], not [name].
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.validate(AnnotationUtils.java:1991)
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.from(AnnotationUtils.java:1937)
	at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasNames(AnnotationUtils.java:1626)
	at org.springframework.core.annotation.AnnotationUtils.isSynthesizable(AnnotationUtils.java:1585)
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1368)
	at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:685)
	at 
...
```

---

**Affects:** 4.2.6

**Reference URL:** https://github.com/spring-cloud/spring-cloud-netflix/issues/1025#issuecomment-219702187

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
