### ISSUE TITLE
Better exception message when injecting Model with two constructors in a controller [SPR-14807]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19373]
**[Stéphane Nicoll](https://jira.spring.io/secure/ViewProfile.jspa?name=snicoll)** opened **[SPR-14807](https://jira.spring.io/browse/SPR-14807?redirect=false)** and commented

Consider the following use case

```java
public class A {

  public A(String one) { ... }

  public A(String one, String two) { ... }
}
```

Define `A` as a `Bean` and wrongly try to inject it in a controller

```java
@RequestMapping("/foo")
public String foo(A a) { ... }
```

Leads to

```
java.lang.NoSuchMethodException: com.example.A.<init>()
    at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_91]
    at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_91]
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:102) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:142) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.createAttribute(ServletModelAttributeMethodProcessor.java:80) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:102) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(
```

We can't inject a bean in a controller but the exception here does not help. If you know what you're doing, you new Spring MVC is going to try to instantiate your model class and couldn't find the constructor to use. An exception that phrases this would help debugging this particular use case.

---

**Affects:** 4.3.2

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
