### ISSUE TITLE
WebSocket support on Resin [SPR-14910]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19477]
**[Yanming Zhou](https://jira.spring.io/secure/ViewProfile.jspa?name=quaff)** opened **[SPR-14910](https://jira.spring.io/browse/SPR-14910?redirect=false)** and commented

[Resin](http://caucho.com/products/resin) is one of mainstream Java EE server, but is not supported by spring websocket.

```
java.lang.IllegalStateException: No suitable default RequestUpgradeStrategy found
                       	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.initRequestUpgradeStrategy(AbstractHandshakeHandler.java:143)
                       	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.<init>(AbstractHandshakeHandler.java:109)
                       	at org.springframework.web.socket.server.support.DefaultHandshakeHandler.<init>(DefaultHandshakeHandler.java:35)
```

---

0 votes, 5 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
