### ISSUE TITLE
RestTemplate.exchange throws IllegalArgumentException instead of RestClientException when a template cannot be expanded [SPR-14966]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#19533]
**[Andrew Garland](https://jira.spring.io/secure/ViewProfile.jspa?name=aeg)** opened **[SPR-14966](https://jira.spring.io/browse/SPR-14966?redirect=false)** and commented

When incorrect number of arguments are passed into the exchange method, the code currently throws IllegalArgumentException.  I think this should be ResourceAccessException or RestClientException since that better reflects the likelihood that a caller would want to catch this vs catching a runtime exception.

Sample top of the stacktrace.

java.lang.IllegalArgumentException: Not enough variable values available to expand '|'
at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:327)
at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:230)
at org.springframework.web.util.HierarchicalUriComponents.expandQueryParams(HierarchicalUriComponents.java:343)
at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:329)
at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:47)
at org.springframework.web.util.UriComponents.expand(UriComponents.java:163)
at org.springframework.web.util.DefaultUriTemplateHandler.expand(DefaultUriTemplateHandler.java:101)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:556)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475)

---

**Affects:** 4.2.6

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.
