### ISSUE TITLE
Document limitation of SpEL regarding minimum values for numeric literals

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20779]
**[Tamas Szekeres](https://jira.spring.io/secure/ViewProfile.jspa?name=firefoxpdm)** opened **[SPR-16232](https://jira.spring.io/browse/SPR-16232?redirect=false)** and commented

The `Tokenizer` cuts the integer literal `-2147483648` (whose value is equal to `Integer.MIN_VALUE`) into a `MINUS` token and a `LITERAL_INT`. The integer token, in itself, falls outside of the integer range, so from that point of view it is understandable that the parsing later fails, but from a usability one, it should work.

```java
public void testParseWhenMinIntegerSetShouldNotBeThrowingExceptionButItDoes() {
    final ExpressionParser parser = new SpelExpressionParser();
    final Expression expression = parser.parseExpression(String.valueOf(Integer.MIN_VALUE));
    expression.getValue();
}
```

```
FAILED: testParseWhenMinIntegerSetShouldNotBeThrowingExceptionButItDoes
org.springframework.expression.spel.SpelParseException: EL1035E: The value '2147483648' cannot be parsed as an int
	at org.springframework.expression.spel.ast.Literal.getIntLiteral(Literal.java:80)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.maybeEatLiteral(InternalSpelExpressionParser.java:840)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatStartNode(InternalSpelExpressionParser.java:500)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatPrimaryExpression(InternalSpelExpressionParser.java:343)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatUnaryExpression(InternalSpelExpressionParser.java:337)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatUnaryExpression(InternalSpelExpressionParser.java:316)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatPowerIncDecExpression(InternalSpelExpressionParser.java:293)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatProductExpression(InternalSpelExpressionParser.java:272)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatSumExpression(InternalSpelExpressionParser.java:255)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatRelationalExpression(InternalSpelExpressionParser.java:210)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatLogicalAndExpression(InternalSpelExpressionParser.java:198)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatLogicalOrExpression(InternalSpelExpressionParser.java:186)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.eatExpression(InternalSpelExpressionParser.java:146)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.doParseExpression(InternalSpelExpressionParser.java:127)
	at org.springframework.expression.spel.standard.SpelExpressionParser.doParseExpression(SpelExpressionParser.java:60)
	at org.springframework.expression.spel.standard.SpelExpressionParser.doParseExpression(SpelExpressionParser.java:32)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseExpression(TemplateAwareExpressionParser.java:73)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseExpression(TemplateAwareExpressionParser.java:60)
	...
Caused by: java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:499)
	at org.springframework.expression.spel.ast.Literal.getIntLiteral(Literal.java:76)
	... 44 more
```

---

**Affects:** 4.3.11, 4.3.12

**Comment by sbrannen** [comment]
First and foremost, thank you for the detailed report and apologies for taking so long to process this issue.

Please note that, depending on your exact use case, you may be able to work around this limitation if you're using the `StandardEvaluationContext` (and not the `SimpleEvaluationContext`) by making use of the type operator `T()` and `Integer.valueOf(String)` as demonstrated in the following test which passes.

```java
@Test
void parsingIntegerMinValueFromStringLiteral() {
	EvaluationContext context = new StandardEvaluationContext();
	ExpressionParser parser = new SpelExpressionParser();
	Expression expression = parser.parseExpression("T(Integer).valueOf('-2147483648')");
	assertThat(expression.getValue(context)).isEqualTo(Integer.MIN_VALUE);
}
```

**Comment by sbrannen** [comment]
After further investigation, I have determined that the following expressions can be used as workarounds, depending on your exact use case.

### Integer.MIN_VALUE (-2147483648)

- `-2147483647 - 1` -- always works (equal to `Integer.MIN_VALUE` + 1 - 1)
- `-2147483648L` -- always works (stores `Integer.MIN_VALUE` in a `Long`)
- `0.MIN_VALUE` -- always works, even with `SimpleEvaluationContext`; `0` can be any integer literal
- `T(Integer).MIN_VALUE` -- requires `StandardEvaluationContext`
- `T(Integer).valueOf('-2147483648')` -- requires `StandardEvaluationContext`

### Long.MIN_VALUE (-9223372036854775808)

- `-9223372036854775807 - 1` -- always works (equal to `Long.MIN_VALUE` + 1 - 1)
- `0L.MIN_VALUE` -- always works, even with `SimpleEvaluationContext`; `0` can be any long literal
- `T(Long).MIN_VALUE` -- requires `StandardEvaluationContext`
- `T(Long).valueOf('-9223372036854775808')` -- requires `StandardEvaluationContext`

**Comment by sbrannen** [comment]
@firefoxpdm, are you perhaps the same `firefoxpdm` that created this issue on JIRA?

**Comment by sbrannen** [comment]
While working on #32187, I realized that the easiest way to express `Integer.MIN_VALUE` within an expression (when not evaluated in a `StandardEvaluationContext`) is to simply calculate the valuate using SpEL's exponential power operator (`-2^31`).
