### ISSUE TITLE
We are facing the maximum open cursor issue [SPR-17001]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21539]
**[A V Vamsi krishna](https://jira.spring.io/secure/ViewProfile.jspa?name=vamckrisna)** opened **[SPR-17001](https://jira.spring.io/browse/SPR-17001?redirect=false)** and commented

+Error stack trace+

 ** 
|
| |
Caused by: java.sql.SQLException: ORA-01000: maximum open cursors exceeded 

at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) 
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399) 
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059) 
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522) 
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257) 
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587) 
at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:220) 
at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:48) 
at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:938) 
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150) 
at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798) 
at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901) 
at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:5631) 
at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385) 
at weblogic.jdbc.wrapper.PreparedStatement.execute(PreparedStatement.java:105) 
at org.springframework.jdbc.core.JdbcTemplate$6.doInCallableStatement(JdbcTemplate.java:1134) 
at org.springframework.jdbc.core.JdbcTemplate$6.doInCallableStatement(JdbcTemplate.java:1131) 
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1079) |
|

 

---

**Reference URL:** https://stackoverflow.com/questions/47044033/spring-5-0-1-namedjdbctemplate-batchupdate-ora-01000-maximum-open-cursors-excee

**Issue Links:**
- #20687 Doc: ParameterMetaData.getParameterType performance on Oracle 12c

**Comment by sabinsumghershanan** [comment]
@jhoeller I am also facing the issue with open cursors in my application. I am using spring version 5.0.16-RELEASE and ojdbc6 jar and java1.7. The open cursor value has been set to 400 and connction pool value is 40. But still the open cursors get exceeded. Could you please provide some recommendation for the same?

**Comment by iKoru** [comment]
@jhoeller Me, too. I'm on Spring boot 2.2.5.RELEASE(maybe based on Spring 5.2.6.RELEASE or something) and ojdbc8.jar and java 1.8.

**Comment by pkumaravel** [comment]
me too facing same issue using Spring JDBC 5.1.3.RELEASE with ojdbc7 driver on a Oracle 12c database, any suggestion or solution.

**Comment by sabinsumghershanan** [comment]
@pkumaravel I resolved the issue by adding spring.jdbc.getParameterType.ignore=true, as a custom property in was. You can also add it as a spring.properties file in the root of the classpath of your project.
