### ISSUE TITLE
More error details in RestTemplate client and server exception [SPR-17130]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21667]
**[Jerzy Krolak](https://jira.spring.io/secure/ViewProfile.jspa?name=jerzykrlk)** opened **[SPR-17130](https://jira.spring.io/browse/SPR-17130?redirect=false)** and commented

The default `RestTemplate` HTTP error exceptions might contain some preview of the response body, along with the HTTP status code.

So that, instead of this:

```java
org.springframework.web.client.HttpClientErrorException.BadRequest: 400 Bad Request
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```

... I could see this:

```java
org.springframework.web.client.HttpClientErrorException.BadRequest: 400 Bad Request [<html><head><title>page not found</title>...]
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```

or even this:

```java
org.springframework.web.client.HttpClientErrorException.Conflict: 409 Conflict [{
"error": {
 "errors": [
  {
   "domain": "global",
   "reason": "conflict",
   "message": "You already own this bucket. Please select another name."
  }
 ],
 "code": 409,
 "message": "You already own this bucket. Please select another name."
 }
}]
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```

This should not introduce too much overhead, as the response is already there, in `byte [] body`.

---

**Affects:** 5.0.8

**Issue Links:**
- #19967 Exception hierarchy under HttpClientException and HttpServerException for the RestTemplate

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1956

**Comment by rstoyanchev** [comment]
This is superseded by #1956.
