### ISSUE TITLE
Suppress Reactor Netty "disconnected client" exceptions the logs [SPR-17257]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21790]
**[David Terk](https://jira.spring.io/secure/ViewProfile.jspa?name=david.terk)** opened **[SPR-17257](https://jira.spring.io/browse/SPR-17257?redirect=false)** and commented

I am seeing  WARN 15 — [-server-epoll-9] o.s.h.s.r.ReactorHttpHandlerAdapter : Handling completed with error: Connection has been closed

All over my logs.  Nearly every request through my gateway.  Why would this happen?  All requests are completing without ANY errors.

Sorry but I don't have much more info than that.  I am using Spring Cloud Gateway.  Seems to happen on calls which make a POST.

I am finding that I need to turn off logging on both

org.springframework.http.server.reactive.ReactorHttpHandlerAdapter
org.springframework.web.server.adapter.HttpWebHandlerAdapter

Otherwise there is an unbelievable amount of logs being generated from what appears to be requests and responses that are functioning normally.

 

Would be useful to show the trace to have an idea where it is coming from.

---

**Affects:** 5.0.8, 5.1.2

**Issue Links:**
- #21875 Disconnected client exception logging should differentiate remote service exceptions too

0 votes, 5 watchers

**Comment by dave-fl** [comment]
@spencergibb @violetagg Could you comment at all on this issue.

This still exists with latest Greenwich and Californium Snapshots.  Non stop logging of `ServerHttpResponse already committed (200 OK)`

**Comment by srikanthbommareddy** [comment]
We are facing same issue in Spring Cloud Gateway. 

--------------------POM-------------------------------------------------------
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Finchley.M9</spring-cloud.version>
	</properties>
--------------------POM-------------------------------------------------------

------------------EXCEPTION--------------------------------------
ERROR o.s.w.s.a.HttpWebHandlerAdapter:213 - Unhandled failure: Connection has been closed, response already set (status=200)
10.0.0.15:9092 2019-03-14 03:34:01 ERROR o.s.h.s.r.ReactorHttpHandlerAdapter:76 - Handling completed with error
reactor.ipc.netty.channel.AbortedException: Connection has been closed
        at reactor.ipc.netty.channel.ChannelOperationsHandler.discard(ChannelOperationsHandler.java:366)
        at reactor.ipc.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:376)
        at reactor.ipc.netty.channel.ChannelOperationsHandler.handlerRemoved(ChannelOperationsHandler.java:207)
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:670)
        at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:922)
        at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:888)
        at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:880)
        at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1416)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:865)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at java.lang.Thread.run(Thread.java:745)
------------------EXCEPTION--------------------------------------

**Comment by rstoyanchev** [comment]
@srikanthbommareddy, @bono007, I've created what should be a fix. That should be available in [the next 5.1.6.BUILD-SNAPSHOT](https://build.spring.io/browse/SPR-PUB9). It would be great if you could confirm it suppresses those exceptions.

**Comment by bono007** [comment]
@rstoyanchev I am sorry I did not get you more information when you asked for it earlier. I have been meaning to do that. You fixed it before i got around to it. Thx. I will verify next week when I get back in the office.

**Comment by bono007** [comment]
@rstoyanchev I upgraded to `SpringBoot 2.1.4 -> Spring 5.1.6` to pickup the fix and it does in fact suppress the log message. Thank you very much - especially for that quick turnaround.

**Comment by rstoyanchev** [comment]
Thanks for taking the tie to confirm!

**Comment by Blokko** [comment]
Hi @rstoyanchev,
we get the same logged exception as described here and which you "fixed" with 5f11109.
Now it's getting funny: Because we're from Germany, our exception message text does not contain "connection reset by peer" or "broken pipe", we get the German equivalent "Eine bestehende Verbindung wurde softwaregesteuert durch den Hostcomputer abgebrochen". 😄
So what now?
