### ISSUE TITLE
FatalBeanException while instantiating RestTemplate in Junit Test in Spring Version 5.1.4

### ISSUE THREAD

**Issue by Prazhant** [spring-projects/spring-framework#22274]
I am using Spring Boot 2.1.2(Spring Version is 5.1.4) and getting FatalBeanException while instantiating RestTemplate in Junit test case. It works fine when I downgrade Spring Version to 5.1.3. I dont see any changes to RestTemplate in release notes of 5.1.4. 

java.lang.NoClassDefFoundError: org/springframework/beans/FatalBeanException
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:59)
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:76)
	at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:148)
	at .
.
.
.
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.FatalBeanException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by rstoyanchev** [comment]
This looks like a dependency issue. The actual error is a `ClassNotFoundException`. From the (incomplete) stack trace shown it looks like this might be as a result of `Jackson2ObjectMapperBuilder` trying to raise `FatalBeanException` for an unknown feature .

**Comment by Prazhant** [comment]
It fails for: -Spring Boot 2.1.2 uses Spring 5.1.4 which uses Jackson-Core 2.9.8. Even if I downgrade version of Jackson-Core to 2.7.x and above, it gives error.

When I downgrade Spring to 5.1.3 and Jackson Core 2.9.7, it works fine. So,  I think its combination of Spring and Jackson.

**Comment by snicoll** [comment]
> When I downgrade Spring to 5.1.3 and Jackson Core 2.9.7, it works fine. So, its combination of Spring and Jackson.

Given the information that you have provided, there is no indication that such a problem exists. A `ClassNotFoundException` is a pretty serious issue that usually results from broken projects. Perhaps a jar file got corrupted when it was downloaded from a repository and the java process can't open it? Try to delete `5.1.4.RELEASE` from your cache and try again. If that doesn't work, you can attach a sample that we can run ourselves to reproduce the problem.
