### ISSUE TITLE
simpMessagingTemplate convertAndSendToUser lot of waiting threads blocking other functionality

### ISSUE THREAD

**Issue by sarathpetec** [spring-projects/spring-framework#22295]
We are using Stomp, SpringBoot, and WebSockets in our application. The server application is doing the following:

**1)** Generating messages to be pushed to the users,

**2)** Accepting WebSocket connections and

**3)** pushing messages to ActiveMQ stomp broker.

Thread dump shows a lot of waiting threads associated with the simpMessagingTemplate convertAndSendToUser API call.

Two instances of the application are running in a cloud. This application generates messages and pushes to ActiveMQ stomp broker (running separately) using simpMessagingTemplate convertAndSendToUser API.

We use Gatling for simulating user WebSocket connections for load testing. The Gatling runs on a separate instance. The application works fine for 2000 user connections with a load of 20,000 messages per minute. Once we increase the users to 4000 we see that the message generation thread stops. Users are getting connected to the same servers without any problem though.

If we comment the simpMessagingTemplate convertAndSendToUser API call then everything works perfectly fine (both generate messages and new WebSocket connections). So we doubt the issue with convertAndSendToUser API.

 

We have created the same issue is StackOverflow as well.

[Stackoverflow Question Link](https://stackoverflow.com/questions/54284576/simpmessagingtemplate-convertandsendtouser-lot-of-waiting-threads-blocking-other)

**Environment Details:** 

```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
de-root-centos7-64
de-base-centos7-120
```
 **Spring Version:** 
```
 org.springframework : 5.1.3.RELEASE
 Spring-boot: 2.1.1.RELEASE
```

**Dependency which we are using:** 
```
<dependency>
 <groupId>org.springframework</groupId>
 <artifactId>spring-websocket</artifactId>
 <scope>compile</scope>
</dependency>

<dependency>
 <groupId>io.projectreactor.netty</groupId>
 <artifactId>reactor-netty</artifactId>
</dependency>
<dependency>
 <groupId>io.netty</groupId>
 <artifactId>netty-all</artifactId>
</dependency>

<dependency>
 <groupId>org.webjars</groupId>
 <artifactId>webjars-locator-core</artifactId>
</dependency>
<dependency>
 <groupId>org.webjars</groupId>
 <artifactId>sockjs-client</artifactId>
 <version>1.0.2</version>
</dependency>
<dependency>
 <groupId>org.webjars</groupId>
 <artifactId>stomp-websocket</artifactId>
 <version>2.3.3</version>
</dependency>
<dependency>
 <groupId>org.webjars</groupId>
 <artifactId>bootstrap</artifactId>
 <version>3.3.7</version>
</dependency>
<dependency>
 <groupId>org.webjars</groupId>
 <artifactId>jquery</artifactId>
 <version>3.1.0</version>
</dependency>
```
**Below one is the heap dump snippet which we get it from the server**
```
"ForkJoinPool-1-worker-246" #577 daemon prio=5 os_prio=0 tid=0x00007f7a28005000 nid=0x329c sleeping[0x00007f7978008000]
 java.lang.Thread.State: TIMED_WAITING (sleeping)
 at java.lang.Thread.sleep(Native Method)
 at reactor.util.concurrent.WaitStrategy$Sleeping.waitFor(WaitStrategy.java:319)
 at reactor.core.publisher.MonoProcessor.block(MonoProcessor.java:211)
 at reactor.core.publisher.MonoProcessor.block(MonoProcessor.java:176)
 at org.springframework.util.concurrent.MonoToListenableFutureAdapter.get(MonoToListenableFutureAdapter.java:55)
 at org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler$SystemStompConnectionHandler.forward(StompBrokerRelayMessageHandler.java:990)
 at org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler.handleMessageInternal(StompBrokerRelayMessageHandler.java:559)
 at org.springframework.messaging.simp.broker.AbstractBrokerMessageHandler.handleMessage(AbstractBrokerMessageHandler.java:256)
 at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
 at org.springframework.messaging.support.ExecutorSubscribableChannel.sendInternal(ExecutorSubscribableChannel.java:100)
 at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:136)
 at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:122)
 at org.springframework.messaging.simp.SimpMessagingTemplate.sendInternal(SimpMessagingTemplate.java:187)
 at org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:162)
 at org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:48)
 at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
 at org.springframework.messaging.simp.user.UserDestinationMessageHandler.handleMessage(UserDestinationMessageHandler.java:217)
 at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
 at org.springframework.messaging.support.ExecutorSubscribableChannel.sendInternal(ExecutorSubscribableChannel.java:100)
 at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:136)
 at org.springframework.messaging.simp.SimpMessagingTemplate.sendInternal(SimpMessagingTemplate.java:187)
 at org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:162)
 at org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:48)
 at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
 at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151)
 at org.springframework.messaging.simp.SimpMessagingTemplate.convertAndSendToUser(SimpMessagingTemplate.java:229)
 at org.springframework.messaging.simp.SimpMessagingTemplate.convertAndSendToUser(SimpMessagingTemplate.java:218)
 at org.springframework.messaging.simp.SimpMessagingTemplate.convertAndSendToUser(SimpMessagingTemplate.java:204)
 at com.test.test1.websocket.domain.PushMessageManager.lambda$sendMDSMessage$2(PushMessageManager.java:84)
```

**Comment by sdeleuze** [comment]
@rstoyanchev [This](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompBrokerRelayMessageHandler.java#L990) `get()` blocking call in a method that returns `ListenableFuture<Void>` looks suspicious to me. Do you think we could use a `FailureCallback` to wrap the exception to a `MessageDeliveryException` in a non blocking way?

**Comment by rstoyanchev** [comment]
@sdeleuze , yes, those calls through the `SimpMessagingTemplate` are blocking, or otherwise the caller can't know if the message was successfully forwarded to the broker. The only other alternative would be to send errors to some error channel, but without any blocking there is no back pressure of any kind and could result in too many messages being sent.
