### ISSUE TITLE
SynchronossFilePart.transferTo should should get inputStream from content instead of FileStreamStorage.getInputStream.

### ISSUE THREAD

**Issue by starrybleu** [spring-projects/spring-framework#22298]
After https://github.com/spring-projects/spring-framework/issues/21464, I'm working file upload with spring-webflux and spring-web 5.1.4.

I found that default implementation of FilePart is SynchronossFilePart and SynchronossFilePart implemented `transfer(Path dest)`.

I think `Mono<Void> transferTo(Path dest)` method is supposed to write data into the given destinated path from content of part(FilePart).

However, implemented transferTo(Path dest) is trying read input via getStorage().getInputStream() which is using FileStreamStorage with different path provided by `DefaultPartBodyStreamStorageFactory.getTempFile`.

So, `getStorage().getInputStream()` is throwing IllegalArguementException because temporary file created by `DefaultPartBodyStreamStorageFactory.getTempFile` doesn't actually exist.

I propose that `Mono<Void> transferTo(Path dest)` should read input data from content of FilePart instead of nonexistent temporary created file.

FYI.

![image](https://user-images.githubusercontent.com/14271094/51602674-ee71ff00-1f4a-11e9-8345-0570f7cc5584.png)

![image](https://user-images.githubusercontent.com/14271094/51602758-2711d880-1f4b-11e9-8df5-93706a6f6876.png)

![image](https://user-images.githubusercontent.com/14271094/51602810-427ce380-1f4b-11e9-9a6d-3f0f58054be9.png)

**Comment by starrybleu** [comment]
Sure. I tried small file ( < 10kb ), then it worked.
I found a big file ( > 10kb ) had been created in specified temporary directory and instantly deleted.

I think this is related in `NameAwarePurgableFileInputStream`.

I'm doing force throw an exception, and handle it by storing as a fallback as below.

FYI. I attached a snippet. Please see 

```java
    public Mono<String> uploadToS3Bucket(final String bucketName, final String filename, final FilePart part) {
        return DataBufferUtils.join(part.content())
                .flatMap(dataBuffer -> {
                    return Mono.zip(Mono.just(filename), Mono.error(new RuntimeException())); // note force throw
                })
                .map(Tuple2::getT1)
                .doOnError(ex -> {
                            Path pathForRestore = FilesHelper.createTempFileWithGivenFilename(filename);
                            part.transferTo(pathForRestore).block(); // fixme threshold 10kb
                        }
                );
    }

```

Am I doing wrong with it?

**Comment by starrybleu** [comment]
Yes, I could.

I changed the operator which is handling an exception by using onErrorResume.

But, there is still the same problem, additionally when I tried to do with onErrorMap.

I think that once the parameter `FilePart` had been read by an operator and if the parent thread returned, then contents(inputStream) has gone for a file over 10kb. Am I understanding right?

[The changed code accordingly maybe]

```java
    public Mono<String> uploadToS3Bucket(final String bucketName, final String filename, final FilePart part) {
        return DataBufferUtils.join(part.content())
                .flatMap(dataBuffer -> {
                    return Mono.zip(Mono.just(filename), Mono.error(new RuntimeException())); // note force throw
                })
                .map(Tuple2::getT1)
                .onErrorResume(ex -> {
                            Path pathForRestore = FilesHelper.createTempFileWithGivenFilename(filename);
                            return part.transferTo(pathForRestore).flatMap(discarded -> Mono.error(ex));                        
                });
    }
```

And I attached the stack trace below.

```
2019-01-29 10:41:25.880 ERROR 25140 --- [callback-thread] reactor.Mono.OnAssembly.1                : | onError(java.lang.IllegalStateException: Unable to create the inputStream.)
2019-01-29 10:41:25.881 ERROR 25140 --- [callback-thread] reactor.Mono.OnAssembly.1                : 

java.lang.IllegalStateException: Unable to create the inputStream.
	at org.synchronoss.cloud.nio.stream.storage.FileStreamStorage.newFileInputStream(FileStreamStorage.java:324)
	at org.synchronoss.cloud.nio.stream.storage.FileStreamStorage.getInputStream(FileStreamStorage.java:245)
	at org.springframework.http.codec.multipart.SynchronossPartHttpMessageReader$SynchronossFilePart.transferTo(SynchronossPartHttpMessageReader.java:333)
	at kr.co.opensurvey.somedia.v1.service.UploadService.lambda$uploadToS3Bucket$2(UploadService.java:44)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
	at reactor.core.publisher.MonoZip$ZipInner.onError(MonoZip.java:343)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:167)
	at kr.co.opensurvey.somedia.v1.service.UploadService.lambda$null$6(UploadService.java:79)
	at com.amazonaws.event.ProgressListenerChain.progressChanged(ProgressListenerChain.java:98)
	at com.amazonaws.event.SDKProgressPublisher$1.run(SDKProgressPublisher.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.RuntimeException: Uploading to stg-survey-answer-images/4fee352c-665b-4121-9275-31360a965a42.jpg
		... 8 common frames omitted
		Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:183)
	kr.co.opensurvey.somedia.v1.service.UploadService.addProgressListeners(UploadService.java:69)
Error has been observed by the following operator(s):
	|_	Mono.create ⇢ kr.co.opensurvey.somedia.v1.service.UploadService.addProgressListeners(UploadService.java:69)
	|_	Mono.zip ⇢ kr.co.opensurvey.somedia.v1.service.UploadService.lambda$uploadToS3Bucket$0(UploadService.java:37)
	|_	Mono.flatMap ⇢ kr.co.opensurvey.somedia.v1.service.UploadService.uploadToS3Bucket(UploadService.java:31)
	|_	Mono.map ⇢ kr.co.opensurvey.somedia.v1.service.UploadService.uploadToS3Bucket(UploadService.java:39)

	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoOnErrorResume] :
	reactor.core.publisher.Mono.onErrorResume(Mono.java:3029)
	kr.co.opensurvey.somedia.v1.service.UploadService.uploadToS3Bucket(UploadService.java:40)
Error has been observed by the following operator(s):
	|_	Mono.onErrorResume ⇢ kr.co.opensurvey.somedia.v1.service.UploadService.uploadToS3Bucket(UploadService.java:40)

Caused by: java.io.FileNotFoundException: C:\Users\terrylee\AppData\Local\Temp\nio-file-upload\nio-body-1-aeff811c-24f5-47ec-859c-b93247981b2c.tmp (지정된 파일을 찾을 수 없습니다)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.synchronoss.cloud.nio.stream.storage.NameAwarePurgableFileInputStream.<init>(NameAwarePurgableFileInputStream.java:49)
	at org.synchronoss.cloud.nio.stream.storage.FileStreamStorage.newFileInputStream(FileStreamStorage.java:322)
	... 21 common frames omitted
```

**Comment by rstoyanchev** [comment]
Isn't it the case that you can either read the raw content or transfer to a file? The example seems to be doing both which makes no sense.

**Comment by starrybleu** [comment]
Maybe you're right. First I tried to read the raw content of filePart using DataBufferUtils and send it to other storage service as InputStream. On failed to previous trial, I want to keep contents to a local file. Does it itself make no sense?

Should I keep raw content manually before using it?

What I intended at the time I created issue, framework can do that or at least have possibility to change MAX_THRESHOLD.

Any further possibility?

**Comment by sdeleuze** [comment]
As explained previously, I understand the need to configure this max threshold, but we are likely to rework multipart support in a way that will maybe not create temporary files anymore via https://github.com/spring-projects/spring-framework/issues/21659, so I would vote for waiting this evolution to be completed instead of introducing some configuration that will make no sense in a few months.

Any thoughts @rstoyanchev @poutsma ?

**Comment by rstoyanchev** [comment]
Saving the content to a local file should be possible with the `transferTo` method. Do you have something that demonstrates it's not?

**Comment by starrybleu** [comment]
Thank you for your information, @sdeleuze. I will follow up to that issue #21659.

By the way, it should be possible in a synchronous way. But I encountered it in a asynchronous way. @rstoyanchev .

Thanks guys.

**Comment by rstoyanchev** [comment]
@starrybleu sorry, it's gotten confusing. Is there still an issue or can we close this? If there is an issue please provide a sample.

**Comment by starrybleu** [comment]
Oh, I missed closing this issue. Thanks.

**Comment by rstoyanchev** [comment]
No worries, thanks.
