### ISSUE TITLE
Kotlin Beans DSL doesn't work with `object`

### ISSUE THREAD

**Issue by nfrankel** [spring-projects/spring-framework#22317]
**Affects:** 5.1.4.RELEASE

Those are the steps to reproduce:

* Create a new project using Maven/Kotlin/Spring Web Flux with the Spring Initializer
* Use the following code snippet:

```kotlin
    import org.springframework.boot.autoconfigure.SpringBootApplication
    import org.springframework.boot.runApplication
    import org.springframework.context.support.beans
    
    @SpringBootApplication
    class FailApplication
    
    fun beans() = beans {
        bean {
            object : Foo() {
                override fun bar() = 42
            }
        }
    }
    
    abstract class Foo {
        abstract fun bar(): Int
    }
    
    fun main(args: Array<String>) {
        runApplication<FailApplication>(*args) {
            addInitializers(beans())
        }
    }
```

This is the log I get:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)

2019-01-28 16:36:47.794 ERROR 87999 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: ch/frankel/blog/spring/fail/FailApplicationKt$beans$1$1$1
	at ch.frankel.blog.spring.fail.FailApplicationKt$beans$1.invoke(FailApplication.kt:41) ~[classes/:na]
	at ch.frankel.blog.spring.fail.FailApplicationKt$beans$1.invoke(FailApplication.kt) ~[classes/:na]
	at org.springframework.context.support.BeanDefinitionDsl.initialize(BeanDefinitionDsl.kt:286) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.BeanDefinitionDsl.initialize(BeanDefinitionDsl.kt:78) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at ch.frankel.blog.spring.fail.FailApplicationKt.main(FailApplication.kt:29) [classes/:na]
Caused by: java.lang.ClassNotFoundException: ch.frankel.blog.spring.fail.FailApplicationKt$beans$1$1$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_181]
	... 8 common frames omitted


Process finished with exit code 1
```

Expected behavior: starts normally

Mitigation: create a dedicated child class of `Foo` and register it. This works, but forces to create additional boiler-plate code

**Comment by sdeleuze** [comment]
Indeed, I think this is triggered by `T::class.java.name` [here](https://github.com/spring-projects/spring-framework/blob/d3b5ba7a361866ea96fcc64d3f76be9b5be3b8e4/spring-context/src/main/kotlin/org/springframework/context/support/BeanDefinitionDsl.kt#L234) since there is no matching Java class in that case.

**Comment by sdeleuze** [comment]
Look like a **very** strange Kotlin bug, I have opened https://youtrack.jetbrains.com/issue/KT-29595.

**Comment by sdeleuze** [comment]
The issue seems to be confirmed on Kotlin side, so I close that one since I don't think we need to do something on Spring side.
