### ISSUE TITLE
WebFlux with undertow throws exception when serving big static files.

### ISSUE THREAD

**Issue by lkolek** [spring-projects/spring-framework#22413]
**Affects:** \5.1.3, 5.0.*

---

When serving big enough static resources (file), WebFlux + Undertow throws following exception:
`java.io.IOException: UT000094: Blocking await method called from IO thread.`

It is caused by `Channels.transferBlocking` call in `org.springframework.http.server.reactive.UndertowServerHttpResponse` class:

	@Override
	public Mono<Void> writeWith(Path file, long position, long count) {
		return doCommit(() ->
				Mono.defer(() -> {
					try (FileChannel source = FileChannel.open(file, StandardOpenOption.READ)) {
						StreamSinkChannel destination = this.exchange.getResponseChannel();
						Channels.transferBlocking(destination, source, position, count);
						return Mono.empty();
					}
					catch (IOException ex) {
						return Mono.error(ex);
					}
				}));
	}

Moving this call to IO threads seems to work, but migt be sub-optimal (see: `.subscribeOn(Schedulers.elastic())` near end):

	@Override
    public Mono<Void> writeWith(Path file, long position, long count) {
        return doCommit(() ->
                Mono.defer(() -> {
                    try (FileChannel source = FileChannel.open(file, StandardOpenOption.READ)) {
                        StreamSinkChannel destination = this.exchange.getResponseChannel();
                        Channels.transferBlocking(destination, source, position, count);
                        return Mono.empty();
                    }
                    catch (IOException ex) {
                        ex.printStackTrace();
                        return Mono.error(ex);
                    }
                }))
                // TO HANDLE BLOCKING!
                .subscribeOn(Schedulers.elastic())
                ;
    }

Stack trace:

	2019-02-14 14:19:29.329 ERROR 44484 --- [   XNIO-1 I/O-1] io.undertow                              : UT005085: Connection io.undertow.server.protocol.http.HttpServerConnection@13871769 for exchange HttpServerExchange{ GET /test.mp4 request {Accept=[*/*], Accept-Language=[pl-pl], Accept-Encoding=[identity], User-Agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15], Range=[bytes=0-1], Connection=[keep-alive], X-Playback-Session-Id=[B6657529-5085-4A47-AD60-089BDEC59DD5], Cookie=[Idea-e386df9=4ce8f3fb-c39f-415a-8ff1-c19f2999954d; Idea-e386df8=603d089f-ad6a-4efd-8e7b-186238fff603; _ga=GA1.1.524791181.1511035090], Referer=[http://localhost:8080/test.mp4], Host=[localhost:8080]} response {Connection=[keep-alive], Last-Modified=[Wed, 13 Feb 2019 19:58:38 GMT], Content-Range=[bytes 0-1/121486134], Content-Length=[2], Content-Type=[video/mp4], Accept-Ranges=[bytes], Date=[Thu, 14 Feb 2019 13:19:29 GMT]}} was not closed cleanly, forcibly closing connection
	java.io.IOException: UT000094: Blocking await method called from IO thread. Blocking IO must be dispatched to a worker thread or deadlocks will result.
	at io.undertow.server.HttpServerExchange$WriteDispatchChannel.awaitWritable(HttpServerExchange.java:2035)
	at org.xnio.channels.Channels.transferBlocking(Channels.java:514)
	at org.springframework.http.server.reactive.UndertowServerHttpResponse.lambda$null$0(UndertowServerHttpResponse.java:131)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3608)
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:146)
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60)
	at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3608)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1476)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:422)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:212)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3608)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:275)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:849)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2041)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1849)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1723)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3608)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:442)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:212)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3608)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3608)
	at org.springframework.http.server.reactive.UndertowHttpHandlerAdapter.handleRequest(UndertowHttpHandlerAdapter.java:87)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

**Comment by rstoyanchev** [comment]
The `transferBlocking` call was introduced in 45aa1edf871e7e86cbd9523146a94b911d944736 when a similar issue was reported in #19906. Unfortunately I don't see any explanation around that. @poutsma any thoughts?

**Comment by gitgispartner** [comment]
Looking at previous code, it was trying to send all data there. For bigger data - up to buffer sizes.  As doc says: 

> An invocation of this method may or may not transfer all of the requested bytes; whether or not it does so depends upon the natures and states of the channels.  Fewer than the requested number of bytes will be transferred if the source channel has fewer than count bytes remaining, **or if the source channel is non-blocking and has fewer than count bytes immediately available in its input buffer**.

So previous implementation was a bug also.

As I understand this issue, you can call `Channels.transferBlocking` in working thread, ie.`subscribeOn(Schedulers.elastic())`  (not blocking Undertow) or replace it with some kind of flux-based, non-blocking transfering.

**Comment by lkolek** [comment]
You may look at [http://undertow.io/javadoc/1.3.x/io/undertow/io/AsyncSenderImpl.html#transferFrom-java.nio.channels.FileChannel-io.undertow.io.IoCallback-](http://undertow.io/javadoc/1.3.x/io/undertow/io/AsyncSenderImpl.html#transferFrom-java.nio.channels.FileChannel-io.undertow.io.IoCallback-) or it's implementation.

**Comment by lkolek** [comment]
I have implementation, that seems to work pretty well, handling small files in current thread, while using `Schedulers.elastic()` to do rest of the job. 

```java
    @Override
    public Mono<Void> writeWith(Path file, long position, long count) {
        return doCommit(() ->
                Mono.defer(() -> {
                    try (FileChannel source = FileChannel.open(file, StandardOpenOption.READ)) {
                        final StreamSinkChannel destination = this.exchange.getResponseChannel();

                        logger.trace("trans start on th:" + Thread.currentThread().getName());

                        final long result = destination.transferFrom(source, position, count);
                        if (result < count) {
                            logger.trace("trans need to continue: " + (count-result));
                            return Mono.just(1)
                                    .publishOn(Schedulers.elastic())
                                    .flatMap((x)->{
                                        try (FileChannel source2 = FileChannel.open(file, StandardOpenOption.READ)) {
                                            logger.trace("trans continue on th:" + Thread.currentThread().getName());
                                            Channels.transferBlocking(destination, source2, position + result, count - result);
                                            return Mono.just(2);
                                        }catch (IOException ex){
                                            return Mono.error(ex);
                                        }
                                    }).then();

                        } else {
                            return Mono.empty();
                        }
                    }
                    catch (IOException ex) {
                        return Mono.error(ex);
                    }
                })
        );
    }
```

**Comment by rstoyanchev** [comment]
Ideally the solution should not involve a dedicated thread but registering for a callback when writing is possible again.
