### ISSUE TITLE
RestController Reactor and Schedulers.elastic()

### ISSUE THREAD

**Issue by marcin-kasinski** [spring-projects/spring-framework#22433]
I dont know whether it is good place or not.

Env:
Spring boot 2.1.3:

pom: https://github.com/marcin-kasinski/SpringBootMicroservice/blob/master/pom.xml

I have a problem with  Restcontroller

To simplify I've changed it to be as simple as posible
```

@RequestMapping("/get-by-email4")
	public Mono<User> getByEmail4(@RequestParam(value = "email", defaultValue = ".") String email,@RequestHeader HttpHeaders headers) {
	  return Mono.fromCallable(() -> {
			  log.info("getByEmail4 START");
				User user = null;
				try {
					Thread.sleep(1000);
					String threadName=Thread.currentThread().getName() ;
					log.info("->->->->getEmail threadName "+threadName);
					return new User();					
				} catch (Exception e) {
					log.error("getByEmail4 error :"+e);
				}
				log.info("getByEmail4 END");
				return user;
		    }).subscribeOn(Schedulers.elastic());
	}

```
When I test it manually everything works fine	

I have problem with performance test
I test this endpoint with:

`siege -b -c 100 -r 10 http://192.168.1.239:9191/api/get-by-email4?email=ajax@ajax.com`

Based on logs I can see that my code is executed but there is lots of exceptions:
```

2019-02-19 17:39:29.340  INFO [SpringBootMicroservice,ca5fb133753715a6,f88c2dca38578211,true] 7708 --- [     elastic-57] mk.MicroserviceController                : ->->->->getEmail threadName elastic-57
2019-02-19 17:39:29.344  INFO [SpringBootMicroservice,27b74a1b19cf6d6b,168bbbcd07321099,true] 7708 --- [     elastic-30] mk.MicroserviceController                : ->->->->getEmail threadName elastic-30
2019-02-19 17:39:29.345  INFO [SpringBootMicroservice,b1f0bc3ece931717,ec75654d08f2ceb8,true] 7708 --- [     elastic-54] mk.MicroserviceController                : ->->->->getEmail threadName elastic-54
2019-02-19 17:39:29.346 ERROR [SpringBootMicroservice,d93da046f70f3123,e30bd6ed15714e3a,true] 7708 --- [     elastic-61] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.lang.NullPointerException: null
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:209) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:175) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:169) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:131) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:387) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:453) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.context.request.async.DeferredResult.setResult(DeferredResult.java:238) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$DeferredResultSubscriber.onComplete(ReactiveTypeHandler.java:465) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123) ~[reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:113) ~[spring-cloud-sleuth-core-2.1.0.M2.jar:2.1.0.M2]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:251) ~[reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:291) ~[reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) ~[reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) ~[reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:69) ~[spring-cloud-sleuth-core-2.1.0.M2.jar:2.1.0.M2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]

2019-02-19 17:39:29.346  INFO [SpringBootMicroservice,980443c5520c141e,2f92bb1d82ab3aa1,true] 7708 --- [     elastic-56] mk.MicroserviceController                : ->->->->getEmail threadName elastic-56
2019-02-19 17:39:29.357  INFO [SpringBootMicroservice,59d75a75d7e371f4,4e514a2ac70717e3,true] 7708 --- [     elastic-20] mk.MicroserviceController                : ->->->->getEmail threadName elastic-20
2019-02-19 17:39:29.369  INFO [SpringBootMicroservice,ad1af493a04646a2,79d8374630f40a7d,true] 7708 --- [    elastic-111] mk.MicroserviceController                : ->->->->getEmail threadName elastic-111

```	

Can you tell me what it is and how I can solve it?

It works with netty but with tomcat it doesn't.
I mean when I switch to netty there are no error messages.

**Comment by marcin-kasinski** [comment]
Additional info:
This problem exists with embeded tomcat only.

After removing spring-boot-starter-web dependency  ( embeded netty) there are no error messages in logs.

**Comment by bclozel** [comment]
It looks like something is trying to access request/response headers after the exchange has been handled by the application. Could you check if this happens still after removing spring-cloud-sleuth from the picture?

Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
