### ISSUE TITLE
NoSuchMethodError when invoking RedisOperationsSessionRepository.delete

### ISSUE THREAD

**Issue by asha-chandran** [spring-projects/spring-framework#22538]
I'm using spring session and spring data redis for session management. I haven't used Spring boot.

Used are as follows,

- spring-session: 1.3.5.RELEASE
- spring-data-redis: 2.1.4.RELEASE
- spring-webmvc: 5.0.4.RELEASE
- lettuce-core: 5.1.4.RELEASE

Included these beans for redis configuration: 
`org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration`, `org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory`.

Included filter `springSessionRepositoryFilter` in `web.xml`.

But I got following error frequently.

```
ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NoSuchMethodError: org.springframework.data.redis.core.RedisOperations.delete(Ljava/lang/Object;)V
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:132) ~[spring-session-1.3.5.RELEASE.jar:?]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:398) ~[spring-session-1.3.5.RELEASE.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

Can you please help to solve this?

**Comment by sbrannen** [comment]
This sounds like a version conflict for various JARs in the classpath.

@mp911de, can you provide further insight here? Is this an issue with Lettuce?

**Comment by mp911de** [comment]
Looks like a version incompatibility between Spring Session and Spring Data Redis. Spring Session should be the right place for this issue.

**Comment by vpavic** [comment]
The issue here are indeed incompatible dependency versions - Spring Session 1.3 is aligned with Spring Data Ingalls (i.e. Spring Data Redis 1.8).

@asha-chandran You'll need to upgrade Spring Session to 2.1 to match your Spring Data Redis version. At that point, you might also want to bump Spring Framework to 5.1. Probably the safest way to keep your Spring dependencies aligned is to use Spring Boot's BOM (`org.springframework.boot:spring-boot-dependencies`) even if you are not using Spring Boot itself.

**Comment by sbrannen** [comment]
@mp911de and @vpavic, thanks for the input!

I unfortunately cannot transfer this to the `spring-session` since I'm not an admin for that repo. @rwinch, can you transfer it?

**Comment by asha-chandran** [comment]
> The issue here are indeed incompatible dependency versions - Spring Session 1.3 is aligned with Spring Data Ingalls (i.e. Spring Data Redis 1.8).
> 
> @asha-chandran You'll need to upgrade Spring Session to 2.1 to match your Spring Data Redis version. At that point, you might also want to bump Spring Framework to 5.1. Probably the safest way to keep your Spring dependencies aligned is to use Spring Boot's BOM (`org.springframework.boot:spring-boot-dependencies`) even if you are not using Spring Boot itself.

I can't see Spring Session to 2.1  in Maven repository. Latest I could seen is 1.3.5.RELEASE. If I can use Spring Data Redis 1.8 then which is correct version ? Is it Spring Data Redis 1.8.18.RELEASE ?

**Comment by vpavic** [comment]
I'd suggest to take a look at [_Upgrading to 2.x_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#upgrading-2.0) of Spring Session reference manual.

**Comment by asha-chandran** [comment]
I need to use HttpSessionManager sessionManager =(HttpSessionManager) request.getAttribute(HttpSessionManager.class.getName()); String alias = sessionManager.getNewSessionAlias(request);

So  spring-session 1.3.5 jar(latest in maven central) is needed. For all other dependencies gives error. Please give me solution  for **NoSuchMethodError when invoking RedisOperationsSessionRepository.delete**

**Comment by asha-chandran** [comment]
> I'd suggest to take a look at [_Upgrading to 2.x_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#upgrading-2.0) of Spring Session reference manual.

I'm not planning to upgrade to Spring session 2.1 unless I have another option to solve this issue. I have spring -session 1.3.5 which is the latest I can get from MavenRepository (Central).

**Comment by sbrannen** [comment]
I am closing this issue since it is related Spring Session. Feel free to open a new issue there or request from @rwinch that this issue be transferred to Spring Session's issue tracker.
