### ISSUE TITLE
Using MockMvc to test Flux<ServerSentEvent> endpoints?

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-framework#22544]
I'm strugling with writing tests for rest endpoints that return Flux<ServerSentEvent>. I'd like to use mockMvc for this. Is this even possible? 

Note that, allthough I have some rest endpoints returning Flux and/or Mono I am *not* using WebFllux but just regular MVC. The framework handles those types fine and for my Flux<ServerSentEvent> example, these are received on the browser side as a 'stream' of ServerSentEvents. This all works fine.

The trouble is. I can't seem to find a good way to write tests agains these endpoints using mockmvc. 

The best I came up with is here:

https://github.com/kdvolder/mvc-flux-testing/blob/master/src/test/java/com/example/demo/MvcFluxDemoApplicationTests.java

Is turning the stream of events into String via `getResponse().getContentAsString()' really the best I can do here? (Note: @rstoyanchev has told me it is, mockMvc doesn't provide good ways to test this sort of thing. He recommends to use WebTestClient).

So I submit for consideration the following:

1. It may be useful to expand mockMvc apis to handle endpoints returning streamed ServerSentEvents better. Perhaps, something that can get the content as a Flux? Then we can use reactive testing support such as StepVerifier to validate the content in our tests.

2. Add a pointer in the docs on using WebTestClient instead for these scenarios.

**Comment by kdvolder** [comment]
Note: I don't seem to be the only one strugling with this. See: https://stackoverflow.com/questions/35499655/how-to-test-server-sent-events-with-spring

There are two answers there, neither of which seem very satisfactory.

**Comment by rstoyanchev** [comment]
Thanks Kris. Indeed `WebTestClient` is the best answer we have for this. Building something (async, streaming parsing) in MockMvc would be non-trivial. We certainly can and need to explain the available options in the documentation however.

**Comment by daliborfilus** [comment]
How can we use WebTestClient with Spring Boot MVC (starter-web)?
It throws unsatisfied dependency on me. WebTestClient is in reactive namespaced package.
So we cannot use it for regular MVC?
(I tried @AutoConfigureWebTestClient, but that didn't help; even the doc for that annotations says it's only for WebFlux.)

So if WebTestClient is for WebFlux only, and MockMvc is for MVC only, and we want to test Flux/Mono responses, what should we do? I'm trying to find an answer to this for multiple hours at this point... and each of such answers is contradictory or confusing or incorrect, because things have changed.

**Comment by rstoyanchev** [comment]
@daliborfilus, indeed `WebTestClient` uses `WebClient` from spring-webflux internally but this is a fully expected supported scenario in Spring Boot, just like it is fully supported to use the `WebClient` in a Spring Boot application with WebMvc. These are [the rules](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-web-environment) Boot uses to determine the web environment.

In addition in 5.3 we updated `WebTestClient` to support both WebFlux and WebMvc controllers so it can be used for both. You might want to review the updated reference in the [WebTestClient](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#webtestclient) and the [MockMvc](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-mvc-test-framework) sections.

That said, for testing SSE and streaming responses, full end-to-end tests through the `WebTestClient` along with the `StepVerifier` from Project Reactor is your best bet.

**Comment by daliborfilus** [comment]
@rstoyanchev Thank you. Seem like I tried to use WebTestClient as autowired component, which doesn't work in this case?
(I'm using Spring Boot 2.4.3, which uses Spring Web 5.3.4.)

The WebTestClient link you mention links to sample project https://github.com/spring-projects/spring-framework/tree/master/spring-test/src/test/java/org/springframework/test/web/client/samples which doesn't use WebTestClient, at least not directly? One of the tests mocks the server side completely, which I don't want - I just want to mock the servlet part and still do end-to-end integration test. (Or even expose random port and test it using rest template - which is maybe what this sample project does? But that's another topic.)

The part [3.6.1 - Setup](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#webtestclient-context-config) explains how to create instance of WebTestClient - or more precisely MockMvcWebTestClient - bound to a controller or the application context. I don't want to instantiate the controller here, because then I would need to pass all autowired dependencies to it, so the ApplicationContext is preferrable I think.

So following this, I now have this code:

```kotlin
@ActiveProfiles("test")
// tried with RANDOM_PORT and MOCK
@SpringBootTest(classes = [BackendApplication::class], webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc(printOnlyOnFailure = false)
@AutoConfigureRestDocs(outputDir = "build/generated-snippets")
internal class PhysterMonitoringControllerTest {

    @Autowired
    lateinit var context: WebApplicationContext

    lateinit var client: WebTestClient

    @BeforeEach
    fun setUp() {
        client = WebTestClient.bindToApplicationContext(context).build()
    }

    @Test
    fun indexAcceptJsonAndDocument() {
        client.get().uri("$contextPath/entities/export")
//                .with(SecurityMockMvcRequestPostProcessors.user("user").authorities(allAuthorities())) // FIXME: find replacement for this
            .accept(MediaType.APPLICATION_JSON)
            .exchange()
            .expectStatus().isOk
            .expectBody()
            .jsonPath("$.totalElements").isEqualTo(3)
            .jsonPath("$.totalPages").isEqualTo(1)
//            .andDo(MockMvcRestDocumentation.document("monitored-entities-export")) // FIXME: find replacement for this to get restdocs working; use consumeWith?
    }
}
```

which throws and I don't know why:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'webHandler' available

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:863)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1159)
	at org.springframework.web.server.adapter.WebHttpHandlerBuilder.applicationContext(WebHttpHandlerBuilder.java:165)
	at org.springframework.test.web.reactive.server.ApplicationContextSpec.initHttpHandlerBuilder(ApplicationContextSpec.java:43)
	at org.springframework.test.web.reactive.server.AbstractMockServerSpec.configureClient(AbstractMockServerSpec.java:86)
	at org.springframework.test.web.reactive.server.AbstractMockServerSpec.build(AbstractMockServerSpec.java:107)
	at app.web.data.monitoring.MonitoringControllerTest.setUp(MonitoringControllerTest.kt:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:490)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$19(ClassBasedTestDescriptor.java:475)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:164)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
```

**Comment by daliborfilus** [comment]
@rstoyanchev Uh. I tried to at least solve the todos in the comments above (mock user, apply rest docs) and I found out that I cannot use `.apply(springSecurity())` in the test because of #20606 - kotlin cannot infer the type T.
I would like to supply the the type to the apply method, but I cannot, because the type is package-private - and I can see you are the author of that class (spring-test-5.3.4-sources.jar!/org/springframework/test/web/reactive/server/ApplicationContextSpec.java).

So even if I could get that "webHandler" dependency error go away, I still cannot use the WebTestClient in Kotlin.

**Comment by rstoyanchev** [comment]
As you already found out, you need to use `MockMvcWebTestClient`. That has a method to bind to an `ApplicationContext` as well so change to the following:
```java
MockMvcWebTestClient.bindToApplicationContext(this.wac).build();
```

As for #20606 yes that is an issue. I believe there is some effort to resolve it but I don't have the details.

**Comment by daliborfilus** [comment]
@rstoyanchev Thank you, I will stick to MVC + MockMvc for now and we'll see in the future.

**Comment by rstoyanchev** [comment]
No problem. For streaming and Server-Sent Events, you'll need the `WebTestClient` which can also do full end-to-end integration tests but apart from that you can also stick to MockMvc.
