### ISSUE TITLE
spring-bean:5.1.3 compatibility with spring-webmvc-portlet:4.3.18 and Liferay 7.1

### ISSUE THREAD

**Issue by djacn** [spring-projects/spring-framework#22608]
**Affects:** 5.1.3
I am encountering a weird issue with spring bean, trying to work with the libraries in the title.
I am trying to migrate from spring 4.1.9 to 5.1.3 so this error is not in version 4.1.9

**Stacktrace:**
```
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line xx in XML document from PortletContext resource [/WEB-INF/context/xxx.xml] is invalid;
nested exception is org.xml.sax.SAXParseException; lineNumber: xx; columnNumber: xxx; cvc-complex-type.2.4.c: The matching wildcard is
strict, but no declaration can be found for element 'context:component-scan'.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
        at org.springframework.web.portlet.context.XmlPortletApplicationContext.loadBeanDefinitions(XmlPortletApplicationContext.java:125)
        at org.springframework.web.portlet.context.XmlPortletApplicationContext.loadBeanDefinitions(XmlPortletApplicationContext.java:93)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:541)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:452)
        at org.springframework.web.portlet.FrameworkPortlet.createPortletApplicationContext(FrameworkPortlet.java:368)
        at org.springframework.web.portlet.FrameworkPortlet.initPortletApplicationContext(FrameworkPortlet.java:297)
        at org.springframework.web.portlet.FrameworkPortlet.initPortletBean(FrameworkPortlet.java:271)
        at org.springframework.web.portlet.GenericPortletBean.init(GenericPortletBean.java:124)
        at javax.portlet.GenericPortlet.init(GenericPortlet.java:143)
        at com.liferay.portlet.internal.InvokerPortletImpl.init(InvokerPortletImpl.java:248)
        at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.init(MonitoringInvokerPortlet.java:154)
        at com.liferay.portlet.internal.PortletInstanceFactoryImpl.init(PortletInstanceFactoryImpl.java:269)
        at com.liferay.portlet.internal.PortletInstanceFactoryImpl.create(PortletInstanceFactoryImpl.java:170)
        at com.liferay.portlet.internal.PortletInstanceFactoryImpl.create(PortletInstanceFactoryImpl.java:114)
        at com.liferay.portal.kernel.portlet.PortletInstanceFactoryUtil.create(PortletInstanceFactoryUtil.java:40)
        at com.liferay.portal.deploy.hot.PortletHotDeployListener.initPortletApp(PortletHotDeployListener.java:453)
        at com.liferay.portal.deploy.hot.PortletHotDeployListener.doInvokeDeploy(PortletHotDeployListener.java:225)
        at com.liferay.portal.deploy.hot.PortletHotDeployListener.invokeDeploy(PortletHotDeployListener.java:92)
        ... 13 more
```

**xxx.xml**:
```
<?xml version="1.0"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:mvc="http://www.springframework.org/schema/mvc"
       xmlns:sws="http://www.springframework.org/schema/web-services"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
						http://www.springframework.org/schema/beans/spring-beans.xsd
						http://www.springframework.org/schema/context
						http://www.springframework.org/schema/context/spring-context.xsd
						 http://www.springframework.org/schema/tx
						 http://www.springframework.org/schema/tx/spring-tx.xsd
						 http://www.springframework.org/schema/mvc
						 http://www.springframework.org/schema/mvc/spring-mvc.xsd
						 http://www.springframework.org/schema/aop
						 http://www.springframework.org/schema/aop/spring-aop.xsd">

    <import resource="root-context.xml"/>
    <context:component-scan base-package="com.x.xx.xxx, com.y.yy.yyy.yyyy, com.z.zz.zzz.zzzz, com.a.aa.aaa, com.b.bb.bbb" />
    <bean id="viewResolver"
          class="org.springframework.web.servlet.view.InternalResourceViewResolver">
        <property name="viewClass" value="org.springframework.web.servlet.view.JstlView" />
        <property name="prefix" value="/WEB-INF/jsp/xxx/" />
        <property name="suffix" value=".jsp" />
    </bean>

    <bean id="XController" class="com.c.cc.ccc.controller.XController"/>

    <bean id="portletModeHandlerMapping"
          class="org.springframework.web.portlet.handler.PortletModeHandlerMapping">
        <property name="portletModeMap">
            <map>
                <entry key="view" value-ref="XController"></entry>
            </map>
        </property>
    </bean>

    <bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean">
        <property name="jndiName" value="java:/jdbc/PortalDataSource"/>
    </bean>
    <bean id="jdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">
        <property name="dataSource" ref="dataSource" />
    </bean>
</beans>

```
---

**Comment by rstoyanchev** [comment]
Is this a Portlet application? Spring Framework 5 [dropped support](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#dropped-support) for Portlets.

**Comment by djacn** [comment]
Yes, this is a portlet application. and thanks for the response!~
