### ISSUE TITLE
Quartz - an exception if ZeroSizeThreadPool is used as a ThreadPool

### ISSUE THREAD

**Issue by realmfoo** [spring-projects/spring-framework#22650]
For management only I need to use `org.quartz.simpl.ZeroSizeThreadPool` as a `ThreadPool`. Unfortunately `SchedulerFactoryBean` puts property `org.quartz.threadPool.threadCount` without respect to specified `org.quartz.threadPool.class` property.

It ends up with an exception `java.lang.NoSuchMethodException: No setter for property 'threadCount'`.

Indeed it should not add a default pool size if I specify property `org.quartz.threadPool.class` by my own.

**Comment by snicoll** [comment]
@realmfoo can you please provide the full stacktrace of this exception?

**Comment by realmfoo** [comment]
```
Caused by: org.quartz.SchedulerException: ThreadPool class 'org.quartz.simpl.ZeroSizeThreadPool' props could not be configured. [See nested exception: java.lang.NoSuchMethodException: No setter for property 'threadCount']
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:849)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:676)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.prepareScheduler(SchedulerFactoryBean.java:613)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:501)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
	... 91 more
Caused by: java.lang.NoSuchMethodException: No setter for property 'threadCount'
	at org.quartz.impl.StdSchedulerFactory.setBeanProps(StdSchedulerFactory.java:1447)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:847)
	... 97 more
```

**Comment by snicoll** [comment]
Thank for the feedback. As I suspected, Quartz is attempting to call that property on the thread pool instance. I disagree that we should not configure the thread count property as there is no way for us to know whether or not the thread pool instance supports it.

You may want to report your use case against the Quartz project to see if they would consider being more lenient about it.

Alternatively you can provide your own `Executor`.

**Comment by realmfoo** [comment]
@snicoll Quartz uses that properties to create a thread pool and it fails to set unknown properties. Indeed it should fail because you could misspell property name.

`SchedulerFactoryBean` knows only two thread pools: `LocalTaskExecutorThreadPool` and `SimpleThreadPool`. And it adds an extra property only when `taskExecuter` is not defined. So it first defines default values and then merges specified `quartzProperties`.

I suggest to merge first and then setup default thread pool if necessary. This will allow to set the pool class and it's properties without errors.
