### ISSUE TITLE
PrematureCloseException: Connection prematurely closed BEFORE  when running UnitTests

### ISSUE THREAD

**Issue by xDouglasx** [spring-projects/spring-framework#22774]
Using Spring Boot 2.1.3-RELEASE and 0.8.6.RELEASE of reactor-netty i'm using webClient and using StepVerifier for testing.
All the tests are ok, but when im using DynamicTest it returns the exception.

```
public Mono<Optional<JsonNode>> getObject(String name) {
    return webClient.get().uri(buildUri(name))
        .exchange()
        .flatMap(clientResponse -> `handleClientResponse(clientResponse));

```

```
private Mono<Optional<JsonNode>> handleClientResponse(ClientResponse clientResponse, String name) {
    if (clientResponse.statusCode().isError()) {
      if (clientResponse.statusCode().equals(HttpStatus.NOT_FOUND)) {
        return Mono.just(Optional.empty());
      } else {
        throw new BadGatewayException(
            format("Unable to retrieve external object with name: '{%s}'",
                name));
      }
    }
    return clientResponse.bodyToMono(new ParameterizedTypeReference<Response<JsonNode>>() {
    })
        .map(r -> Optional.ofNullable(r.getData().getItem()));
  }
```

Test

```
@TestFactory
    @DisplayName("Get Object With Random HTTP Responses")
    public Collection<DynamicTest> getObjectWithInvalidHttpResponseTest() {

      return Stream.of(RANDOM_DATA_THEN_CLOSE, CONNECTION_RESET_BY_PEER, EMPTY_RESPONSE, MALFORMED_RESPONSE_CHUNK)
          .map(fault -> DynamicTest.dynamicTest(fault.toString(), () -> {
            stubFor(get(urlEqualTo(OBJECT_URL))
                .willReturn(aResponse()
                    .withFault(fault)
                    .withStatus(HttpStatus.OK.value())));

            StepVerifier.create(objectGateway.getObject(OBJECT_NAME))
                .expectErrorMatches(throwable -> throwable instanceof BadGatewayException &&
                    throwable.getMessage()
                        .equals("Unexpected response retrieving Object with name [xxxxx]")
                ).verify();

          })).collect(Collectors.toList());
  }
```
Stack tracer

```
2019-04-09 10:46:51.121  WARN   --- [ctor-http-nio-4] r.netty.http.client.HttpClientConnect    : [id: 0xeea96051, L:0.0.0.0/0.0.0.0:63355] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response


java.lang.AssertionError: expectation "expectErrorMatches" failed (predicate failed on exception: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response)

	at reactor.test.ErrorFormatter.assertionError(ErrorFormatter.java:105)
	at reactor.test.ErrorFormatter.failPrefix(ErrorFormatter.java:94)
	at reactor.test.ErrorFormatter.fail(ErrorFormatter.java:64)
	at reactor.test.ErrorFormatter.failOptional(ErrorFormatter.java:79)
	at reactor.test.DefaultStepVerifierBuilder.lambda$expectErrorMatches$8(DefaultStepVerifierBuilder.java:399)
	at reactor.test.DefaultStepVerifierBuilder$SignalEvent.test(DefaultStepVerifierBuilder.java:2112)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSignal(DefaultStepVerifierBuilder.java:1408)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1356)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onError(DefaultStepVerifierBuilder.java:1030)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:1747)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.onError(TraceWebClientBeanPostProcessor.java:276)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:193)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:100)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:105)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:167)
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onUncaughtException(HttpClientConnect.java:404)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onUncaughtException(ReactorNetty.java:351)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onUncaughtException(PooledConnectionProvider.java:503)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onUncaughtException(PooledConnectionProvider.java:412)
	at reactor.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:254)
	at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:121)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:206)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

Thanks in advance!
---

**Comment by xDouglasx** [comment]
I noticed that i wasn't handling the errors from webClient and the prematureConnectionException is expected since i'm using faults, the way i fixed it was adding doOnError.

```
public Mono<Optional<JsonNode>> getObject(final String name) {
    return webClient.get().uri(buildUri(name))
        .exchange()
        .flatMap(clientResponse -> handleClientResponse(clientResponse, name))
        .doOnError(err -> onError(err, name));
  }
```

I was handling only the HTTPErrors with doOnError i handle the Exceptions.
but i have one question, there is a better way or a correct way to handle the HttpErrors and the Exceptions with webClient?
