### ISSUE TITLE
Accept header with trailing comma produces HTTP "406 Not Acceptable"

### ISSUE THREAD

**Issue by j3r0lin** [spring-projects/spring-framework#23241]
Spring version: 5.1.8.RELEASE

Send a http request with header like this, containing `, ` at the end.

```http
Accept: application/json, 
```

`HeaderContentNegotiationStrategy` will produce a `HttpMediaTypeNotAcceptableException`.

```
org.springframework.web.HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header [application/json,]: Invalid mime type "": 'mimeType' must not be empty
	at org.springframework.web.accept.HeaderContentNegotiationStrategy.resolveMediaTypes(HeaderContentNegotiationStrategy.java:59) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.accept.ContentNegotiationManager.resolveMediaTypes(ContentNegotiationManager.java:124) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.getAcceptableMediaTypes(AbstractMessageConverterMethodProcessor.java:391) ~[spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:229) ~[spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:225) ~[spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
```

That http request works before 5.1.2.RELEASE.

Maybe the cause of this is the parsing method refactoring in this commit [f4b05dc](https://github.com/spring-projects/spring-framework/commit/f4b05dc2e730ca667daf8861c6eb2d9a6b83d534#diff-47ef64129825b0e047375d409c7d95a9L260).

`StringUtils.tokenizeToStringArray(mimeTypes, ",")` will trim tokens and ignore empty tokens by default, but now, the replacement method not support that anymore.

**Comment by sbrannen** [comment]
> Send a http request with header like this, containing `, ` at the end.

What is your use case for that?

What client is sending the Accept request header with a trailing comma?

**Comment by j3r0lin** [comment]
I'm using an http client named Paw, it sends that request from it's build in oauth2 client.
Although it seems to be an invalid header, but it dose works before.

**Comment by sbrannen** [comment]
Thanks for the feedback. I've labeled this as a _regression_.

**Comment by sbrannen** [comment]
The following test passes against the `v5.1.2.RELEASE` tag and fails on the current `5.1.x` branch.

```java
	@Test
	public void parseMimeTypesWithTrailingComma() {
		List<MediaType> mediaTypes = MediaType.parseMediaTypes("text/plain, text/html, ");
		assertNotNull("No media types returned", mediaTypes);
		assertEquals("Incorrect number of media types", 2, mediaTypes.size());
	}
```
