### ISSUE TITLE
Calling uri of the form /-system is causing an exception in jvm-11

### ISSUE THREAD

**Issue by GrigoreStancul** [spring-projects/spring-framework#23270]
**Affects:** spring-test 5.1.5.RELEASE

Calling in the test uri of the form /-system is causing an exception in jvm-11
Example:
`        MvcResult mvcResult = mvc.perform(get("/-system/check")
                .accept(MediaType.TEXT_PLAIN_VALUE))
                .andExpect(status().isOk())
                .andReturn();
`

Stacktrace:
`org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
        at cs.SystemCheckIT.shouldGetSystemCheck(SystemCheckIT.java:37)
Caused by: java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
        at cs.SystemCheckIT.shouldGetSystemCheck(SystemCheckIT.java:37)
Caused by: java.lang.ClassNotFoundException: sun.misc.SharedSecrets
        at cs.SystemCheckIT.shouldGetSystemCheck(SystemCheckIT.java:37)
`

**Comment by GrigoreStancul** [comment]
The problem was in the test itself
