### ISSUE TITLE
Mockito cannot mock @Async method

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#23324]
When trying to mock an `@Async` method I get the following error:

```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced or misused argument matcher detected here:

-> at package.TestClass.init_aroundBody0(File.java:79)
-> at package.TestClass.init_aroundBody0(File.java:79)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

This message may appear after an NullPointerException if the last matcher is returning an object 
like any() but the stubbed method signature expect a primitive argument, in this case,
use primitive alternatives.
    when(mock.get(any())); // bad use, will raise NPE
    when(mock.get(anyInt())); // correct usage use

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.
```

This error only appears when I run the test without debugger attached. When I try to debug, the error doesn't show up, and everything works fine.
When I remove the `@Async`, then it works also without the debugger attached.

This error started showing up after I upgraded from spring 4 to spring 5.
Using **spring-boot-starter-test 2.1.6.RELEASE** (mockito-core:2.23.4, spring-test:5.1.8.RELEASE)

**Comment by sbrannen** [comment]
Due to the involvement of `@SpyBean`, it sounds to me like it might be an issue in Spring Boot Test.

@philwebb and @wilkinsona, have you come across something like this before?

**Comment by philwebb** [comment]
We've seen a few issue like this in the past related to AOP. I'll transfer the issue.
