### ISSUE TITLE
NullPointerException in JpaMetamodel with Hibernate dynamic-component

### ISSUE THREAD

**Issue by xpoinsard** [spring-projects/spring-framework#23392]
**Affects:**  spring-data Ingalls-SR22

---

With Hibernate 5.3.10, I am using an .hbm.xml mapping which contains :
`<dynamic-component name="additionalAttributes"/> `
see https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html_single/#components-dynamic for more info or https://github.com/hibernate/hibernate-orm/blob/164178330a92ce1b064b44306c5d9408e86cefdf/hibernate-core/src/test/java/org/hibernate/test/legacy/Glarch.hbm.xml#L27 for an example

I tried to create the jpa repositories with 
`<jpa:repositories base-package="com.acme.repositories" />`
and got :

> 2019-07-31 16:09:15,317 ERROR [o.s.w.c.ContextLoader] localhost-startStop-1 Context initialization failed
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is java.lang.NullPointerException
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:737)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
> 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
> 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
> 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
> 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4743)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException: null
> 	at org.springframework.data.mapping.model.AbstractPersistentProperty.getActualType(AbstractPersistentProperty.java:318)
> 	at org.springframework.data.jpa.mapping.JpaPersistentPropertyImpl.getActualType(JpaPersistentPropertyImpl.java:152)
> 	at org.springframework.data.jpa.mapping.JpaPersistentPropertyImpl.isEntity(JpaPersistentPropertyImpl.java:201)
> 	at org.springframework.data.mapping.model.AbstractPersistentProperty.getPersistentEntityType(AbstractPersistentProperty.java:130)
> 	at org.springframework.data.jpa.mapping.JpaPersistentPropertyImpl.getPersistentEntityType(JpaPersistentPropertyImpl.java:161)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:525)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:483)
> 	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:693)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:347)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:526)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:483)
> 	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:693)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:347)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:526)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:483)
> 	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:693)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:347)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:526)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:483)
> 	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:693)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:347)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:526)
> 	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:483)
> 	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:693)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:347)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:299)
> 	at org.springframework.data.mapping.context.AbstractMappingContext.initialize(AbstractMappingContext.java:429)
> 	at org.springframework.data.jpa.repository.config.JpaMetamodelMappingContextFactoryBean.createInstance(JpaMetamodelMappingContextFactoryBean.java:73)
> 	at org.springframework.data.jpa.repository.config.JpaMetamodelMappingContextFactoryBean.createInstance(JpaMetamodelMappingContextFactoryBean.java:26)
> 	at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:135)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
> 	... 21 common frames omitted

And this exception occurs while trying to analyse the dynamic-component properties.

**Comment by snicoll** [comment]
Sorry this got overlooked. 

The NPE happens in Spring Data JPA so this shouldn't be reported here. If you manage to reproduce with a supported version, please create an issue in the [Spring Data JPA issue tracker](https://github.com/spring-projects/spring-data-jpa/) with a small sample that the team can use to reproduce the issue.
