### ISSUE TITLE
ConcurrentModificationException during setHeader for MockHTTPServletResponse during setRedirection

### ISSUE THREAD

**Issue by Hello629** [spring-projects/spring-framework#23426]
[TestSpringProject.zip](https://github.com/spring-projects/spring-framework/files/3475181/TestSpringProject.zip)

**Affects:** 5.1.7.RELEASE

---

Hi

We are getting a concurrent modification exception sometimes when our tests run in Jenkins. I have attached a test project to reproduce the issue. I could see there are changes in master for HeaderValueHolder class but do we have any plan for backporting those changes?  To run the attached project just run TestControllerTest test. It might take a minute or two to get the exception.

Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at org.springframework.mock.web.HeaderValueHolder.getByName(HeaderValueHolder.java:98)
	at org.springframework.mock.web.MockHttpServletResponse.containsHeader(MockHttpServletResponse.java:383)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	... 32 more

Thanks

**Comment by rstoyanchev** [comment]
Looks like this was already addressed in #23460.
