### ISSUE TITLE
Should spring-test upgrade hamcrest to 2.x ?

### ISSUE THREAD

**Issue by wamaco** [spring-projects/spring-framework#23467]
Now the version of hamcrest which spring depends is 1.3, some new features in hamcrest 2.x cannot be applied in our self project, such as `matchesPattern`. If we upgrade it in our pom, then spring-test cannot find some  methods.

```
java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.springframework.test.web.client.match.MockRestRequestMatchers$2.match(MockRestRequestMatchers.java:72)
	at org.springframework.test.web.client.RequestMatcherClientHttpRequest.executeInternal(RequestMatcherClientHttpRequest.java:75)
	at org.springframework.mock.http.client.MockClientHttpRequest.execute(MockClientHttpRequest.java:93)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:591)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:552)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:259)
	at com.cisco.edsartapi.v3.client.RequestClient.getLastApprover(RequestClient.java:54)
	at com.cisco.edsartapi.v3.client.RequestClientTest.testGetLastApprover_Success(RequestClientTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by sbrannen** [comment]
I just upgraded my `spring-events` sample application to Hamcrest 2.1 (https://github.com/sbrannen/spring-events/commit/f18ae04aea6f718adb5b6bc88bd3c5237f292ebd), and I didn't run into any issues.

Thus, it appears to me that you potentially have conflicting versions of Hamcrest in the classpath. For example, you may have different versions of `hamcrest-core` and `hamcrest-all` in the classpath.

In light of that, I am closing this issue.

However, if you find that you still run into an issue after ensuring that you have consistent versions of Hamcrest JARs in the classpath, please post back here with further details.

Thanks!

**Comment by sbrannen** [comment]
Having said that, since there appears to be no conflict in upgrading to Hamcrest 2.1, I have gone ahead and done that in 303fc3211c1eba3ea434fcf4fab64e72e723f99f for Spring Framework 5.2.

Thanks for raising the issue!

**Comment by unxia** [comment]
Sorry for no timely reply. I have tested your spring-events, and also create a sample myself, there is no any issues.  
The project I am refactoring is very confusing, now I'm checking it in detail.
Thank you very much!

**Comment by sbrannen** [comment]
No problem.

You're welcome.

and...

Thanks for the feedback.
