### ISSUE TITLE
Raise 400 instead of 500 on failure to find  index of lookupPath within requestUri in ResourceUrlEncodingFilter

### ISSUE THREAD

**Issue by mixcloud-downloader** [spring-projects/spring-framework#23508]
**Affects:** 5.1.9

```
java.lang.IllegalStateException: Failed to find lookupPath '/d/mixcloud/logo.png' within requestUri '/d/mixcloud/superbmixes/../logo.png'. Does the path have invalid encoded characters for characterEncoding 'UTF-8'?
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter$ResourceUrlEncodingRequestWrapper.initLookupPath(ResourceUrlEncodingFilter.java:102)
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter$ResourceUrlEncodingRequestWrapper.setAttribute(ResourceUrlEncodingFilter.java:86)
	at org.springframework.web.servlet.resource.ResourceUrlProviderExposingInterceptor.preHandle(ResourceUrlProviderExposingInterceptor.java:51)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:136)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1034)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.doHead(HttpServlet.java:245)
```

If that URI is unexpected, I think that request should result in a 400 rather than the 500 from the IllegalStateException.

**Comment by rstoyanchev** [comment]
That would also apply to the original scenario #22851.

**Comment by mentallurg** [comment]
Regarding _a 400 rather than the 500_: You are right that `IllegalStateException` and code 400 are not compatible. If a client requested something that server cannot find, then it is a client error and that's why 400 is correct. But throwing the `IllegalStateException` in such case is not correct, other exception should be used instead.

**Comment by rstoyanchev** [comment]
@mentallurg I'm not very clear what you mean. As far as I can see your point is the same i.e. that the 500/IllegalStateException should be replaced with something else that results in 400.
