### ISSUE TITLE
PathPatternParserTests#regexPathElementPatterns() fails on Java 13

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-framework#23669]
Stacktrace:

```
org.opentest4j.AssertionFailedError: [/{var:a{{1,2}}}
        ^
Exception occurred in regex pattern compilation] 
Expecting:
 <8>
to be equal to:
 <6>
but was not.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at org.springframework.web.util.pattern.PathPatternParserTests.lambda$checkError$3(PathPatternParserTests.java:441)
	at org.springframework.web.util.pattern.PathPatternParserTests.checkError(PathPatternParserTests.java:440)
	at org.springframework.web.util.pattern.PathPatternParserTests.regexPathElementPatterns(PathPatternParserTests.java:121)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
```

**Comment by sbrannen** [comment]
After some internal brainstorming...

Proposal: create an overloaded variant of `checkError()` for the `/{var:a{{1,2}}}` pattern that does not check the `expectedPos`, but leave the remaining usage of `checkError()` as-is.

Rationale: if a `java.util.regex.PatternSyntaxException` is thrown, we cannot influence the "error index" reported in that exception. Thus, we should not assert a specific "expected position" in the `org.springframework.web.util.pattern.PatternParseException` thrown by SpEL code for such cases.
