### ISSUE TITLE
ClassUtils.isAssignable() returns false for the "same" types loaded from different ClassLoaders

### ISSUE THREAD

**Issue by yiding-he** [spring-projects/spring-framework#23765]
I'm having a strange issue while using Spring Boot Auto Configuration and `@Autowired` is not working. Through debugging process I found this:

![批注 2019-10-07 164404](https://user-images.githubusercontent.com/900606/66297495-5a9e6280-e922-11e9-829e-efb84a39ddaa.png)

The 2 arguments of method `isAssignable()` refers to the same class, but not the same Class instance because `lhsType` is loaded by `RestartClassLoader` and `rhsType` is loaded by `Launcher$AppClassLoader`. 

As a result, `lhsType.isAssignableFrom(rhsType)` returns `false`, which makes Spring unable to locate the factory method to create this bean:

```
2019-10-07 17:05:30.598 DEBUG 944 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.hyd.dao.DataSources' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1662) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1221) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
```

I have no idea why the 2 arguments are from different class loaders, and I don't know how to solve this problem.

---

Affects: 5.1.10-RELEASE

**Comment by quaff** [comment]
同一个类由不同的类加载器加载那就是两个不同的类，isAssignable返回false是没错的，所以问题是为什么会有两个类加载器，从名字看应该是用了Spring Developer Tools开启了热加载导致的，可以去掉试试。

**Comment by snicoll** [comment]
Sorry, but we can't help either based on a screenshot. `ClassUtils` is doing the right thing here as the classes are loaded from two different classloaders.

**Comment by bld-commons** [comment]
same problem, I solved it by deleting spring-boot-devtools, as @quaff  says
The problem was only when starting from eclipse
