### ISSUE TITLE
Cache bean does not inject in a bean which created using FactoryBean. 

### ISSUE THREAD

**Issue by DmitryevichD** [spring-projects/spring-framework#23817]
Redis cache bean does not inject in a bean which created using FactoryBean. 
But another cache which created does not via FactoryBean is success.

Example: https://github.com/DmitryevichD/BugWithBeanFactoryCache

**Comment by snicoll** [comment]
Thanks for the sample, this is very useful. If you inspect the logs, you'll see the following:

```
2019-10-16 14:41:26.790  INFO 17277 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'incorrectCache' of type [by.dm13y.spring.example.beanfactorycache.cache.IncorrectCache] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-16 14:41:26.791  INFO 17277 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'cacheServiceImpl' of type [by.dm13y.spring.example.beanfactorycache.services.impl.CacheServiceImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-10-16 14:41:26.791  INFO 17277 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'cacheChecker' of type [by.dm13y.spring.example.beanfactorycache.services.CacheChecker] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

Adding `CacheChecker` as a constructor argument of your factory bean forces early initialization of the whole chain and before the cache infrastructure has a chance to initialize. Having said that, I don't understand what that sample is supposed to show.

If I start this app, it fails with:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customBeanFactory' defined in file [/Users/snicoll/Downloads/BugWithBeanFactoryCache-master/build/classes/java/main/by/dm13y/spring/example/beanfactorycache/factory/CustomBeanFactory.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:828) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at by.dm13y.spring.example.beanfactorycache.BeanFactoryCacheApplication.main(BeanFactoryCacheApplication.java:12) [main/:na]
Caused by: java.lang.NullPointerException: null
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_202]
	at by.dm13y.spring.example.beanfactorycache.services.CacheChecker.check(CacheChecker.java:19) ~[main/:na]
	at by.dm13y.spring.example.beanfactorycache.factory.CustomBeanFactory.createInstance(CustomBeanFactory.java:21) ~[main/:na]
	at by.dm13y.spring.example.beanfactorycache.factory.CustomBeanFactory.createInstance(CustomBeanFactory.java:9) ~[main/:na]
	at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:142) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	... 15 common frames omitted
```

`CacheService` has a single implementation that takes the `IncorrectCache` that always return `null`. What are you trying to demonstrate?

**Comment by DmitryevichD** [comment]
In this project lombok add CacheChecker in constructor. This is not work.
In `CacheChecker` I add value to cache
`cacheService.put(SOME_KEY, "value");`
but in next string, when I get value by this key -  return null
`val result = cacheService.get(SOME_KEY);`
I want get my "value" by this key.

**Comment by snicoll** [comment]
I see it now. As I've indicated above, your triggering early initialization (see the excerpt of the logs in my first comment). So the cache just doesn't work (the cache proxy is not created). Injecting a bean in a `FactoryBean` constructor is a bad idea anyway. I've moved the dependency to setter injection and those logs are gone and the cache proxy is now created.

Your put implementation doesn't do anything so the only thing the get can do really is return `null`. If you have more questions, please ask on StackOverflow.

**Comment by DmitryevichD** [comment]
Thanks for the quick and constructive answer.
