### ISSUE TITLE
Specified transaction manager is not a ReactiveTransactionManager

### ISSUE THREAD

**Issue by okhowang** [spring-projects/spring-framework#23932]
**Affects:** 5.2.0.RELEASE

after upgrade to spring boot 2.2
method with `@Transactional` will throw exception
```
java.lang.IllegalStateException: Specified transaction manager is not a ReactiveTransactionManager: org.springframework.orm.jpa.JpaTransactionManager@4674ac4d
	at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.asReactiveTransactionManager(TransactionAspectSupport.java:957) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.determineTransactionManager(TransactionAspectSupport.java:929) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:848) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:335) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at com.tencent.cloud.iov.account.service.CAMService$$EnhancerBySpringCGLIB$$fcb5db19.process(<generated>) ~[main/:na]
```
it's look like
because there is graphql-java in classpath, which depend reactivestreams
and spring do reactive transaction due to reactivestreams in classpath
but my application is a spring mvc application
```java
	/**
	 * Reactive Streams API present on the classpath?
	 */
	private static final boolean reactiveStreamsPresent =
			ClassUtils.isPresent("org.reactivestreams.Publisher", TransactionAspectSupport.class.getClassLoader());
```

expected result: work normal as spring 5.1/ spring boot 2.1

**Comment by snicoll** [comment]
@okhowang thanks for the report but I believe this has already been fixed (see #23832). You can test with Spring Boot 2.2.0 by overriding Spring Framework to 5.2.1 or wait for Spring Boot 2.2.1 to be released shortly. 

If the upgrade didn't work, please let us know by attaching a small sample to this issue and we'll reconsider.
