### ISSUE TITLE
Cache level when using spring.artemis.pool.enabled with spring-boot-starter-artemis

### ISSUE THREAD

**Issue by bigon** [spring-projects/spring-framework#24360]
Hello,

When I'm using spring-boot-starter-artemis with org.messaginghub pooled-jms, if I'm stopping the application (or sometimes during the execution) I get:

```
javax.jms.IllegalStateException: Session is closed
	at org.apache.activemq.artemis.jms.client.ActiveMQSession.checkClosed(ActiveMQSession.java:1165) ~[artemis-jms-client-2.6.4.jar:2.6.4]
	at org.apache.activemq.artemis.jms.client.ActiveMQSession.setMessageListener(ActiveMQSession.java:315) ~[artemis-jms-client-2.6.4.jar:2.6.4]
	at org.messaginghub.pooled.jms.JmsPoolSession.close(JmsPoolSession.java:91) ~[pooled-jms-1.0.6.jar:na]
	at org.springframework.jms.support.JmsUtils.closeSession(JmsUtils.java:109) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.clearResources(DefaultMessageListenerContainer.java:1242) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.access$100(DefaultMessageListenerContainer.java:1048) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer.doShutdown(DefaultMessageListenerContainer.java:594) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.jms.listener.AbstractJmsListeningContainer.shutdown(AbstractJmsListeningContainer.java:244) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.jms.listener.AbstractJmsListeningContainer.destroy(AbstractJmsListeningContainer.java:184) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.jms.config.JmsListenerEndpointRegistry.destroy(JmsListenerEndpointRegistry.java:251) ~[spring-jms-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1040) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1033) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
```

If the cache is set to `CACHE_CONNECTION` or `CACHE_NONE`, I don't get this exception.

Conceptually shouldn't the cache be disable (automatically) when the pool is used?

**Comment by snicoll** [comment]
Discussing a bit more with @jhoeller we'd like a sample that reproduces this issue please as we consider that this should work and might be an issue elsewhere.

**Comment by bigon** [comment]
Hello @snicoll 

I believe I was able to get the backtrace and the cache/pool behavior with https://start.spring.io/ with the "Apache ActiveMQ Artemis" dependency, so it should be really easy to reproduce

**Comment by snicoll** [comment]
@bigon sweet. If you don't mind, instructions on how to reproduce it would be very much welcome.

**Comment by bigon** [comment]
Hello @snicoll,

I finally had the time to look at this again, as said this is an almost non-modified quick-start from https://start.spring.io/

With the code attached here, the number of threads is never going above 1 (while `spring.jms.listener.max-concurrency` is set to 5) and I get the `javax.jms.IllegalStateException: Session is closed` when stopping the application.

If I uncomment the code in `DemoApplication.java` and set the cache to `CACHE_CONNECTION` (or to `CACHE_NONE`), the number of threads is going to 5 (as I would expect) and I don't get the `IllegalStateException` on exit.


[demo-artemis.zip](https://github.com/spring-projects/spring-framework/files/4370701/demo-artemis.zip)

**Comment by ymajoros** [comment]
@snicoll @jhoeller any news on this? Got the same stack trace today.

**Comment by jhoeller** [comment]
I don't see anything that we can do about this from the core framework side. We defensively catch and log any exceptions thrown within `JmsUtils.closeSession` already; I actually wonder where that stacktrace comes from, we only log that at trace level.

Also, we allow for changing the cache level in the listener container. Automatically adapting the cache level isn't really feasible since there is no reliable way to detect a pooled ConnectionFactory, so I'm afraid this will have to be explicitly configured.

As a side note, there is generally no need to configure a listener container with a pooled ConnectionFactory to begin with since it is capable of performing specific resource reuse for its own purposes in any case. A pooled ConnectionFactory is primarily useful for sending purposes via JmsTemplate and co.
