### ISSUE TITLE
Mockito cannot mock @Async method

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#24724]
When trying to mock an `@Async` method from a `@SpyBean` I get the following error:

```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced or misused argument matcher detected here:

-> at package.TestClass.init_aroundBody0(File.java:79)
-> at package.TestClass.init_aroundBody0(File.java:79)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

This message may appear after an NullPointerException if the last matcher is returning an object 
like any() but the stubbed method signature expect a primitive argument, in this case,
use primitive alternatives.
    when(mock.get(any())); // bad use, will raise NPE
    when(mock.get(anyInt())); // correct usage use

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.
```

This error only appears when I run the test without debugger attached. When I try to debug, the error doesn't show up, and everything works fine.
When I remove the `@Async`, then it works also without the debugger attached.

This error started showing up after I upgraded from spring 4 to spring 5.
Using **spring-boot-starter-test 2.1.6.RELEASE** (mockito-core:2.23.4, spring-test:5.1.8.RELEASE)

**Comment by cdalexndr** [comment]
Still reproductible with Spring 5.3.3

**Comment by snicoll** [comment]
This looks like a more general problem, see https://github.com/spring-projects/spring-framework/issues/24735#issuecomment-601172062 that has a reproducer for `@Cacheable` with AspectJ.

**Comment by leogong** [comment]
I have the same problem. Spy a bean which is a AOP proxy bean, same error occured.

**Comment by DennisGoermannMD** [comment]
Hello, we have this issue too. 
Usecase:
We want to test the caching. 
Problem:
With a @SpyBean it does not work. The same test runs with an autowired bean. If the Bean is with @SpyBean intialized the values for the cachekey becomes null.
Workaround:
As workaround, we could use an autowired bean in this case. But if we do so, the (collection of) tests tooks more time. We want to have only one "base" test file with all beans initialized with @SpyBean, so we can mock or not in every test case. The advantage is that no spring context will be reloaded and the tests runs faster.

**Comment by ghilainm** [comment]
Same issue here. @SpyBean with @Cacheable does not work.
