### ISSUE TITLE
Usage of java 14 record throws java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL

### ISSUE THREAD

**Issue by kevinleturc** [spring-projects/spring-framework#24722]
**Affects:** spring-core 5.2.4.RELEASE

---
I'm using the java 14 records in my application. Since the upgrade from `5.2.3.RELEASE` to `5.2.4.RELEASE`, I'm facing this kind of issue when running the application:
```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/Users/kleturc/ws_perso/spring-boot-java14-record/target/classes/fr/kevinleturc/java/record/Point.class]; nested exception is java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
  at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:454)
  at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316)
  at org.springframework.boot.test.context.AnnotatedClassFinder.scanPackage(AnnotatedClassFinder.java:90)
  at org.springframework.boot.test.context.AnnotatedClassFinder.findFromPackage(AnnotatedClassFinder.java:82)
  at org.springframework.boot.test.context.AnnotatedClassFinder.findFromClass(AnnotatedClassFinder.java:68)
  at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.getOrFindConfigurationClasses(SpringBootTestContextBootstrapper.java:232)
  at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:149)
  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:395)
  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildDefaultMergedContextConfiguration(AbstractTestContextBootstrapper.java:312)
  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:265)
  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:108)
  at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.buildTestContext(SpringBootTestContextBootstrapper.java:99)
  at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:137)
  at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:122)
  at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
  at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
  at org.junit.jupiter.engine.execution.ExtensionValuesStore.remove(ExtensionValuesStore.java:98)
  at org.junit.jupiter.engine.execution.NamespaceAwareStore.remove(NamespaceAwareStore.java:73)
  at org.springframework.test.context.junit.jupiter.SpringExtension.afterAll(SpringExtension.java:89)
  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$13(ClassBasedTestDescriptor.java:421)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$14(ClassBasedTestDescriptor.java:421)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:421)
  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:213)
  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:77)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:145)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
  ... 27 more
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
  at org.springframework.asm.ClassVisitor.visitRecordComponentExperimental(ClassVisitor.java:305)
  at org.springframework.asm.ClassReader.readRecordComponent(ClassReader.java:931)
  at org.springframework.asm.ClassReader.accept(ClassReader.java:705)
  at org.springframework.asm.ClassReader.accept(ClassReader.java:401)
  at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:50)
  at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
  at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:132)
  at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430)
  ... 55 more
```

I created a sample project which highlights the issue: https://github.com/kevinleturc/spring-boot-java14-record

Just run command below to get the test failing:
```
mvn clean install -Dspring-core.version=5.2.4.RELEASE
```

Culprit seems to be the upgrade of ASM to `7.3.1` (#24438). It makes java record a `ASM8_EXPERIMENTAL` feature.

**Comment by olucasfelix** [comment]
Hi! Is there some workaround for this? 

I'm trying to see the [josh long video using Spring and Java 14](https://youtu.be/mr-7kGy8Yao), but I can't reproduce due to this `UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL` exception. thanks!
