### ISSUE TITLE
spring-orm tx Isolation bug  in eclipseLink

### ISSUE THREAD

**Issue by deanwong** [spring-projects/spring-framework#24802]
In EclipseLinkJpaDialect class line 81
```
if (definition.getIsolationLevel() != TransactionDefinition.ISOLATION_DEFAULT) {
	// Pass custom isolation level on to EclipseLink's DatabaseLogin configuration
	// (since Spring 4.1.2)
	UnitOfWork uow = entityManager.unwrap(UnitOfWork.class);
	uow.getLogin().setTransactionIsolation(definition.getIsolationLevel());
}
```

for instance:
If txA beginTransaction and there is Isolation.SERIALIZABLE around the repository class, the TransactionIsolation in uow.getLogin() will be changed to Isolation.SERIALIZABLE.
Then txB beginTransaction with Isolation.DEFAULT, the condition is not met,  TransactionIsolation in uow.getLogin()  still be SERIALIZABLE.

I think the right code should like this:

```
if (definition.getIsolationLevel() != TransactionDefinition.ISOLATION_DEFAULT
   && definition.getIsolationLevel() != entityManager.unwrap(UnitOfWork.class).getLogin().setTransactionIsolation()) {
	// ... 
}
```

**Comment by sbrannen** [comment]
@deanwong, I think you meant to use `getTransactionIsolation()` instead of `setTransactionIsolation()` -- right?

**Comment by deanwong** [comment]
@sbrannen  yes

correct 
```
definition.getIsolationLevel() != entityManager.unwrap(UnitOfWork.class).getLogin().getTransactionIsolation()) 
```

**Comment by jhoeller** [comment]
`UnitOfWork` is supposed to be an independent instance for every `EntityManager`, so I wonder why there would be old serialization settings exposed there? Every fresh `UnitOfWork` within a new transaction should come with EclipseLink's default settings... We just override those if necessary, and at the end of every transaction the `UnitOfWork` and its settings gets closed and disposed.

**Comment by deanwong** [comment]
We use Hikari as connection pool, does that affect the behavior?

**Comment by jhoeller** [comment]
I suspect that EclipseLink applies the transaction isolation level to the underlying JDBC Connection but does not restore the original isolation level there before it returns the Connection to the pool. As far as I can see, it does not expose the current connection isolation level via `DatabaseLogin.getTransactionIsolation()` though, so the suggested check above won't help. We'd rather have to make sure to restore the original JDBC isolation level ourselves, similar to how we do it with Hibernate. A bit of a shame since EclipseLink has a higher-level API for this, in contrast to Hibernate, so it seems a bit awkward to manually dive down to JDBC level for restoring.

**Comment by deanwong** [comment]
@jhoeller 
I just create a [minimize project ](https://github.com/deanwong/spring-orm-sample) to reproduce this problem. Hope that could help.

**Comment by toalexivanov** [comment]
transactionIsolation field in
org.eclipse.persistence.internal.databaseaccess.DatabasePlatform is not
synchronized. This is the root cause.

DatabasePlatform stores various database settings that rarely
change at runtime. Perhaps that is what implementors of EclipseLink meant for
transactionIsolation as well, set it once and forget. This is how most 
database applications use it anyway. It is rare for an application to use
transaction isolation level other than the default.

An instance of this class is called by JpaTransactionManager which is a Spring 
bean in our application. Application accesses this bean from multiple threads.
Now you can imagine multiple service threads starting transactions with
different isolation levels concurrently. Also statement in
EclipseLinkAdapter.beginTransaction() checks requested transaction isolation
level and simply returns without setting it if it is equal to a default value. 
Transaction isolation level is set to default automatically in Spring if it is 
not set explicitly. In majority of our usages, we don't set this level explicitly 
for one simple reason - default isolation level READ_COMMITTED is sufficient
for our purposes most of the time. However it means that transaction by explicitly
setting non-default isolation level overrides this level for all subsequent transactions. 
Not only that, depending on timing, a transaction in one thread could silently
override transaction isolation level in another thread. 

To remedy this problem I supplied CustomOraclePlatform bean where I override
setTransactionIsolation() and getTransactionIsolation(). These methods make use 
of a ThreadLocal field represeting isolation level. Now each thread gets its own
isolation level. However transactions with different isolation levels 
in the same thread would still experience the problem. Also cached thread pools 
do not reset ThreadLocals. For that we need to prevent EclipseLinkJpaDialect 
from invoking short-circuit check for default level. This can be 
be done by translating TransactionDefinition.ISOLATION_DEFAULT to
TransactionDefinition.ISOLATION_READ_COMMITTED (or whatever default level is
appropriate for your database) in EclipseLinkJpaDialect.beginTransaction(). This
is exactly what I did in CustomEclipseLinkJpaDialect.

**Comment by jhoeller** [comment]
Well spotted, these calls internally delegate to the shared `DatabasePlatform` instance... despite appearing on an independent `UnitOfWork` instance and its `DatabaseLogin`. This means that EclipseLink's own support for transaction isolation levels is effectively unusable for our purposes :-( We'll see whether there is some way to apply an independent isolation level without modifying the `DatabasePlatform` implementation; otherwise we'll have to document this as being severely limited.

**Comment by jhoeller** [comment]
I've locally applied a different patch: Using a custom `TransactionalDatabaseLogin` class for the `UnitOfWork` which locally stores the isolation level and only falls back to the platform-defined isolation level if no transaction-specific isolation level has been set. This seems to work fine so far, and decouples the solution from the vendor-specific `DatabasePlatform` implementation. It also covers the default-isolation-level problem (when mixing transactions with a custom isolation level next to transactions without a specific isolation level) as far as it will set the platform-defined transaction isolation by default, so we don't need to reset the isolation level ourselves.

**Comment by jhoeller** [comment]
It looks like this can only really be solved through a custom `DatabasePlatform` subclass for your particular dialect, overriding `set/getTransactionIsolation` to take the Spring transaction isolation level into account in a thread-local fashion, in interaction with a custom variant of `EclipseLinkJpaDialect`. To some degree I wonder whether we should revert to rejecting custom isolation levels by default in `EclipseLinkJpaDialect`... but then this would also prevent single-threaded scenarios and such custom `DatabasePlatform` variants. Maybe there's something we can do to make the latter easier to implement, and for the standard case we'll document the limitations.

**Comment by toalexivanov** [comment]
Can you just set transaction isolation level directly on a JDBC Connection thus overriding whatever EclipseLink does?

**Comment by jhoeller** [comment]
We could try to operate directly on the JDBC Connection but we'd have to clarify when exactly an EclipseLink Session obtains its JDBC Connection and when exactly it returns the Connection to the pool. Hibernate has well-defined connection policies for that purpose, whereas with EclipseLink we'd probably have to rely on implementation behavior (hoping that it won't change).

**Comment by jhoeller** [comment]
We're rolling an `EclipseLinkJpaDialect` refinement into 6.0.10 and 5.3.28 now: see https://github.com/spring-projects/spring-framework/issues/29997#issuecomment-1575604420

While this still operates on a shared `DatabasePlatform` instance, it should work reliably in concurrent scenarios as well as in scenarios with inconsistent transaction isolation definitions now. This seems to be the best we can do with current EclipseLink, even in its 3.0 and 4.0 version.

**Comment by avgustinmm** [comment]
@jhoeller, all
I've found another related issue with shared `DatabaseLogin` object. I'm not sure if I should add the new issue to this one (I see there is a commit that handles the reported issue). However, my issue seems related - shared `DatabaseLogin` is probably the core issue for both. If needed I could open new issue.

Spring orm version I get the issue with is 6.2.15.

In [Eclipse hawkBit](https://github.com/eclipse-hawkbit/hawkbit) we have sporadic failures of one of our tests `DistributedLockTest.keepLockAlive` ->  e.g. https://github.com/eclipse-hawkbit/hawkbit/actions/runs/20857780854/job/59929050215.

What we see there is: 
<details>
<summary>Internal Exception: org.h2.jdbc.JdbcSQLDataException: Invalid value "-1" for parameter "isolation level" [90008-232]</summary>

```java
Error:  org.eclipse.hawkbit.repository.jpa.cluster.DistributedLockTest.keepLockAlive -- Time elapsed: 2.706 s <<< ERROR!
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.9.v202601021151-061974965b9a70b72fdcb96dae36a4d6ef5df9ce): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLDataException: Invalid value "-1" for parameter "isolation level" [90008-232]
Error Code: 90008
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:334)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.checkTransactionIsolation(DatabaseAccessor.java:342)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:319)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:618)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1820)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:346)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.beginTransaction(DatasourceAccessor.java:270)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicBeginTransaction(AbstractSession.java:761)
	at org.eclipse.persistence.sessions.server.ClientSession.addWriteConnection(ClientSession.java:757)
	at org.eclipse.persistence.sessions.server.ServerSession.acquireClientConnection(ServerSession.java:271)
	at org.eclipse.persistence.sessions.server.ClientSession.getAccessor(ClientSession.java:391)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.getAccessor(UnitOfWorkImpl.java:1963)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.unwrap(EntityManagerImpl.java:2932)
	at org.springframework.orm.jpa.vendor.EclipseLinkJpaDialect$EclipseLinkConnectionHandle.getConnection(EclipseLinkJpaDialect.java:185)
	at org.springframework.jdbc.datasource.ConnectionHolder.getConnection(ConnectionHolder.java:162)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:113)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:653)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:754)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:889)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:918)
	at org.springframework.integration.jdbc.lock.DefaultLockRepository.lambda$isAcquired$3(DefaultLockRepository.java:423)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.integration.jdbc.lock.DefaultLockRepository.isAcquired(DefaultLockRepository.java:420)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:724)
	at org.eclipse.hawkbit.repository.jpa.cluster.DistributedLockRepository$$SpringCGLIB$$0.isAcquired(<generated>)
	at org.eclipse.hawkbit.repository.jpa.cluster.DistributedLockTest.keepLockAlive(DistributedLockTest.java:171)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.h2.jdbc.JdbcSQLDataException: Invalid value "-1" for parameter "isolation level" [90008-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.engine.IsolationLevel.fromJdbc(IsolationLevel.java:67)
	at org.h2.jdbc.JdbcConnection.setTransactionIsolation(JdbcConnection.java:715)
	at com.zaxxer.hikari.pool.ProxyConnection.setTransactionIsolation(ProxyConnection.java:450)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setTransactionIsolation(HikariProxyConnection.java)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.checkTransactionIsolation(DatabaseAccessor.java:338)
	... 33 more
```
</details>

As far as I see in `EclipseLinkJpaDialect.beginTransaction` there is implemented `transactionIsolationLock` in order to do isolation level changes atomic. However, on `EclipseLinkJpaDialect.EclipseLinkConnectionHandle.getConnection` the Eclipse link, under the hood, again deals with transaction isolation level - and if it is concurrently with `beginTransaction` it could fail.
The isolation level seems to be handled in EclipseLink `DatabaseAccessor`:
```java
protected void checkTransactionIsolation(AbstractSession session) throws DatabaseException {
        if ((!this.isInTransaction) && (this.login != null) && (((DatabaseLogin)this.login).getTransactionIsolation() != -1)) {
            try {
                getConnection().setTransactionIsolation(((DatabaseLogin)this.login).getTransactionIsolation());
            } catch (java.sql.SQLException sqlEx) {
                DatabaseException commException = processExceptionForCommError(session, sqlEx, null);
                if (commException != null) throw commException;
                throw DatabaseException.sqlException(sqlEx, this, session, false);
            }
        }
    }
```

**Comment by jhoeller** [comment]
@avgustinmm I suppose that means that we have to execute the `unwrap(Connection.class)` within the `transactionIsolationLock`. I went ahead and created a corresponding issue which I'll fix right away.

This could also be fixed in EclipseLink itself through only calling `getTransactionIsolation()` once and then performing the -1 check against a local variable, but we can just as well be defensive on Spring's side as well.
