### ISSUE TITLE
Jackson2ObjectMapperBuilder rejects JaxRSFeature

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-framework#25407]
**Affects:** 5.2.7
Trying to disable [JaxRSFeature.ALLOW_EMPTY_INPUT](https://github.com/FasterXML/jackson-jaxrs-providers/blob/master/base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/JaxRSFeature.java#L28) I discovered that `Jackson2ObjectMapperBuilder` will throw an exception.
```java
public Jackson2ObjectMapperBuilderCustomizer basicObjectMapperBuilderCustomizer() {
        return builder -> {
            builder.serializationInclusion(JsonInclude.Include.NON_NULL);
            builder.featuresToDisable(JaxRSFeature.ALLOW_EMPTY_INPUT);
        };
    }
```

````
org.springframework.beans.FatalBeanException: Unknown feature class: com.fasterxml.jackson.jaxrs.cfg.JaxRSFeature
        at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.configureFeature(Jackson2ObjectMapperBuilder.java:786) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.lambda$configure$2(Jackson2ObjectMapperBuilder.java:725) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
````

Please suport `JaxRSFeature` too.

**Comment by andrei-ivanov** [comment]
Hmm, I think this is invalid as it seems `JaxRSFeature` is meant for a subclass of `com.fasterxml.jackson.jaxrs.base.ProviderBase`, like `JacksonJsonProvider`
