### ISSUE TITLE
Using RestTemplate to submit the data to the rest endpoint throwing StackOverflow Error 

### ISSUE THREAD

**Issue by SanjayGautam** [spring-projects/spring-framework#25492]
Using RestTemplate to submit the data to the rest endpoint throwing below error 

Caused by: java.lang.StackOverflowError: null
        at org.springframework.http.client.support.HttpRequestWrapper.getHeaders(HttpRequestWrapper.java:88)
        at org.springframework.http.client.support.HttpRequestWrapper.getHeaders(HttpRequestWrapper.java:88)
        at org.springframework.http.client.support.HttpRequestWrapper.getHeaders(HttpRequestWrapper.java:88)
        at org.springframework.http.client.support.HttpRequestWrapper.getHeaders(HttpRequestWrapper.java:88)

**Comment by quaff** [comment]
Show your code.

**Comment by bclozel** [comment]
@SanjayGautam Could you share a sample project demonstrating the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
