### ISSUE TITLE
./gradlew :spring-oxm:compileTestJava  error

### ISSUE THREAD

**Issue by WangAlainDelon** [spring-projects/spring-framework#25611]
40 actionable tasks: 40 up-to-date
Build scan background action failed.
org.gradle.process.internal.ExecException: Process 'command 'git'' finished with non-zero exit value 128
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:409)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at io.spring.ge.WorkingDirectoryProcessOperations.exec(WorkingDirectoryProcessOperations.java:45)
        at io.spring.ge.BuildScanConventions.exec(BuildScanConventions.java:161)
        at io.spring.ge.BuildScanConventions.addGitMetadata(BuildScanConventions.java:110)
        at com.gradle.scan.plugin.internal.api.j.a(SourceFile:22)
        at com.gradle.scan.plugin.internal.api.k$a.a(SourceFile:112)
        at com.gradle.scan.plugin.internal.api.h.a(SourceFile:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by sbrannen** [comment]
Have you tried disabling the background uploading as follows?

```shell
./gradlew build -Dscan.uploadInBackground=false
```

If that doesn't work, you should be able to disable the build scan altogether as follows

```shell
./gradlew build --no-scan
```

In light of the above, I am closing this issue. However, if you continue to face issues or think you have encountered a genuine bug, feel free to post additional information here.
