### ISSUE TITLE
DataBufferUtils.CompositeMatcher causes poor performance when one or more matchers does not match

### ISSUE THREAD

**Issue by DanielThomas** [spring-projects/spring-framework#25915]
I noticed my CPU pegged for over a minute reading a 675K text resource when subscribing to a flux for a response in a test:

```
        val events = ClientResponse.create(HttpStatus.OK)
            .body(eventsBody)
            .build()
            .bodyToFlow<ServerSentEvent<JsonNode>>()
```

When I hooked up YourKit all the time was being spent in `org.springframework.core.io.buffer.DataBufferUtils.KnuthMorrisPrattMatcher#match`:

<img width="950" alt="Screen Shot 2020-10-14 at 3 52 11 pm" src="https://user-images.githubusercontent.com/1479220/95945166-97564100-0e35-11eb-9b8d-32e3d9ec0e94.png">

After stepping in the debugger I noticed the problem - the default delimiter bytes are for DOS line endings and newlines and because `DataBufferUtils.CompositeMatcher` doesn't hold onto state indicating if a matcher previously failed to find a match, each time the newline delimiter is seen the entire input has to be scanned again.

The `StringDecoder` is created here:
```
"scheduling-1@17393" prio=5 tid=0xcd nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.core.codec.StringDecoder.<init>(StringDecoder.java:79)
	  at org.springframework.core.codec.StringDecoder.textPlainOnly(StringDecoder.java:239)
	  at org.springframework.core.codec.StringDecoder.textPlainOnly(StringDecoder.java:229)
	  at org.springframework.http.codec.ServerSentEventHttpMessageReader.<init>(ServerSentEventHttpMessageReader.java:58)
	  at org.springframework.http.codec.support.ClientDefaultCodecsImpl.extendObjectReaders(ClientDefaultCodecsImpl.java:103)
	  at org.springframework.http.codec.support.BaseDefaultCodecs.getObjectReaders(BaseDefaultCodecs.java:354)
	  at org.springframework.http.codec.support.BaseCodecConfigurer.getReaders(BaseCodecConfigurer.java:100)
	  at org.springframework.http.codec.support.DefaultClientCodecConfigurer.getReaders(DefaultClientCodecConfigurer.java:31)
	  at org.springframework.web.reactive.function.client.DefaultExchangeStrategiesBuilder$DefaultExchangeStrategies.<init>(DefaultExchangeStrategiesBuilder.java:86)
	  at org.springframework.web.reactive.function.client.DefaultExchangeStrategiesBuilder.build(DefaultExchangeStrategiesBuilder.java:71)
	  at org.springframework.web.reactive.function.client.DefaultExchangeStrategiesBuilder.<clinit>(DefaultExchangeStrategiesBuilder.java:42)
	  at org.springframework.web.reactive.function.client.ExchangeStrategies.withDefaults(ExchangeStrategies.java:67)
	  at org.springframework.web.reactive.function.client.DefaultWebClientBuilder.initExchangeStrategies(DefaultWebClientBuilder.java:287)
	  at org.springframework.web.reactive.function.client.DefaultWebClientBuilder.build(DefaultWebClientBuilder.java:260)
	  at org.springframework.web.reactive.function.client.WebClient.create(WebClient.java:150)
```

I've worked around for now by running the file through `unix2dos`.

**Comment by DanielThomas** [comment]
I didn't expect this to be such a contributor to production code (I thought this was as expensive as it is because of a large, non-streaming input), but looks like it's just as bad there too:

<img width="1206" alt="Screen Shot 2020-10-15 at 4 03 07 pm" src="https://user-images.githubusercontent.com/1479220/96079262-131cc000-0f00-11eb-9214-2e24ef049a37.png">

**Comment by rstoyanchev** [comment]
Thanks for reporting your findings. I've scheduled it tentatively to explore some improvements. 

It is a little surprising that it takes a 1 minute for 675K and that's with just 8 concurrent streams? Any chance of providing a reproducer?

**Comment by rstoyanchev** [comment]
Or some sample input would be quite helpful.

**Comment by DanielThomas** [comment]
Happy to help - https://github.com/DanielThomas/spring-framework-issue-25915

```
20:50:49.926 [main] INFO  Issue25915 - Reading unix SSE
20:51:09.555 [main] INFO  Issue25915 - Unix line ending duration 19627ms
20:51:09.556 [main] INFO  Issue25915 - Reading DOS SSE
20:51:09.603 [main] INFO  Issue25915 - Dos line ending duration 47ms
```

**Comment by rstoyanchev** [comment]
Super, thanks!

**Comment by rstoyanchev** [comment]
This should is fixed now. I've confirmed with the sample as well. Thanks again for the helpful report!

**Comment by DanielThomas** [comment]
Awesome, appreciate it. Elegant fix too!
