### ISSUE TITLE
java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by chailinglu** [spring-projects/spring-framework#26322]
**Affects:** `4.3.1.RELEASE`

 * Spring Boot `1.5.10.RELEASE`
 * Spring Cloud `1.3.4.RELEASE`

**ErrorCode:**
```java
ResponseEntity<String> response = restTemplate.postForEntity(url, request, String.class);
```

**Exception StackTrace:**
```
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at org.springframework.web.client.RestTemplate$AcceptHeaderRequestCallback.doWithRequest(RestTemplate.java:771)
        at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:836)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:658)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:621)
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:415)
        at org.springframework.web.client.RestTemplate$$FastClassBySpringCGLIB$$aa4e9ed0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at org.springframework.cloud.netflix.metrics.RestTemplateUrlTemplateCapturingAspect.captureUrlTemplate(RestTemplateUrlTemplateCapturingAspect.java:33)
        at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at org.springframework.web.client.RestTemplate$$EnhancerBySpringCGLIB$$542b8900.postForEntity(<generated>)
```

**Comment by quaff** [comment]
Please verify with latest version 5.3.2 or 4.3.30.

**Comment by chailinglu** [comment]
> Please verify with latest version 5.3.2 or 4.3.30.

**Comment by snicoll** [comment]
@quaff thank you. Please note that `4.3.x` is EOL as  well now, see [supported versions](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#supported-versions) on the wiki.
