### ISSUE TITLE
Client WS disconnect triggers server failure

### ISSUE THREAD

**Issue by JanStureNielsen** [spring-projects/spring-framework#26710]
The [ws.disconnect()](https://github.com/spring-guides/gs-messaging-stomp-websocket/blob/master/complete/src/test/java/com/example/messagingstompwebsocket/GreetingIntegrationTests.java#L77) in the `gs-messaging-stomp-websocket` sample can trigger this on the associated server when run as separate applications:

```
2021-03-21 12:34:59.943[0;39m [32mDEBUG[0;39m [35m12622[0;39m [2m---[0;39m [2m[boundChannel-31][0;39m [36ms.w.s.s.t.s.WebSocketServerSockJsSession[0;39m [2m:[0;39m Terminating connection after failure to send message to client

java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:439) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:311) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:251) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:224) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.writeFrameInternal(WebSocketServerSockJsSession.java:224) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:326) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.sendMessageInternal(WebSocketServerSockJsSession.java:213) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendMessage(AbstractSockJsSession.java:170) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.tryFlushMessageBuffer(ConcurrentWebSocketSessionDecorator.java:190) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.sendMessage(ConcurrentWebSocketSessionDecorator.java:163) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:494) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:481) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:366) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.5.jar:5.3.5]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

[2m2021-03-21 12:34:59.945[0;39m [32mDEBUG[0;39m [35m12622[0;39m [2m---[0;39m [2m[boundChannel-31][0;39m [36mo.s.w.s.m.StompSubProtocolHandler       [0;39m [2m:[0;39m Failed to send WebSocket message to client in session 23326ba4647c4e33b5de83f443398b33

org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to write SockJsFrame content='a["ERROR\nmessage:Session closed.\ncontent-length:0\n\n\u0000"]'; nested exception is java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:343) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.sendMessageInternal(WebSocketServerSockJsSession.java:213) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendMessage(AbstractSockJsSession.java:170) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.tryFlushMessageBuffer(ConcurrentWebSocketSessionDecorator.java:190) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.sendMessage(ConcurrentWebSocketSessionDecorator.java:163) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:494) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:481) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:366) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.5.jar:5.3.5]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:439) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:311) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:251) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:224) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.writeFrameInternal(WebSocketServerSockJsSession.java:224) ~[spring-websocket-5.3.5.jar:5.3.5]
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:326) ~[spring-websocket-5.3.5.jar:5.3.5]
	... 11 common frames omitted
```
More often than not, I have to restart the server after a single apparently successful client run. Although this is sample code, the server-side should not become unstable from a quick client disconnect (or any other client action for that matter).

**Comment by snicoll** [comment]
> You can reproduce from [my repository](https://github.com/JanStureNielsen/websocket-samples/tree/spring-framework-issue-26710) or from the Spring Guides repository.

Unfortunately, looking at the repository and the description above, I have not found how to reproduce the problem. Can you please clarify the steps to reproduce?
