### ISSUE TITLE
java.lang.NoSuchMethodError: org.springframework.util.Assert.isTrue(ZLjava/util/function/Supplier;)V

### ISSUE THREAD

**Issue by Shreevas-Karanth** [spring-projects/spring-framework#26853]
Getting this Error 

```
Caused by: java.lang.NoSuchMethodError: org.springframework.util.Assert.isTrue(ZLjava/util/function/Supplier;)V
	at org.springframework.data.mapping.model.BasicPersistentEntity.getPropertyAccessor(BasicPersistentEntity.java:427)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:276)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:253)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:202)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:198)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:86)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:2775)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2439)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2235)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2218)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:774)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:760)
	at com.tarento.framework.util.AppConfiguration.propertiesReload(AppConfiguration.java:448)
	at com.tarento.framework.util.AppConfiguration.afterPropertiesSet(AppConfiguration.java:166)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	... 199 more
```

I am currently using spring version 4.2.9. RELEASE and spring data mongodb 2.0.3.RELEASE

**Comment by sbrannen** [comment]
> spring data mongodb 2.0.3.RELEASE

That artifact requires [Spring Framework 5.0.3.RELEASE](https://repo1.maven.org/maven2/org/springframework/data/build/spring-data-parent/2.0.3.RELEASE/spring-data-parent-2.0.3.RELEASE.pom).

Note that the method in question was introduced in Spring Framework 5.0 (#19020).

Thus, you either need to upgrade to Spring Framework 5.0.x or downgrade the version of Spring Data MongoDB that you use so that it is compatible with Spring Framework 4.2.9.
