### ISSUE TITLE
Spring version upgrade to 5.3.7 from 5.3.6 gives issues on activemq "Could not load xbean "

### ISSUE THREAD

**Issue by sagga001** [spring-projects/spring-framework#27382]
ACTIVEMQ_HOME: /opt/na/activemq
ACTIVEMQ_BASE: /opt/na/activemq
ACTIVEMQ_CONF: /opt/na/activemq/conf
ACTIVEMQ_DATA: /opt/na/activemq/data
Loading message broker from: xbean:activemq.xml?validate=false
ERROR: java.lang.RuntimeException: Failed to execute start task. Reason: java.io.IOException: Could not load xbean factory:java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext
java.lang.RuntimeException: Failed to execute start task. Reason: java.io.IOException: Could not load xbean factory:java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext
        at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:91)
        at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
        at org.apache.activemq.console.command.ShellCommand.runTask(ShellCommand.java:154)
        at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
        at org.apache.activemq.console.command.ShellCommand.main(ShellCommand.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.activemq.console.Main.runTaskClass(Main.java:262)
        at org.apache.activemq.console.Main.main(Main.java:115)
Caused by: java.io.IOException: Could not load xbean factory:java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext
        at org.apache.activemq.util.IOExceptionSupport.create(IOExceptionSupport.java:28)

Is activemq and spring version compatability mentione somewhere ? Or list of any known issues?

**Comment by bclozel** [comment]
Could you reach out to the activeMQ project? This looks like a setup issue rather than a Spring Framework issue. Thanks!

**Comment by sagga001** [comment]
But I am not facing this if I revert back to 5.3.6

**Comment by snicoll** [comment]
@sagga001 `java.lang.NoClassDefFoundError` means you have a broken setup. Reverting to a previous setup that works is no proof that it's a bug in that version.

**Comment by sagga001** [comment]
Thanks @snicoll . I am not saying its a bug but I think there is some incompatability
