### ISSUE TITLE
NullPointerException in Smile encoder when encoding empty publisher

### ISSUE THREAD

**Issue by fedortche** [spring-projects/spring-framework#27661]
**Affects:** 5.3.12

---

NullPointerException in Smile encoder in case of empty publisher:

```
23:01:06.221 ERROR reactor.core.publisher.Operators [elastic-2]: Operator called default onErrorDropped
java.lang.NullPointerException: null
        at com.fasterxml.jackson.core.util.ByteArrayBuilder.write(ByteArrayBuilder.java:245) ~[jackson-core-2.12.5.jar:2.12.5]
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator._flushBuffer(SmileGenerator.java:2596) ~[jackson-dataformat-smile-2.12.5.jar:2.12.5]
        at com.fasterxml.jackson.dataformat.smile.SmileGenerator.close(SmileGenerator.java:1854) ~[jackson-dataformat-smile-2.12.5.jar:2.12.5]
        at org.springframework.http.codec.json.AbstractJackson2Encoder.lambda$encode$2(AbstractJackson2Encoder.java:173) ~[spring-web-5.3.12.jar:5.3.12]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:282) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onComplete(FluxDoOnEach.java:223) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:894) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:997) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:498) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:86) ~[reactor-core-3.4.11.jar:3.4.11]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
```

**Comment by fedortche** [comment]
WIll check further, most porbably that's a Jackson issue
