### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by dylan-tao** [spring-projects/spring-framework#28222]
spring-core-5.3.16

when i invoke org.springframework.cglib.beans.BeanMap.create(obj)，I checked this class(BeanMapEmitter.class) doesn't exist, but it's still being quoted(org.springframework.cglib.beans.BeanMap.Generator#generateClass, line number: 141)，appear this following error message: 

> Exception in thread "main" java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at org.springframework.cglib.beans.BeanMap$Generator.create(BeanMap.java:138)
	at org.springframework.cglib.beans.BeanMap.create(BeanMap.java:68)
	at com.javaosc.kernel.common.enhance.KitReflectionTest.main(KitReflectionTest.java:28)
Caused by: java.lang.NoClassDefFoundError: org/springframework/cglib/beans/BeanMapEmitter
	at org.springframework.cglib.beans.BeanMap$Generator.generateClass(BeanMap.java:142)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:358)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.springframework.cglib.beans.BeanMapEmitter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more

**Comment by dylan-tao** [comment]
> Thanks for the report. This is a duplicate of #28110. Please upgrade to `5.3.17`.

i‘m using spring-boot-2.5.10，BeanMap.create(obj) ref is my framework core. Please confirm date of the next release, thanks!
