### ISSUE TITLE
nested exception is java.lang.ArrayIndexOutOfBoundsException: 23309

### ISSUE THREAD

**Issue by 2509569172** [spring-projects/spring-framework#28605]
1.spring version
spring-context-3.0.5.RELEASE.jar

2.error code
![image](https://user-images.githubusercontent.com/49397581/173047166-3cef2e64-c16c-489b-a238-5ccbef38c7f5.png)

3.exception
"D:\Program Files\Java\jdk1.8.0_202\bin\java.exe" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.2\lib\idea_rt.jar=50379:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.2\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\Java\jdk1.8.0_202\jre\lib\charsets.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\deploy.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\access-bridge-64.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\cldrdata.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\dnsns.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\jaccess.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\jfxrt.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\localedata.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\nashorn.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunec.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunjce_provider.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunmscapi.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunpkcs11.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\zipfs.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\javaws.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\jce.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\jfr.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\jfxswt.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\jsse.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\management-agent.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\plugin.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\resources.jar;D:\Program Files\Java\jdk1.8.0_202\jre\lib\rt.jar;D:\worksapce\vsim-core\vsim-apps\vsim-dse\target\classes;D:\worksapce\vsim-core\vsim-base\base-cfg\target\classes;D:\work\apache-maven-3.8.4\repo\commons-configuration\commons-configuration\1.10\commons-configuration-1.10.jar;D:\work\apache-maven-3.8.4\repo\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\work\apache-maven-3.8.4\repo\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;D:\work\apache-maven-3.8.4\repo\commons-jxpath\commons-jxpath\1.3\commons-jxpath-1.3.jar;D:\work\apache-maven-3.8.4\repo\org\apache\commons\commons-vfs2\2.0\commons-vfs2-2.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\maven\scm\maven-scm-api\1.4\maven-scm-api-1.4.jar;D:\work\apache-maven-3.8.4\repo\org\codehaus\plexus\plexus-utils\1.5.6\plexus-utils-1.5.6.jar;D:\work\apache-maven-3.8.4\repo\org\apache\maven\scm\maven-scm-provider-svnexe\1.4\maven-scm-provider-svnexe-1.4.jar;D:\work\apache-maven-3.8.4\repo\org\apache\maven\scm\maven-scm-provider-svn-commons\1.4\maven-scm-provider-svn-commons-1.4.jar;D:\work\apache-maven-3.8.4\repo\regexp\regexp\1.3\regexp-1.3.jar;D:\work\apache-maven-3.8.4\repo\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;D:\work\apache-maven-3.8.4\repo\com\jcraft\jsch\0.1.50\jsch-0.1.50.jar;D:\work\apache-maven-3.8.4\repo\commons-net\commons-net\3.3\commons-net-3.3.jar;D:\work\apache-maven-3.8.4\repo\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-beans\3.0.5.RELEASE\spring-beans-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\cglib\cglib-nodep\2.1_3\cglib-nodep-2.1_3.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-context-support\3.0.5.RELEASE\spring-context-support-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-core\3.0.5.RELEASE\spring-core-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-test\3.0.5.RELEASE\spring-test-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springmodules\spring-modules-jakarta-commons\0.8\spring-modules-jakarta-commons-0.8.jar;D:\work\apache-maven-3.8.4\repo\commons-validator\commons-validator\1.1.4\commons-validator-1.1.4.jar;D:\work\apache-maven-3.8.4\repo\commons-chain\commons-chain\1.1\commons-chain-1.1.jar;D:\work\apache-maven-3.8.4\repo\javax\portlet\portlet-api\1.0\portlet-api-1.0.jar;D:\work\apache-maven-3.8.4\repo\myfaces\myfaces-api\1.1.0\myfaces-api-1.1.0.jar;D:\work\apache-maven-3.8.4\repo\commons-el\commons-el\1.0\commons-el-1.0.jar;D:\work\apache-maven-3.8.4\repo\commons-fileupload\commons-fileupload\1.0\commons-fileupload-1.0.jar;D:\work\apache-maven-3.8.4\repo\oro\oro\2.0.8\oro-2.0.8.jar;D:\work\apache-maven-3.8.4\repo\javax\servlet\jstl\1.1.2\jstl-1.1.2.jar;D:\work\apache-maven-3.8.4\repo\commons-digester\commons-digester\1.6\commons-digester-1.6.jar;D:\work\apache-maven-3.8.4\repo\javax\servlet\servlet-api\2.3\servlet-api-2.3.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-tx\3.0.5.RELEASE\spring-tx-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-aop\3.0.5.RELEASE\spring-aop-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-jdbc\3.0.5.RELEASE\spring-jdbc-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-orm\3.0.5.RELEASE\spring-orm-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-oxm\3.0.5.RELEASE\spring-oxm-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\mysql\mysql-connector-java\5.1.25\mysql-connector-java-5.1.25.jar;D:\work\apache-maven-3.8.4\repo\commons-dbcp\commons-dbcp\1.4\commons-dbcp-1.4.jar;D:\work\apache-maven-3.8.4\repo\commons-pool\commons-pool\1.6\commons-pool-1.6.jar;D:\work\apache-maven-3.8.4\repo\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;D:\work\apache-maven-3.8.4\repo\org\apache\logging\log4j\log4j-core\2.17.0\log4j-core-2.17.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\logging\log4j\log4j-api\2.17.0\log4j-api-2.17.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\logging\log4j\log4j-slf4j-impl\2.17.0\log4j-slf4j-impl-2.17.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\logging\log4j\log4j-1.2-api\2.17.0\log4j-1.2-api-2.17.0.jar;D:\work\apache-maven-3.8.4\repo\javax\activation\activation\1.1\activation-1.1.jar;D:\work\apache-maven-3.8.4\repo\javax\mail\mail\1.4\mail-1.4.jar;D:\work\apache-maven-3.8.4\repo\org\apache\logging\log4j\log4j-flume-ng\2.17.0\log4j-flume-ng-2.17.0.jar;D:\work\apache-maven-3.8.4\repo\com\sleepycat\je\5.0.73\je-5.0.73.jar;D:\work\apache-maven-3.8.4\repo\org\apache\flume\flume-ng-sdk\1.9.0\flume-ng-sdk-1.9.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\avro\avro\1.7.4\avro-1.7.4.jar;D:\work\apache-maven-3.8.4\repo\com\thoughtworks\paranamer\paranamer\2.3\paranamer-2.3.jar;D:\work\apache-maven-3.8.4\repo\org\apache\avro\avro-ipc\1.7.4\avro-ipc-1.7.4.jar;D:\work\apache-maven-3.8.4\repo\org\mortbay\jetty\jetty\6.1.26\jetty-6.1.26.jar;D:\work\apache-maven-3.8.4\repo\org\mortbay\jetty\jetty-util\6.1.26\jetty-util-6.1.26.jar;D:\work\apache-maven-3.8.4\repo\org\apache\velocity\velocity\1.7\velocity-1.7.jar;D:\work\apache-maven-3.8.4\repo\org\apache\thrift\libthrift\0.9.3\libthrift-0.9.3.jar;D:\work\apache-maven-3.8.4\repo\org\slf4j\jcl-over-slf4j\1.7.0\jcl-over-slf4j-1.7.0.jar;D:\work\apache-maven-3.8.4\repo\com\lmax\disruptor\3.3.0\disruptor-3.3.0.jar;D:\work\apache-maven-3.8.4\repo\commons-beanutils\commons-beanutils\1.8.1\commons-beanutils-1.8.1.jar;D:\work\apache-maven-3.8.4\repo\commons-codec\commons-codec\1.8\commons-codec-1.8.jar;D:\work\apache-maven-3.8.4\repo\com\google\inject\guice\3.0\guice-3.0.jar;D:\work\apache-maven-3.8.4\repo\javax\inject\javax.inject\1\javax.inject-1.jar;D:\worksapce\vsim-core\vsim-base\base-clustering\target\classes;D:\work\apache-maven-3.8.4\repo\org\apache\zookeeper\zookeeper\3.4.6\zookeeper-3.4.6.jar;D:\work\apache-maven-3.8.4\repo\jline\jline\0.9.94\jline-0.9.94.jar;D:\work\apache-maven-3.8.4\repo\io\netty\netty\3.7.0.Final\netty-3.7.0.Final.jar;D:\work\apache-maven-3.8.4\repo\org\apache\curator\curator-framework\4.0.1\curator-framework-4.0.1.jar;D:\work\apache-maven-3.8.4\repo\org\apache\curator\curator-client\4.0.1\curator-client-4.0.1.jar;D:\work\apache-maven-3.8.4\repo\org\apache\curator\curator-recipes\4.0.1\curator-recipes-4.0.1.jar;D:\worksapce\vsim-core\vsim-base\base-clustering-dubbo\target\classes;D:\work\apache-maven-3.8.4\repo\com\alibaba\dubbo\2.5.5\dubbo-2.5.5.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-web\4.3.10.RELEASE\spring-web-4.3.10.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\com\github\sgroschupf\zkclient\0.1\zkclient-0.1.jar;D:\work\apache-maven-3.8.4\repo\org\projectlombok\lombok\1.18.10\lombok-1.18.10.jar;D:\worksapce\vsim-core\vsim-apps\vsim-api\target\classes;D:\work\apache-maven-3.8.4\repo\com\simo\vsim\biz\vsim-external-api\1.0.43\vsim-external-api-1.0.43.jar;D:\worksapce\vsim-core\vsim-base\base-data-access\target\classes;D:\worksapce\vsim-core\vsim-base\base-protocol\target\classes;D:\work\apache-maven-3.8.4\repo\org\apache\commons\commons-compress\1.9\commons-compress-1.9.jar;D:\worksapce\vsim-core\vsim-base\base-common\target\classes;D:\work\apache-maven-3.8.4\repo\org\apache\mina\mina-core\2.0.7\mina-core-2.0.7.jar;D:\work\apache-maven-3.8.4\repo\joda-time\joda-time\2.9.4\joda-time-2.9.4.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-context\3.0.5.RELEASE\spring-context-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-expression\3.0.5.RELEASE\spring-expression-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-asm\3.0.5.RELEASE\spring-asm-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\codehaus\jackson\jackson-core-asl\1.8.5\jackson-core-asl-1.8.5.jar;D:\work\apache-maven-3.8.4\repo\org\codehaus\jackson\jackson-mapper-asl\1.8.5\jackson-mapper-asl-1.8.5.jar;D:\worksapce\vsim-core\vsim-base\base-redis\target\classes;D:\work\apache-maven-3.8.4\repo\redis\clients\jedis\2.9.0\jedis-2.9.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\commons\commons-pool2\2.4.2\commons-pool2-2.4.2.jar;D:\worksapce\vsim-core\vsim-base\base-msgq\target\classes;D:\work\apache-maven-3.8.4\repo\org\apache\activemq\activemq-core\5.7.0\activemq-core-5.7.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\geronimo\specs\geronimo-jms_1.1_spec\1.1.1\geronimo-jms_1.1_spec-1.1.1.jar;D:\work\apache-maven-3.8.4\repo\org\apache\activemq\kahadb\5.7.0\kahadb-5.7.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\activemq\protobuf\activemq-protobuf\1.1\activemq-protobuf-1.1.jar;D:\work\apache-maven-3.8.4\repo\org\fusesource\mqtt-client\mqtt-client\1.3\mqtt-client-1.3.jar;D:\work\apache-maven-3.8.4\repo\org\fusesource\hawtdispatch\hawtdispatch-transport\1.11\hawtdispatch-transport-1.11.jar;D:\work\apache-maven-3.8.4\repo\org\fusesource\hawtdispatch\hawtdispatch\1.11\hawtdispatch-1.11.jar;D:\work\apache-maven-3.8.4\repo\org\fusesource\hawtbuf\hawtbuf\1.9\hawtbuf-1.9.jar;D:\work\apache-maven-3.8.4\repo\org\apache\geronimo\specs\geronimo-j2ee-management_1.1_spec\1.0.1\geronimo-j2ee-management_1.1_spec-1.0.1.jar;D:\work\apache-maven-3.8.4\repo\org\jasypt\jasypt\1.9.0\jasypt-1.9.0.jar;D:\work\apache-maven-3.8.4\repo\org\springframework\spring-jms\3.0.5.RELEASE\spring-jms-3.0.5.RELEASE.jar;D:\work\apache-maven-3.8.4\repo\org\apache\activemq\activemq-pool\5.7.0\activemq-pool-5.7.0.jar;D:\work\apache-maven-3.8.4\repo\org\apache\geronimo\specs\geronimo-jta_1.0.1B_spec\1.0.1\geronimo-jta_1.0.1B_spec-1.0.1.jar;D:\worksapce\vsim-core\vsim-base\base-resource\target\classes;D:\work\apache-maven-3.8.4\repo\com\alibaba\druid\1.0.16\druid-1.0.16.jar;D:\Program Files\Java\jdk1.8.0_202\lib\jconsole.jar;D:\Program Files\Java\jdk1.8.0_202\lib\tools.jar;D:\work\apache-maven-3.8.4\repo\com\baomidou\mybatis-plus\2.3\mybatis-plus-2.3.jar;D:\work\apache-maven-3.8.4\repo\com\baomidou\mybatis-plus-support\2.3\mybatis-plus-support-2.3.jar;D:\work\apache-maven-3.8.4\repo\com\baomidou\mybatis-plus-core\2.3\mybatis-plus-core-2.3.jar;D:\work\apache-maven-3.8.4\repo\com\github\jsqlparser\jsqlparser\1.1\jsqlparser-1.1.jar;D:\work\apache-maven-3.8.4\repo\org\mybatis\mybatis-spring\1.3.2\mybatis-spring-1.3.2.jar;D:\work\apache-maven-3.8.4\repo\org\mybatis\mybatis\3.4.6\mybatis-3.4.6.jar;D:\work\apache-maven-3.8.4\repo\com\baomidou\mybatis-plus-generate\2.3\mybatis-plus-generate-2.3.jar;D:\work\apache-maven-3.8.4\repo\com\google\guava\guava\19.0-rc2\guava-19.0-rc2.jar;D:\work\apache-maven-3.8.4\repo\com\baidu\disconf\disconf-client\2.6.36\disconf-client-2.6.36.jar;D:\work\apache-maven-3.8.4\repo\commons-io\commons-io\1.4\commons-io-1.4.jar;D:\work\apache-maven-3.8.4\repo\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;D:\work\apache-maven-3.8.4\repo\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;D:\work\apache-maven-3.8.4\repo\org\reflections\reflections\0.9.9-RC1\reflections-0.9.9-RC1.jar;D:\work\apache-maven-3.8.4\repo\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;D:\work\apache-maven-3.8.4\repo\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar;D:\work\apache-maven-3.8.4\repo\org\aspectj\aspectjtools\1.7.4\aspectjtools-1.7.4.jar;D:\work\apache-maven-3.8.4\repo\com\baidu\disconf\disconf-core\2.6.36\disconf-core-2.6.36.jar;D:\work\apache-maven-3.8.4\repo\org\apache\httpcomponents\httpclient\4.5.1\httpclient-4.5.1.jar;D:\work\apache-maven-3.8.4\repo\org\apache\httpcomponents\httpcore\4.4.3\httpcore-4.4.3.jar;D:\work\apache-maven-3.8.4\repo\org\slf4j\slf4j-api\1.7.6\slf4j-api-1.7.6.jar;D:\work\apache-maven-3.8.4\repo\org\aspectj\aspectjrt\1.8.9\aspectjrt-1.8.9.jar;D:\work\apache-maven-3.8.4\repo\org\aspectj\aspectjweaver\1.8.9\aspectjweaver-1.8.9.jar;D:\work\apache-maven-3.8.4\repo\jaxen\jaxen\1.1.4\jaxen-1.1.4.jar;D:\work\apache-maven-3.8.4\repo\com\alibaba\fastjson\1.2.59\fastjson-1.2.59.jar;D:\work\apache-maven-3.8.4\repo\org\apache\kafka\kafka-clients\2.3.0\kafka-clients-2.3.0.jar;D:\work\apache-maven-3.8.4\repo\com\github\luben\zstd-jni\1.4.0-1\zstd-jni-1.4.0-1.jar;D:\work\apache-maven-3.8.4\repo\org\lz4\lz4-java\1.6.0\lz4-java-1.6.0.jar;D:\work\apache-maven-3.8.4\repo\org\xerial\snappy\snappy-java\1.1.7.3\snappy-java-1.1.7.3.jar;D:\work\apache-maven-3.8.4\repo\org\powermock\powermock-reflect\1.5.6\powermock-reflect-1.5.6.jar;D:\work\apache-maven-3.8.4\repo\org\objenesis\objenesis\2.1\objenesis-2.1.jar;D:\work\apache-maven-3.8.4\repo\org\javassist\javassist\3.18.2-GA\javassist-3.18.2-GA.jar;D:\work\apache-maven-3.8.4\repo\org\powermock\powermock-api-support\1.5.6\powermock-api-support-1.5.6.jar;D:\work\apache-maven-3.8.4\repo\org\powermock\powermock-classloading-base\1.5.6\powermock-classloading-base-1.5.6.jar;D:\work\apache-maven-3.8.4\repo\org\powermock\powermock-classloading-xstream\1.5.6\powermock-classloading-xstream-1.5.6.jar;D:\work\apache-maven-3.8.4\repo\com\thoughtworks\xstream\xstream\1.4.2\xstream-1.4.2.jar;D:\work\apache-maven-3.8.4\repo\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;D:\work\apache-maven-3.8.4\repo\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar" com.simo.vsim.dse.startup.DseServerMain
2022-06-10 18:21:34.176 [main] INFO  com.simo.vsim.dse.startup.DseServerMain() - *************** Dse Server is starting ...***************
2022-06-10 18:21:34.230 [main] INFO  org.springframework.context.support.ClassPathXmlApplicationContext() - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@62230c58: startup date [Fri Jun 10 18:21:34 CST 2022]; root of context hierarchy
2022-06-10 18:21:34.309 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader() - Loading XML bean definitions from class path resource [appContext.xml]
2022-06-10 18:21:34.450 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader() - Loading XML bean definitions from class path resource [loadDisConfig.xml]
2022-06-10 18:21:34.486 [main] INFO  org.springframework.context.annotation.ClassPathBeanDefinitionScanner() - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2022-06-10 18:21:34.486 [main] INFO  org.springframework.context.annotation.ClassPathBeanDefinitionScanner() - JSR-330 'javax.inject.Named' annotation found and supported for component scanning
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [D:\worksapce\vsim-core\vsim-apps\vsim-dse\target\classes\com\simo\vsim\dse\sim\SimResource.class]; nested exception is java.lang.ArrayIndexOutOfBoundsException: 23309
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:237)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:204)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:84)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:73)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1335)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1325)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:135)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:93)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:143)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:178)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:149)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:212)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:126)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:92)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:467)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:397)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.simo.vsim.dse.startup.DseServerMain.main(DseServerMain.java:15)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 23309
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:101)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:213)
	... 23 more

Process finished with exit code 1

**Comment by 2509569172** [comment]
no support lambda?

the error code:
![image](https://user-images.githubusercontent.com/49397581/173046607-918a3a78-1d4e-4abf-82c0-7c8ded6dcc07.png)

**Comment by bclozel** [comment]
Spring Framework 3.0.5 has been released in 2010 and predates Java 8 (released in 2014).
[Please use a supported version of the Spring Framework](https://spring.io/projects/spring-framework#support).
