### ISSUE TITLE
TestAotProcessorTests failure on MS Windows

### ISSUE THREAD

**Issue by xieruiyuan** [spring-projects/spring-framework#29103]
Hi, I'm following the "build from source" guide, but there's one failed test: `TestAotProcessorTests`

After I clone from the repo and type `./gradlew build` command, this test fails as follows.

```
java.lang.AssertionError: 
Expecting actual:
  ["org\springframework\context\event\DefaultEventListenerFactory__TestContext001_BeanDefinitions.java",
    "org\springframework\context\event\DefaultEventListenerFactory__TestContext002_BeanDefinitions.java",
    "org\springframework\context\event\DefaultEventListenerFactory__TestContext003_BeanDefinitions.java",
    "org\springframework\context\event\DefaultEventListenerFactory__TestContext004_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext001_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext002_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext003_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext004_BeanDefinitions.java",
    "org\springframework\test\context\aot\AotTestMappings__Generated.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterSharedConfigTests__TestContext001_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterSharedConfigTests__TestContext001_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterTests_NestedTests__TestContext002_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterTests_NestedTests__TestContext002_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringTestNGTests__TestContext003_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringTestNGTests__TestContext003_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringVintageTests__TestContext004_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringVintageTests__TestContext004_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext001_BeanDefinitions.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext002_BeanDefinitions.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext003_BeanDefinitions.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext004_BeanDefinitions.java"]
to contain exactly in any order:
  ["org/springframework/test/context/aot/AotTestMappings__Generated.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext001_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext001_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterSharedConfigTests__TestContext001_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterSharedConfigTests__TestContext001_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext001_BeanDefinitions.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext002_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext002_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterTests_NestedTests__TestContext002_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterTests_NestedTests__TestContext002_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext002_BeanDefinitions.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext003_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext003_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringTestNGTests__TestContext003_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringTestNGTests__TestContext003_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext003_BeanDefinitions.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext004_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext004_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringVintageTests__TestContext004_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringVintageTests__TestContext004_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext004_BeanDefinitions.java"]
elements not found:
  ["org/springframework/test/context/aot/AotTestMappings__Generated.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext001_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext001_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterSharedConfigTests__TestContext001_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterSharedConfigTests__TestContext001_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext001_BeanDefinitions.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext002_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext002_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterTests_NestedTests__TestContext002_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringJupiterTests_NestedTests__TestContext002_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext002_BeanDefinitions.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext003_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext003_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringTestNGTests__TestContext003_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringTestNGTests__TestContext003_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext003_BeanDefinitions.java",
    "org/springframework/context/event/DefaultEventListenerFactory__TestContext004_BeanDefinitions.java",
    "org/springframework/context/event/EventListenerMethodProcessor__TestContext004_BeanDefinitions.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringVintageTests__TestContext004_ApplicationContextInitializer.java",
    "org/springframework/test/context/aot/samples/basic/BasicSpringVintageTests__TestContext004_BeanFactoryRegistrations.java",
    "org/springframework/test/context/aot/samples/basic/BasicTestConfiguration__TestContext004_BeanDefinitions.java"]
and elements not expected:
  ["org\springframework\context\event\DefaultEventListenerFactory__TestContext001_BeanDefinitions.java",
    "org\springframework\context\event\DefaultEventListenerFactory__TestContext002_BeanDefinitions.java",
    "org\springframework\context\event\DefaultEventListenerFactory__TestContext003_BeanDefinitions.java",
    "org\springframework\context\event\DefaultEventListenerFactory__TestContext004_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext001_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext002_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext003_BeanDefinitions.java",
    "org\springframework\context\event\EventListenerMethodProcessor__TestContext004_BeanDefinitions.java",
    "org\springframework\test\context\aot\AotTestMappings__Generated.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterSharedConfigTests__TestContext001_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterSharedConfigTests__TestContext001_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterTests_NestedTests__TestContext002_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringJupiterTests_NestedTests__TestContext002_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringTestNGTests__TestContext003_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringTestNGTests__TestContext003_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringVintageTests__TestContext004_ApplicationContextInitializer.java",
    "org\springframework\test\context\aot\samples\basic\BasicSpringVintageTests__TestContext004_BeanFactoryRegistrations.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext001_BeanDefinitions.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext002_BeanDefinitions.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext003_BeanDefinitions.java",
    "org\springframework\test\context\aot\samples\basic\BasicTestConfiguration__TestContext004_BeanDefinitions.java"]

	at org.springframework.test.context.aot.TestAotProcessorTests.process(TestAotProcessorTests.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

This is the only failing test, and I tried to build multiple times.

Please let me know if you need additional information. Thanks.

**Comment by sbrannen** [comment]
Can you please confirm that you are using Microsoft Windows?

**Comment by snicoll** [comment]
We've had the same problem in Spring Boot with our Windows build. Using `Path.of` makes sure that the path can be resolved on all OSes, see https://github.com/spring-projects/spring-boot/blob/0f9ff867e7558ce204d76d2e86e6a1704a97c23c/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/intTest/java/org/springframework/boot/maven/AotTests.java#L43

**Comment by sbrannen** [comment]
This has been fixed on the `main` branch and should now work on MS Windows.

If it does not, please let us know.

Thanks for creating your first issue for the Spring Framework! 👍

**Comment by sbrannen** [comment]
> We've had the same problem in Spring Boot with our Windows build. 

Thanks for providing the link, @snicoll.

I wasn't aware of `Path#subPath`. Combining that with `Files.walk` (instead of `Files.find` like I was previously using) helps to greatly simplify my `findFiles` implementation:

https://github.com/spring-projects/spring-framework/blob/d21d7fd6d0d2be6cc8645c2911208ad0f9a6674d/spring-test/src/test/java/org/springframework/test/context/aot/TestAotProcessorTests.java#L87-L92

**Comment by sbrannen** [comment]
@xieruiyuan, I have pushed a change to `main` that relies solely on `Path` APIs as suggested by @snicoll.

Please let us know if the build still works for you on Windows.

Thanks

**Comment by xieruiyuan** [comment]
Hi Sam. Sorry for late reply, Yes it works perfectly now, Appreciate you help.

**Comment by sbrannen** [comment]
> Hi Sam. Sorry for late reply, Yes it works perfectly now, Appreciate you help.

Great 👍 

Thanks for letting us know.
