### ISSUE TITLE
Remove GraalVM workaround in PathMatchingResourcePatternResolver

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-framework#29214]
This is a follow up to #29163.

Once https://github.com/oracle/graal/issues/5080 and https://github.com/oracle/graal/issues/5081 have been resolved (tentatively in GraalVM 22.3), we should be able to remove the following workaround in `PathMatchingResourcePatternResolver`.

https://github.com/spring-projects/spring-framework/blob/6cb131ac7629cfda489d4d2367a36d44ee7b5ed2/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L744-L750

**Comment by eugeniace** [comment]
There is another problem with the method doFindPathMatchingFileResources. It fails on Windows with the following error:

`
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/TestApp/
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.doFindPathMatchingFileResources(PathMatchingResourcePatternResolver.java:765)
        at org.springframework.web.context.support.ServletContextResourcePatternResolver.doFindPathMatchingFileResources(ServletContextResourcePatternResolver.java:91)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:558)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:328)
`

The leading slash should be removed before calling `Path rootPath = fileSystem.getPath(rootDir);`

We cannot run any application on SB 3.0.0-SNAPSHOT on Windows because of this problem.
