### ISSUE TITLE
Missing reflection hints on controller parameters without annotations

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-framework#29331]
The `@GetMapping` endpoint specified in [this comment](https://github.com/spring-projects/spring-framework/issues/29316#issuecomment-1279986268) triggers this error:

```
java.lang.IllegalStateException: No primary or single unique constructor found for class com.example.validation.NoteFilters
        at org.springframework.beans.BeanUtils.getResolvableConstructor(BeanUtils.java:266) ~[na:na]
        at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:219) ~[validation:6.0.0-SNAPSHOT]
        at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.createAttribute(ServletModelAttributeMethodProcessor.java:85) ~[na:na]
        at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:147) ~[validation:6.0.0-SNAPSHOT]
```
`ControllerMappingReflectiveProcessor` should potentially be updated to add introspect hints on all parameters.

**Comment by sdeleuze** [comment]
The logic to support this use case is quite involved and the simplified one we have currently implemented in [ControllerMappingReflectiveProcessor#registerParameterTypeHints](https://github.com/spring-projects/spring-framework/blob/6b6cf1b4a2f8b03693876dd7b534b49c48a288bd/spring-web/src/main/java/org/springframework/web/bind/annotation/ControllerMappingReflectiveProcessor.java#L78) won't be able to cover this usage of `ServletModelAttributeMethodProcessor` in catch-all mode configured in [RequestMappingHandlerAdapter#getDefaultArgumentResolvers](https://github.com/spring-projects/spring-framework/blob/6b6cf1b4a2f8b03693876dd7b534b49c48a288bd/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerAdapter.java#L682).

A solution discussed with @rstoyanchev yesterday and previously with @snicoll would be to reuse the logic from the resolver from `RequestMappingHandlerAdapter#getDefaultArgumentResolvers` but we would have to provide different implementations for WebFlux versus WebMVC and adapt the hint after evaluating the argument resolver returned. Doable but involved so I move this issue in the `6.0.x` bucket.

In the meantime, users can use `@RegisterReflectionForBinding(Foo.class)` (see related [Javadoc](https://docs.spring.io/spring-framework/docs/6.0.0-SNAPSHOT/javadoc-api/org/springframework/aot/hint/annotation/RegisterReflectionForBinding.html)) to add the relevant hints.

**Comment by sdeleuze** [comment]
This issue is tightly related to #31765, we now document this native limitation in Spring Framework reference documentation and Spring Boot wiki. I tend to think the maintenance burden of implementing what is described in the comment above is not necessarily worth the effort, so I prefer to close this issue and reconsider only if there is a strong ask from various users.

Conceptually, native require to have a more explicit programming model, and asking native users to use the explicitly `@ModelAttribute` to infer related hints does not sound an unreasonable ask to me.
