### ISSUE TITLE
TomcatRequestUpgradeStrategy is not compatible with Tomcat 10.1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#29433]
**Affects:** 6.0.0-RC3

```
java.lang.NoSuchMethodError: 'void org.apache.tomcat.websocket.server.WsServerContainer.doUpgrade(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse, jakarta.websocket.server.ServerEndpointConfig, java.util.Map)'
	at org.springframework.web.socket.server.standard.TomcatRequestUpgradeStrategy.upgradeInternal(TomcatRequestUpgradeStrategy.java:73) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.socket.server.standard.AbstractStandardUpgradeStrategy.upgrade(AbstractStandardUpgradeStrategy.java:136) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.doHandshake(AbstractHandshakeHandler.java:289) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.doHandshake(WebSocketTransportHandler.java:137) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.socket.sockjs.transport.TransportHandlingSockJsService.handleRawWebSocketRequest(TransportHandlingSockJsService.java:216) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:441) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:134) ~[spring-websocket-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52) ~[spring-webmvc-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-webmvc-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1003) ~[spring-webmvc-6.0.0-RC3.jar:6.0.0-RC3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:895) ~[spring-webmvc-6.0.0-RC3.jar:6.0.0-RC3]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.1.jar:6.0]
```

`upgradeHttpToWebSocket(Object, Object, ServerEndpointConfig, Map<String, String>)` that was [added in Tomcat 10.0](https://github.com/apache/tomcat/commit/a182c5f23c3b836c5568eecd7e442d66e856494d) should be used instead.

**Comment by wilkinsona** [comment]
I've been testing Boot against a local build of Framework that contains [this change](https://github.com/wilkinsona/spring-framework/commit/f879e2c2070c5d867b8e802b4cdf78bf8c47f30f) and it seems to do the trick.

**Comment by jhoeller** [comment]
@wilkinsona Looks like we had an old code path just for Tomcat 9.0 compatibility there which obviously isn't relevant anymore. Your change looks straightforward. Could you turn this into a PR? Otherwise we can also manually upgrade the code accordingly.

**Comment by wilkinsona** [comment]
Closing in favor of https://github.com/spring-projects/spring-framework/pull/29434.
