### ISSUE TITLE
sqlSessionFactory has been removed in spring? Mybatis cannot be used in spring boot 3.0.0

### ISSUE THREAD

**Issue by tangtaoshadow** [spring-projects/spring-framework#29445]
**Affects:** \<6.0.0>

---

springBootVersion "3.0.0-SNAPSHOT"

mybatis-spring-boot-starter version: '2.2.2'

> sqlSessionFactory has been removed in spring? Mybatis cannot be used in spring boot 3.0.0

```java
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:122)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1749)
	... 72 more
```

```java

new SqlSessionFactoryBean()

cause 
java.lang.ClassNotFoundException: org.springframework.core.NestedIOException

```

**Comment by snicoll** [comment]
Thanks for the report but there's nothing we can do. MyBatis should upgrade to Spring Framework 6. This was reported previously and I've requested to create [an issue in MyBatis](https://github.com/spring-projects/spring-framework/issues/28198#issuecomment-1206144087) if one doesn't already exist.
