### ISSUE TITLE
Native version of webflux/r2dbc failed

### ISSUE THREAD

**Issue by operrin** [spring-projects/spring-framework#29582]
Hello,

my setup is:
* java: 
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
* platform:
Mac M1
* os:
12.6.1

the following fresh new SB3 project [1] compiles and runs without any problems when produced with
`gradle bootJar`.

When compiled with `gradle nativeCompile`, it fails for the following route: `http:8082/intervenants`.
`POST`, `DELETE`, `PUT` or `GET intervenants/{id}` work fine.

I'm not sure if the probem is related to SB3 or to a GraalVM problem (last line of the exception report):

```
...
2022-11-25T16:29:17.053+01:00 ERROR 78917 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [0e55f725-1]  500 Server Error for HTTP GET "/intervenants"

java.lang.NullPointerException: null
...
...
at java.base@17.0.5/java.lang.Thread.run(Thread.java:833) ~[intervenant-service:na]
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[intervenant-service:na]
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]
```

Thanks,

[1] https://github.com/operrin/sb3-native

**Comment by operrin** [comment]
Hi,

the problem is still reproducible with the new 3.0.2.

Thanks
