### ISSUE TITLE
Missing native hints for Hibernate Native Query proxy

### ISSUE THREAD

**Issue by ahmedeewo** [spring-projects/spring-framework#29603]
In Spring Boot 3.0.0,  jpa native query not working 

```java
    @Query(value = "SELECT * from user  where email = ?1 ;",nativeQuery = true)
    User findByEmail(String email);
```

with this error 

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.hibernate.query.sql.spi.NativeQueryImplementor, interface org.hibernate.query.spi.DomainQueryExecutionContext, interface org.hibernate.query.internal.ResultSetMappingResolutionContext, interface org.hibernate.query.spi.QueryImplementor, interface org.hibernate.query.SelectionQuery, interface org.hibernate.query.CommonQueryContract] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
```

**Comment by ahmedBouchaibi** [comment]
@mp911de can you help me please to be work, i add this hint but that steel not working

**Comment by ahmedBouchaibi** [comment]
can you help me please to be working , i add this hint but that steel not working 
`   hints.reflection().registerType(NativeQueryImplementor.class, MemberCategory.values());
        hints.reflection().registerType(DomainQueryExecutionContext.class, MemberCategory.values());
        hints.reflection().registerType(ResultSetMappingResolutionContext.class, MemberCategory.values());
        hints.reflection().registerType(QueryImplementor.class, MemberCategory.values());
        hints.reflection().registerType(SelectionQuery.class, MemberCategory.values());
        hints.reflection().registerType(CommonQueryContract.class, MemberCategory.values());
        hints.reflection().registerType(NativeQueryImpl.class, MemberCategory.values());
        hints.reflection().registerType(SharedEntityManagerCreator.class,MemberCategory.values());`

**Comment by NicklasWallgren** [comment]
Sample code https://github.com/NicklasWallgren/spring-boot-native-issue

**Comment by drakiula** [comment]
Wild guess, does it (maybe) help to define your query the following way?
```java
@Query(value = "SELECT * from user  where email = :email", nativeQuery = true)
User findByEmail(@Param("email") String email);
```

**Comment by marcusdacoregio** [comment]
+1 for this, I am facing the same problem, the only difference is that I am not using native query.
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.hibernate.query.hql.spi.SqmQueryImplementor, interface org.hibernate.query.sqm.internal.SqmInterpretationsKey$InterpretationsKeySource, interface org.hibernate.query.spi.DomainQueryExecutionContext, interface org.hibernate.query.SelectionQuery, interface org.hibernate.query.CommonQueryContract] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:171) ~[na:na]
        at java.base@17.0.5/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47) ~[spring-data-jpa-native-3-1-2:na]
        at java.base@17.0.5/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037) ~[spring-data-jpa-native-3-1-2:na]
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:316) ~[na:na]
```

The error is thrown by:
```java
@Bean
CommandLineRunner commandLineRunner(UserRepository userRepository) {
		return args -> {
			userRepository.save(new User("user@example.com"));
			Optional<User> user = userRepository.findByEmail("user@example.com"); // here
			user.ifPresent(System.out::println);
		};
}
```

The reproducible sample is here https://github.com/marcusdacoregio/query-hibernate-proxy-native-bug

**Comment by sdeleuze** [comment]
@marcusdacoregio Your error is likely related to #31050 on should be fixed on latest snapshots.
