### ISSUE TITLE
`Charset.forName("BIG5")` don't work in native-image

### ISSUE THREAD

**Issue by wangliang181230** [spring-projects/spring-framework#29769]
### log：
```log
java.lang.reflect.UndeclaredThrowableException: null
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:769) ~[na:na]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[na:na]
	at com.zaxxer.hikari.HikariDataSource$$SpringCGLIB$$0.getConnection(<generated>) ~[test-compatibility-springboot3-seata.exe:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[na:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[na:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[na:na]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:431) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at cn.wangliang181230.seata.TestService.test(TestService.java:45) ~[test-compatibility-springboot3-seata.exe:na]
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[test-compatibility-springboot3-seata.exe:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[na:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[na:na]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:204) ~[na:na]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:130) ~[na:na]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:201) ~[na:na]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:171) ~[na:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[na:na]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[na:na]
	at cn.wangliang181230.seata.TestService$$SpringCGLIB$$0.test(<generated>) ~[test-compatibility-springboot3-seata.exe:na]
	at cn.wangliang181230.seata.TestController.test(TestController.java:22) ~[test-compatibility-springboot3-seata.exe:na]
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[test-compatibility-springboot3-seata.exe:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1010) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:902) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[test-compatibility-springboot3-seata.exe:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:884) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[test-compatibility-springboot3-seata.exe:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[test-compatibility-springboot3-seata.exe:10.1.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[na:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[na:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[test-compatibility-springboot3-seata.exe:10.1.4]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[na:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[test-compatibility-springboot3-seata.exe:10.1.4]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[na:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[na:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[na:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[test-compatibility-springboot3-seata.exe:10.1.4]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[na:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[na:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[test-compatibility-springboot3-seata.exe:10.1.4]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833) ~[test-compatibility-springboot3-seata.exe:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[test-compatibility-springboot3-seata.exe:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178) ~[na:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[test-compatibility-springboot3-seata.exe:na]
	at io.seata.spring.annotation.datasource.SeataAutoDataSourceProxyAdvice.invoke(SeataAutoDataSourceProxyAdvice.java:68) ~[na:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[test-compatibility-springboot3-seata.exe:6.0.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[na:na]
	... 71 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at io.seata.rm.datasource.util.XAUtils.createXAConnection(XAUtils.java:48) ~[na:na]
	at io.seata.rm.datasource.util.XAUtils.createXAConnection(XAUtils.java:43) ~[na:na]
	at io.seata.rm.datasource.xa.DataSourceProxyXA.getConnectionProxyXA(DataSourceProxyXA.java:112) ~[na:na]
	at io.seata.rm.datasource.xa.DataSourceProxyXA.getConnectionProxy(DataSourceProxyXA.java:101) ~[na:na]
	at io.seata.rm.datasource.xa.DataSourceProxyXA.getConnection(DataSourceProxyXA.java:88) ~[na:na]
	... 75 common frames omitted
Caused by: java.nio.charset.UnsupportedCharsetException: BIG5
	at java.base@17.0.5/java.nio.charset.Charset.forName(Charset.java:528) ~[test-compatibility-springboot3-seata.exe:na]
	at com.alibaba.druid.util.MySqlUtils.<clinit>(MySqlUtils.java:519) ~[na:na]
	... 80 common frames omitted
```

### screenshot：
![图片](https://user-images.githubusercontent.com/1527893/210726638-21420dec-9054-4e21-badc-2e657f29a664.png)

**Comment by wangliang181230** [comment]
How can I solve the problem?

**Comment by bclozel** [comment]
I don't think this is strictly related to Spring, but rather a GraalVM question. Maybe `-H:+AddAllCharsets` will help?
Please reach out to the GraalVM community for such questions.

**Comment by wangliang181230** [comment]
OK, Thank you
