### ISSUE TITLE
Add native support for `@Convert` on JPA entities

### ISSUE THREAD

**Issue by NicklasWallgren** [spring-projects/spring-framework#29771]
I've run into an issue with the `jakarta.persistence.Convert` annotation with GraalVM and Spring Native, see the stacktrace below.

I'm a bit unsure if this issue should be reported here, with the Hibernate project or elsewhere .

```
Could not resolve matching constructor on bean class [.....EmailConverter] (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[demo:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[demo:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[demo:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[demo:6.0.3]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[demo:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[demo:6.0.3]
```

The `Converter` is implemented as shown below and is applied via `@Convert(converter = ....)`.
The issue does not present itself if I remove the `@Convert` and instead auto apply it via  `@Converter(autoApply = true)`.

```
@Column(name = "email", columnDefinition = "varchar(255) not null", nullable = false)
@Convert(converter = EmailConverter.class)
@NaturalId
private Email email;
```

```
public final class EmailConverter implements AttributeConverter<Email, String> {
    public EmailConverter() {}

    @Override
    public String convertToDatabaseColumn(final Email attribute) {
        return attribute.getValue();
    }

    @Override
    public Email convertToEntityAttribute(final String dbData) {
        return new Email(dbData);
    }

}
```

You can reproduce the issue with https://github.com/NicklasWallgren/spring-boot-native-issue

**Comment by wilkinsona** [comment]
As discussed with @sdeleuze, `PersistenceManagedTypesBeanRegistrationAotProcessor` looks like a logical place for us to deal with this. We've transfered this to the Framework repository (thanks, Brian!) for their further consideration.

**Comment by wilkinsona** [comment]
@NicklasWallgren Your sample app starts when this change is applied to its main class:

```diff
diff --git a/src/main/java/com/example/demo/DemoApplication.java b/src/main/java/com/example/demo/DemoApplication.java
index 64b538a..76b9b00 100644
--- a/src/main/java/com/example/demo/DemoApplication.java
+++ b/src/main/java/com/example/demo/DemoApplication.java
@@ -1,13 +1,29 @@
 package com.example.demo;
 
+import org.springframework.aot.hint.MemberCategory;
+import org.springframework.aot.hint.RuntimeHints;
+import org.springframework.aot.hint.RuntimeHintsRegistrar;
 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
+import org.springframework.context.annotation.ImportRuntimeHints;
+
+import com.example.demo.DemoApplication.ConverterRuntimeHints;
 
 @SpringBootApplication
+@ImportRuntimeHints(ConverterRuntimeHints.class)
 public class DemoApplication {
 
        public static void main(String[] args) {
                SpringApplication.run(DemoApplication.class, args);
        }
 
+       static class ConverterRuntimeHints implements RuntimeHintsRegistrar {
+
+               @Override
+               public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
+                       hints.reflection().registerType(EmailConverter.class, MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS);
+               }
+
+       }
+
 }
```

**Comment by NicklasWallgren** [comment]
@wilkinsona Great, thanks for the help!
