### ISSUE TITLE
CgLib$SET_THREAD_CALLBACK exception in native image

### ISSUE THREAD

**Issue by martinformi** [spring-projects/spring-framework#29873]
This bug seems to reappear, it was fixed already twice in the past (https://github.com/spring-projects/spring-framework/issues/29584)  Tested on `3.0.1` and `3.0.3-SNAPSHOT` with kotlin. I tried already everything:
- disabling CgLib proxies
- disabling transaction management, aspects proxy
- building on Windows or Linux
- disabling kotlin coroutines

Any idea how to fix it?

Error after startup of native image:

```
Caused by: java.lang.NoSuchMethodException: xxx.zzz$$SpringCGLIB$$0.CGLIB$SET_THREAD_CALLBACKS([Lorg.springframework.cglib.proxy.Callback;)
        at java.base@17.0.5/java.lang.Class.getDeclaredMethod(DynamicHub.java:2675) ~[data-feeder.exe:na]
        at org.springframework.cglib.proxy.Enhancer.getCallbacksSetter(Enhancer.java:901) ~[na:na]
        at org.springframework.cglib.proxy.Enhancer$EnhancerFactoryData.<init>(Enhancer.java:490) ~[na:na]
        ... 40 common frames omitted
```

**Comment by jhoeller** [comment]
Which kind of proxy is about to be created there? This exception is an indication of missing reflection hints for a specific CGLIB proxy class, driven by some framework feature. You could register a method reflection hint for ` xxx.zzz$$SpringCGLIB$$0` yourself as well, but we generally try to automatically register those reflection hints for every specific framework feature that leads to the use of proxies.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
