### ISSUE TITLE
Error after compile and run generated graalvm image

### ISSUE THREAD

**Issue by yosmellopez** [spring-projects/spring-framework#30588]
**Affects:** \<Spring Framework version>
3.0.6
---
I have next error after compile and run a native image with Graalvm and Spring.

2023-06-03 16:36:42 
2023-06-03 16:36:42   .   ____          _            __ _ _
2023-06-03 16:36:42  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2023-06-03 16:36:42 ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2023-06-03 16:36:42  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2023-06-03 16:36:42   '  |____| .__|_| |_|_| |_\__, | / / / /
2023-06-03 16:36:42  =========|_|==============|___/=/_/_/_/
2023-06-03 16:36:42  :: Spring Boot ::                (v3.1.0)
2023-06-03 16:36:42 
2023-06-03 16:36:42 2023-06-03T21:36:42.026Z  INFO 1 --- [           main] o.y.a.ApplicationNativaApplication       : Starting AOT-processed ApplicationNativaApplication using Java 17.0.7 with PID 1 (/workspace/org.ylplabs.applicationnativa.ApplicationNativaApplication started by cnb in /workspace)
2023-06-03 16:36:42 2023-06-03T21:36:42.026Z  INFO 1 --- [           main] o.y.a.ApplicationNativaApplication       : The following 1 profile is active: "prod"
2023-06-03 16:36:42 2023-06-03T21:36:42.057Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-06-03 16:36:42 2023-06-03T21:36:42.058Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-03 16:36:42 2023-06-03T21:36:42.058Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.8]
2023-06-03 16:36:42 2023-06-03T21:36:42.114Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-06-03 16:36:42 2023-06-03T21:36:42.114Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 88 ms
2023-06-03 16:36:42 2023-06-03T21:36:42.138Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-06-03 16:36:42 2023-06-03T21:36:42.158Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@28f66326
2023-06-03 16:36:42 2023-06-03T21:36:42.158Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-06-03 16:36:42 2023-06-03T21:36:42.159Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-06-03 16:36:42 2023-06-03T21:36:42.210Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.2.2.Final
2023-06-03 16:36:42 2023-06-03T21:36:42.211Z  INFO 1 --- [           main] org.hibernate.cfg.Environment            : HHH000406: Using bytecode reflection optimizer
2023-06-03 16:36:42 2023-06-03T21:36:42.214Z  INFO 1 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-03 16:36:42 2023-06-03T21:36:42.215Z  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': No classes have been predefined during the image build to load from bytecodes at runtime.
2023-06-03 16:36:42 2023-06-03T21:36:42.215Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-06-03 16:36:42 2023-06-03T21:36:42.216Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-06-03 16:36:42 2023-06-03T21:36:42.216Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-06-03 16:36:42 2023-06-03T21:36:42.217Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2023-06-03 16:36:42 
2023-06-03 16:36:42 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': No classes have been predefined during the image build to load from bytecodes at runtime.
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:931) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:3.1.0]
2023-06-03 16:36:42     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:3.1.0]
2023-06-03 16:36:42     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:3.1.0]
2023-06-03 16:36:42     at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:3.1.0]
2023-06-03 16:36:42     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:3.1.0]
2023-06-03 16:36:42     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:3.1.0]
2023-06-03 16:36:42     at org.ylplabs.applicationnativa.ApplicationNativaApplication.main(ApplicationNativaApplication.java:10) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:na]
2023-06-03 16:36:42 Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
2023-06-03 16:36:42     at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
2023-06-03 16:36:42     at com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76) ~[na:na]
2023-06-03 16:36:42     at com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130) ~[na:na]
2023-06-03 16:36:42     at java.base@17.0.7/java.lang.ClassLoader.defineClass(ClassLoader.java:294) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:na]
2023-06-03 16:36:42     at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1383) ~[na:na]
2023-06-03 16:36:42     at net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:459) ~[na:na]
2023-06-03 16:36:42     at net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:452) ~[na:na]
2023-06-03 16:36:42     at java.base@17.0.7/java.security.AccessController.executePrivileged(AccessController.java:168) ~[na:na]
2023-06-03 16:36:42     at java.base@17.0.7/java.security.AccessController.doPrivileged(AccessController.java:318) ~[na:na]
2023-06-03 16:36:42     at net.bytebuddy.utility.dispatcher.JavaDispatcher.doPrivileged(JavaDispatcher.java) ~[na:na]
2023-06-03 16:36:42     at net.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:87) ~[na:na]
2023-06-03 16:36:42     at net.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8659) ~[na:na]
2023-06-03 16:36:42     at net.bytebuddy.matcher.ElementMatchers.isFinalizer(ElementMatchers.java:1624) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$ProxyDefinitionHelpers.<init>(ByteBuddyState.java:296) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.<clinit>(ByteBuddyState.java:71) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:123) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:115) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.bytecode.internal.BytecodeProviderInitiator.buildBytecodeProvider(BytecodeProviderInitiator.java:59) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.bytecode.internal.BytecodeProviderInitiator.buildDefaultBytecodeProvider(BytecodeProviderInitiator.java:46) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.jpa.internal.enhance.EnhancingClassTransformerImpl.<init>(EnhancingClassTransformerImpl.java:34) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.jpa.boot.internal.PersistenceUnitInfoDescriptor.pushClassTransformer(PersistenceUnitInfoDescriptor.java:113) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.2.2.Final]
2023-06-03 16:36:42     at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:340) ~[na:na]
2023-06-03 16:36:42     at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:190) ~[na:na]
2023-06-03 16:36:42     at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[na:na]
2023-06-03 16:36:42     at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[org.ylplabs.applicationnativa.ApplicationNativaApplication:6.0.9]
2023-06-03 16:36:42     ... 16 common frames omitted
2023-06-03 16:36:42

**Comment by yosmellopez** [comment]
This issue is duplicated
