### ISSUE TITLE
ClassCastException in `AbstractBeanDefinition.getBeanClassName()` when getting bean multithreaded

### ISSUE THREAD

**Issue by mathekcbo** [spring-projects/spring-framework#30773]
When calling prototype Beans the first time in a multithreaded manner, the following exception can happen:

```
Exception in thread "Thread-2" java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.String (java.lang.Class and java.lang.String are in module java.base of loader 'bootstrap')
        at org.springframework.beans.factory.support.AbstractBeanDefinition.getBeanClassName(AbstractBeanDefinition.java:393)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1535)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1502)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:492)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344)
       ...
```

If this happens, the context/runtime will never raise this exception again. So it seems to be an issue only on startup.
This seems to happen since Spring Boot 3. There is nothing to find on google. We assume this error to be unknown so far.

To simplify things and for reproduction, we created a repository that can demonstrate the behaviour:
[Git Demo Repo for this issue](https://github.com/mathekcbo/sb3cce)

Please elaborate.
Thanks in advance

**Comment by quaff** [comment]
Reproduced with my local environment.

**Comment by wilkinsona** [comment]
Thanks for trying it, @quaff. Looking at the code in `AbstractBeanDefinition` I can see that `getBeanClassName` isn't thread-safe, but I couldn't reproduce it with the sample even after experimenting with different numbers of threads. 

@quaff, @mathekcbo, what OS, JVM, and so on did you use and how many iterations were required before the failure occurred?

**Comment by jhoeller** [comment]
This is a side effect of f64cc08b6210f67924185e65643d600e5bfb968e where we tried to apply `instanceof` pattern matching across the codebase, and accidentally lost the defensive access to the `beanClass` field that we had in 5.3.x there. I'll restore this for 6.0.11, with pattern matching but on a defensive copy of the field still.

**Comment by mathekcbo** [comment]
> Thanks for trying it, @quaff. Looking at the code in `AbstractBeanDefinition` I can see that `getBeanClassName` isn't thread-safe, but I couldn't reproduce it with the sample even after experimenting with different numbers of threads.
> 
> @quaff, @mathekcbo, what OS, JVM, and so on did you use and how many iterations were required before the failure occurred?

OS: Windows and Linux
JVM: JDK 17 Temurin
Reproduction: It may occur after some seconds (in the shell loop) or after 15 minutes. It differs

**Comment by jhoeller** [comment]
This should be restored for the upcoming 6.0.11 snapshot now, in sync with the original behavior in the 5.3.x line.

**Comment by mathekcbo** [comment]
Thank you for this quick response!
