### ISSUE TITLE
Spring framework 5.3.26 petclinic application and JDK21 

### ISSUE THREAD

**Issue by kundana-boddeti** [spring-projects/spring-framework#31068]
I am trying to build and deploy petclinic application using JDK21.the deployment fails with java.lang.IllegalArgumentException: Unsupported class file major version 65.

**Comment by bclozel** [comment]
This is not enough for us to figure out what the problem is. Can you point to which git repository and branch you are using and explain how to reproduce the problem?

**Comment by kundana-boddeti** [comment]
https://github.com/spring-petclinic/spring-framework-petclinic/tree/5.3.x . 
Coming to the steps to reproduce.
Build the war file using JDK21.
Deploy on weblogic

**Comment by bclozel** [comment]
Can you check that the JVM running the weblogic server is Java 21?

**Comment by kundana-boddeti** [comment]
yeah it is Java 21

**Comment by bclozel** [comment]
Can you share the full stack trace?

**Comment by kundana-boddeti** [comment]
User defined listener org.springframework.web.context.ContextLoaderListener failed: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [zip:/scratch/kyellapu/depot/src141200_build/Oracle_Home/results/wls/functional/spring/domains/petclinicDomain/servers/admin/tmp/_WL_user/petclinic/66da6x/war/WEB-INF/lib/_wl_cls_gen.jar!/org/springframework/samples/petclinic/service/ClinicServiceImpl.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: URL [zip:/scratch/kyellapu/depot/src141200_build/Oracle_Home/results/wls/functional/spring/domains/petclinicDomain/servers/admin/tmp/_WL_user/petclinic/66da6x/war/WEB-INF/lib/_wl_cls_gen.jar!/org/springframework/samples/petclinic/service/ClinicServiceImpl.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 65.

**Comment by kundana-boddeti** [comment]
ava.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:457)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:276)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:90)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1391)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1371)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:511)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:671)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:399)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:278)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:719)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:198)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.EventsManager.executeContextListener(EventsManager.java:251)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:204)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:192)
	at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1960)
	at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:3261)
	at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1892)
	at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:947)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:360)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:356)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:138)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:78)
	at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:52)
	at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:751)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:262)
	at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:52)
	at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:90)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:631)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:171)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:121)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:348)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:914)
	at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1475)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:466)
	at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:181)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:217)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:69)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:683)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:58)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:657)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:430)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:370)

**Comment by bclozel** [comment]
I'm not sure what's going on here, but Spring Framework 5.3.x works well with Java 21.
You can create a new application on https://start.spring.io (with [the following link](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.7.14&packaging=jar&jvmVersion=20&groupId=com.example&artifactId=java21demo&name=java21demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.java21demo&dependencies=web)), update the POM with the following:

```xml
    <properties>
        <java.version>21</java.version>
    </properties>
```

and run:

```
$ java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

$ ./mvnw spring-boot:run
```

This works well. Support for Java 21 in the 5.3.x line has been brought by #29966.
Please reach out to the petclinic repository maintainers to get assistance.
Thanks!

**Comment by bclozel** [comment]
See https://github.com/spring-petclinic/spring-framework-petclinic/issues/98
