### ISSUE TITLE
Spring Boot fails on does not reside in the file system: manifoldclass://622488023/.../

### ISSUE THREAD

**Issue by ojecborec** [spring-projects/spring-framework#31216]
I'm getting

```
Caused by: java.io.FileNotFoundException: URL [manifoldclass://622488023/.../] cannot be resolved to absolute file path because it does not reside in the file system: manifoldclass://622488023/.../
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:173) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.io.UrlResource.getFile(UrlResource.java:285) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.doFindPathMatchingFileResources(PathMatchingResourcePatternResolver.java:791) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:576) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:329) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1431) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.support.GenericApplicationContext.getResources(GenericApplicationContext.java:262) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:422) ~[spring-context-6.0.11.jar:6.0.11]
```

as descibed in https://github.com/spring-projects/spring-framework/issues/21950 with the latest Spring Boot 3.1.3 and Manifold 2023.1.24.

My `pom.xml` file includes 2 additional artifacts that are triggering the exception.

```
<dependencies>
        <!-- javac plugins -->
        <dependency>
            <groupId>systems.manifold</groupId>
            <artifactId>manifold-props-rt</artifactId>
            <version>${manifold-version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    ....
                    
                    <annotationProcessorPaths>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-props</artifactId>
                            <version>${manifold-version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by jhoeller** [comment]
This looks like a regression caused by #29226 where a `catch` block is missing around the new fallback `getFile()` call there.

**Comment by ojecborec** [comment]
Thank you. You guys are the best.
