### ISSUE TITLE
Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-framework#31247]
I updated my Spring 6.0/Java 17 cache example to the latest Spring 6.1 M5 and Java 21, but when running the tests it throws exception like this.

The example project: https://github.com/hantsy/spring6-sandbox/tree/master/cache

And the testing codes: https://github.com/hantsy/spring6-sandbox/blob/master/cache/src/test/java/com/example/demo/domain/PostRepositoryTest.java

```bash 
Caused by: java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes(FactoryBeanRegistrySupport.java:86)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:838)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:620)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:120)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:768)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:589)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:221)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:110)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:212)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	... 17 more

```

**Comment by snicoll** [comment]
`factoryBeanObjectType` should either be a `Class` or a `ResolvableType`. This has been the case since day one but the core container ignored the property if it wasn't any of those types. It now throws an exception so this is the expected behavior.

**Comment by CasaSky** [comment]
same issue using gradle plugin     
id "org.springframework.boot" version "3.2.0.M3"

No explicit set of any different spring library version

**Comment by snicoll** [comment]
@Anas-ZAHOURI it's impossible for us to know which component set a `String` `factoryBeanObjectType` on a bean definition. This can't be only Spring Boot as we've fixed those a while ago. If you manage to reproduce with only Spring-libraries, then create an issue at the appropriate place.

**Comment by A-caibird** [comment]
I have solved this issue, you use lower version springboot(3.15,3.14) can  solve that.

**Comment by yan-zhi-cheng** [comment]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
    </parent>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <tink.version>1.11.0</tink.version>
        <springdoc-openapi-starter-webmvc-ui.version>2.2.0</springdoc-openapi-starter-webmvc-ui.version>
        <pagehelper-spring-boot-starter.version>2.0.0</pagehelper-spring-boot-starter.version>
        <redisson-spring-boot-starter.version>3.24.3</redisson-spring-boot-starter.version>

        <bcprov-jdk18on.version>1.77</bcprov-jdk18on.version>
    </properties>

These are my dependencies, and they were upgraded to their latest versions, and now I get an error

I didn't do anything, just upgraded the dependency version



023-11-26 20:20:45.987 WARN 19812 [main] org.springframework.context.support.AbstractApplicationContext.refresh 624: Exception encountered during context initialization - cancelling refresh attempt: java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
2023-11-26 20:20:45.996 INFO 19812 [main] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger.logMessage 82: 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-11-26 20:20:46.005 ERROR 19812 [main] org.springframework.boot.SpringApplication.reportFailure 839: Application run failed

java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes(FactoryBeanRegistrySupport.java:86)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:838)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:620)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:260)
	at org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2AuthorizedClientManagerRegistrar.getBeanNamesForType(OAuth2ClientConfiguration.java:403)
	at org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2AuthorizedClientManagerRegistrar.postProcessBeanDefinitionRegistry(OAuth2ClientConfiguration.java:196)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:148)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:775)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:597)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)

**Comment by bclozel** [comment]
@yan-zhi-cheng same comment as https://github.com/spring-projects/spring-framework/issues/31247#issuecomment-1755714501

**Comment by kthumin** [comment]
> I just ran into this issue and I found a fix (at least for my case). Eventually, while trying to find the issue, I got the log message that Spring Cloud 2022.0.XX is not compatible with Spring Boot 3.2.XX.
> 
> I upgraded Spring Cloud to 2023.0.0-RC1 (available since 02.11.2023, see https://spring.io/blog/2023/11/02/spring-cloud-2023-0-0-rc1-aka-leyton-is-now-available) and my issue was fixed.
> 
> I hope that helps someone.

Thanks @kistlers , I ran into the same issue. This does the trick.

**Comment by iWATCHDOG** [comment]
Hey bro, I'm also experiencing this issue, but what I'm experiencing is when I try to add a mapper, i.e. for example the class "cn.watchdog.mapper.UserMapper", the content is:
```
package cn.watchdog.license.mapper;

import cn.watchdog.license.model.entity.User;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface UserMapper extends BaseMapper<User> {
}
```

The main class content is:
```
package cn.watchdog.license;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@MapperScan("cn.watchdog.license.mapper")
@EnableScheduling
@EnableAsync
@EnableCaching
public class BackendLicenseApplication {

	public static void main(String[] args) {
		SpringApplication.run(BackendLicenseApplication.class, args);
	}

}
```

When I add it, he reports an error. I don't know why this is happening.

Can u tell me how to solve this error?
I'm never meet it ever.

**Comment by m1ngyuan** [comment]
> Hey bro, I'm also experiencing this issue, but what I'm experiencing is when I try to add a mapper, i.e. for example the class "cn.watchdog.license.mapper.UserMapper", the content is:
> 
> ```
> package cn.watchdog.license.mapper;
> 
> import cn.watchdog.license.model.entity.User;
> import com.baomidou.mybatisplus.core.mapper.BaseMapper;
> 
> public interface UserMapper extends BaseMapper<User> {
> }
> ```
> 
> The main class content is:
> 
> ```
> package cn.watchdog.license;
> 
> import org.mybatis.spring.annotation.MapperScan;
> import org.springframework.boot.SpringApplication;
> import org.springframework.boot.autoconfigure.SpringBootApplication;
> import org.springframework.cache.annotation.EnableCaching;
> import org.springframework.scheduling.annotation.EnableAsync;
> import org.springframework.scheduling.annotation.EnableScheduling;
> 
> @SpringBootApplication
> @MapperScan("cn.watchdog.license.mapper")
> @EnableScheduling
> @EnableAsync
> @EnableCaching
> public class BackendLicenseApplication {
> 
> 	public static void main(String[] args) {
> 		SpringApplication.run(BackendLicenseApplication.class, args);
> 	}
> 
> }
> ```
> 
> When I add it, he reports an error. I don't know why this is happening.
> 
> Can u tell me how to solve this error? I'm never meet it ever.

fixed in https://github.com/mybatis/spring/pull/865

**Comment by iWATCHDOG** [comment]
But I followed the previous project to write it, and the previous project works fine, the new one doesn't.
And I just added a new Mapper. it reports an error and I don't even know what the reason is.

**Comment by iWATCHDOG** [comment]
> > Hey bro, I'm also experiencing this issue, but what I'm experiencing is when I try to add a mapper, i.e. for example the class "cn.watchdog.license.mapper.UserMapper", the content is:
> > ```
> > package cn.watchdog.license.mapper;
> > 
> > import cn.watchdog.license.model.entity.User;
> > import com.baomidou.mybatisplus.core.mapper.BaseMapper;
> > 
> > public interface UserMapper extends BaseMapper<User> {
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The main class content is:
> > ```
> > package cn.watchdog.license;
> > 
> > import org.mybatis.spring.annotation.MapperScan;
> > import org.springframework.boot.SpringApplication;
> > import org.springframework.boot.autoconfigure.SpringBootApplication;
> > import org.springframework.cache.annotation.EnableCaching;
> > import org.springframework.scheduling.annotation.EnableAsync;
> > import org.springframework.scheduling.annotation.EnableScheduling;
> > 
> > @SpringBootApplication
> > @MapperScan("cn.watchdog.license.mapper")
> > @EnableScheduling
> > @EnableAsync
> > @EnableCaching
> > public class BackendLicenseApplication {
> > 
> > 	public static void main(String[] args) {
> > 		SpringApplication.run(BackendLicenseApplication.class, args);
> > 	}
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I add it, he reports an error. I don't know why this is happening.
> > Can u tell me how to solve this error? I'm never meet it ever.
> 
> fixed in [mybatis/spring#865](https://github.com/mybatis/spring/pull/865)

OK,now I know the error what is.

and I bump version to 6.1 below. Then it will auto fix.

**Comment by yangas1** [comment]
> Hey bro, I'm also experiencing this issue, but what I'm experiencing is when I try to add a mapper, i.e. for example the class "cn.watchdog.license.mapper.UserMapper", the content is:
> 
> ```
> package cn.watchdog.license.mapper;
> 
> import cn.watchdog.license.model.entity.User;
> import com.baomidou.mybatisplus.core.mapper.BaseMapper;
> 
> public interface UserMapper extends BaseMapper<User> {
> }
> ```
> 
> The main class content is:
> 
> ```
> package cn.watchdog.license;
> 
> import org.mybatis.spring.annotation.MapperScan;
> import org.springframework.boot.SpringApplication;
> import org.springframework.boot.autoconfigure.SpringBootApplication;
> import org.springframework.cache.annotation.EnableCaching;
> import org.springframework.scheduling.annotation.EnableAsync;
> import org.springframework.scheduling.annotation.EnableScheduling;
> 
> @SpringBootApplication
> @MapperScan("cn.watchdog.license.mapper")
> @EnableScheduling
> @EnableAsync
> @EnableCaching
> public class BackendLicenseApplication {
> 
> 	public static void main(String[] args) {
> 		SpringApplication.run(BackendLicenseApplication.class, args);
> 	}
> 
> }
> ```
> 
> When I add it, he reports an error. I don't know why this is happening.
> 
> Can u tell me how to solve this error? I'm never meet it ever.

same to you i'm sad

**Comment by cn-luyang** [comment]
The upgrade of the mybatis-spring JAR to version 3.0.3

**Comment by VaraPrasadInfo** [comment]
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:183) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:428) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationCo
Caused by: java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

Could you please help me on this issue

**Comment by snicoll** [comment]
This issue is closed, please ask questions on StackIverflow. My best guess is that you have incompatible spring versions on the classpath.

**Comment by bjuergens** [comment]
> it's impossible for us to know which component set a `String` `factoryBeanObjectType` on a bean definition

Is there a general way to get this information? e.g. is there a specific log-flag that could help? or maybe I can turn on a relevant log-level in spring 6.0, so I can see the relevant deprectiation-warning?

**Comment by davidsoles** [comment]
> The upgrade of the mybatis-spring JAR to version 3.0.3

This comment helps me solve the problem. Thanks. 👍🏼

**Comment by pcc-tun** [comment]
The reason it returns "java.lang.String" is in class FactoryBeanRegistrySupport
`
ResolvableType getTypeForFactoryBeanFromAttributes(AttributeAccessor attributes) {
    Object attribute = attributes.getAttribute("factoryBeanObjectType");
    if (attribute == null) {
      return ResolvableType.NONE;
    } else if (attribute instanceof ResolvableType) {
      ResolvableType resolvableType = (ResolvableType)attribute;
      return resolvableType;
    } else if (attribute instanceof Class) {
      Class<?> clazz = (Class)attribute;
      return ResolvableType.forClass(clazz);
    } else {
      throw new IllegalArgumentException("Invalid value type for attribute 'factoryBeanObjectType': " + attribute.getClass().getName());
    }
  }`
   attributes.getAttribute("factoryBeanObjectType") look up for value in attributes LinkedHashMap and returns String there. Actually if in throw Exception you can print out the String it should be better.
 In my case it complains about my repository, which is extends JpaRepository.  "factoryBeanObjectType" contains a class name String ("com.abc.xdz.AAARepository") . Upgrading from Spring Boot 3.0.8 to Spring 3.1.10 comes with Hibernate 6.2.22 throws this error.

**Comment by dibyenduSI** [comment]
I am using spring boot version 3.2.4 and spring-cloud-starter-openfeign version 4.1.1 but still facing this issue please help

at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:180)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:130)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:142)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:98)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:260)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:163)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalStateException: Error processing condition on org.dt.core.platform.request.context.action.logging.LogViaMDCExportToAction
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:470)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:131)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:428)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1454)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:553)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	... 17 more
Caused by: java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes(FactoryBeanRegistrySupport.java:86)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:837)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:621)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:575)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:534)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:247)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:240)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:230)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:183)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:120)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 40 more

**Comment by snicoll** [comment]
@pcc-tun this has nothing to do with Hibernate, but the Spring Data version you're using in this case. The attribute has been removed on their end a while ago so you shouldn't be able to reproduce with vanilla Spring Boot 3.1.10. Perhaps you're overriding the version of Spring Data somewhere in your project?

@dibyenduSI asking here for help about OpenFeign is pointless. If you believe OpenFeign is setting the attribute as a String, then you should report that issue there or see if there is an update that has the fix already. There's nothing we can do about that here.

**Comment by hantsy** [comment]
> `factoryBeanObjectType` should either be a `Class` or a `ResolvableType`. This has been the case since day one but the core container ignored the property if it wasn't any of those types. It now throws an exception so this is the expected behavior.
> 
> (That sample needs to upgrade the Spring Data version).

Today I encountered the same problem when upgraded spring-data to 2024.0.0 in my sample projects, https://github.com/hantsy/spring6-sandbox/actions/runs/9232267806/job/25403254616
spring was updated to 6.1.0-M3, not sure this is another version conflict issue?
