### ISSUE TITLE
DefaultManagedTaskScheduler created manually now throws a NPE if the scheduled executor is not configured

### ISSUE THREAD

**Issue by fullopt** [spring-projects/spring-framework#31751]
After upgrading from 3.1.5 to 3.2.0 my application fails:

`org.springframework.context.ApplicationContextException: Failed to start bean 'simpleBrokerMessageHandler'`

The reason:

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.scheduleWithFixedDelay(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)" because "this.scheduledExecutor" is null
        at org.springframework.scheduling.concurrent.ConcurrentTaskScheduler.scheduleWithFixedDelay(ConcurrentTaskScheduler.java:262) ~[spring-context-6.1.1.jar:6.1.1]
        at org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler.startInternal(SimpleBrokerMessageHandler.java:271) ~[spring-messaging-6.1.1.jar:6.1.1]
        at org.springframework.messaging.simp.broker.AbstractBrokerMessageHandler.start(AbstractBrokerMessageHandler.java:210) ~[spring-messaging-6.1.1.jar:6.1.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:284) ~[spring-context-6.1.1.jar:6.1.1]
```

Can you please help me to fix it?

**Comment by fullopt** [comment]
> @fullopt can you confirm you're also using `DefaultManagedTaskScheduler` ? As far as I can see, that only happens if you opt-in for that scheduler and you don't create it as a managed object (bean).

Exactly, I used `DefaultManagedTaskScheduler()` what caused the issue. So far I changed for bean option proposed by @szolen  and it works as expected.

**Comment by szolen** [comment]
> @szolen and @fullopt for the record `DefaultManagedTaskScheduler` should be used if you want to lookup the executor via JNDI. We're wondering if you've used this class thinking that it was the "default scheduler" given its name, can you let us know?
> 
> As for creating the scheduler as a bean, this should have been done in the first place as the context needs that in order to honor the lifecycle, both during the startup phase, and the shutdown phase. Creating such a class manually is not the expected behavior.
> 
> As such the use cases above will still throw an exception, a different one though now.

Yes, I thought from the name that this was the default scheduler.

However, on the configuration class I used an `@Order` annotation: `@Order(Ordered.HIGHEST_PRECEDENCE)` but it seems that was insufficient.
