### ISSUE TITLE
StackOverflow error on SpringContext closing

### ISSUE THREAD

**Issue by antonioT90** [spring-projects/spring-framework#31982]
The following line brought to a recursive call causing an infinite loop:
https://github.com/spring-projects/spring-framework/blob/37fa82c578ae90b043d5cf7f7e216edb007cfc8a/spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java#L483

This is what I see inside logs printing DEBUG level for this package (the last 5 line are replicated until StackOverflowError occur):

>[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'transaction-outcome_binderProducingContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147482648
[o.s.cloud.stream.binding.BindingService ] - Trying to unbind 'errors-out-0', but no binding found.
[o.s.c.support.DefaultLifecycleProcessor ] - Bean 'outputBindingLifecycle' completed its stop procedure
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483647
[o.s.c.support.DefaultLifecycleProcessor ] - Bean 'springBootLoggingLifecycle' completed its stop procedure
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483648
[o.s.c.support.DefaultLifecycleProcessor ] - Bean 'kafkaProducerFactory' completed its stop procedure
[o.s.i.endpoint.EventDrivenConsumer      ] - Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
[o.s.i.channel.PublishSubscribeChannel   ] - Channel 'idpay-payment.errorChannel' has 0 subscriber(s).
[o.s.c.support.DefaultLifecycleProcessor ] - Bean '_org.springframework.integration.errorLogger' completed its stop procedure
[o.s.i.endpoint.EventDrivenConsumer      ] - stopped bean '_org.springframework.integration.errorLogger'
[o.s.c.support.DefaultLifecycleProcessor ] - Bean 'errors_integrationflow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0' completed its stop procedure
[o.s.i.endpoint.ReactiveStreamsConsumer  ] - stopped bean 'errors_integrationflow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0'
[o.s.c.support.DefaultLifecycleProcessor ] - Bean 'transactionOutcome_integrationflow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0' completed its stop procedure
[o.s.i.endpoint.ReactiveStreamsConsumer  ] - stopped bean 'transactionOutcome_integrationflow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0'
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'outerContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'kafka-errors_binderProducingContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147482648
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483647
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483648
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'outerContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'kafka-errors_binderProducingContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147482648
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483647
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483648
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'outerContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'kafka-errors_binderProducingContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147482648
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483647
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483648
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'outerContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'kafka-errors_binderProducingContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147482648
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483647
[o.s.c.support.DefaultLifecycleProcessor ] - Stopping beans in phase -2147483648
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'outerContext'
[o.s.c.support.DefaultLifecycleProcessor ] - Successfully stopped bean 'kafka-errors_binderProducingContext'

I stopped there my application while in debug mode when the stacktrace lenght was > 500 seeing:

These are my phases:
![image](https://github.com/spring-projects/spring-framework/assets/34568575/ef1002ac-2ae9-4a91-afd9-87a1ac2e4a84)

While these are my lifecycleBeans
![image](https://github.com/spring-projects/spring-framework/assets/34568575/07efbeb2-3869-4e0a-8a90-ef713893384f)

This is the stacktrace:
```
WARN  [ionShutdownHook] [o.s.c.support.DefaultLifecycleProcessor ] - Failed to stop bean 'outerContext'
java.lang.StackOverflowError: null
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:494)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:313)
	at org.springframework.context.support.DefaultLifecycleProcessor.stop(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.AbstractApplicationContext.stop(AbstractApplicationContext.java:1524)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:357)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:483)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:313)
	at org.springframework.context.support.DefaultLifecycleProcessor.stop(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.AbstractApplicationContext.stop(AbstractApplicationContext.java:1524)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:357)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:483)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:313)
	at org.springframework.context.support.DefaultLifecycleProcessor.stop(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.AbstractApplicationContext.stop(AbstractApplicationContext.java:1524)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:357)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:483)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:313)
	at org.springframework.context.support.DefaultLifecycleProcessor.stop(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.AbstractApplicationContext.stop(AbstractApplicationContext.java:1524)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:357)
...
```

**Comment by snicoll** [comment]
Thanks for the report but screenshots are not really actionable. Please move this to an application we can run ourselves to reproduce this. You can attach an issue as a zip here or push the code to a GitHub repository.

**Comment by antonioT90** [comment]
Hi  @snicoll,
I reproduced the error on an empty project.
It appears when there is a spring-cloud-stream's kafka binder (either Consumer or Producer)

You can find the code inside the following repo:
https://github.com/antonioT90/spring-stackoverflowerror

**Comment by antonioT90** [comment]
Moreover, It appears when using spring-cloud-dependencies `2023.0.0`, the previous `2022.0.4` is not showing the error

**Comment by snicoll** [comment]
Thank you very much for the sample @antonioT90. I am debugging and I haven't tracked down the root cause of the issue but the sample is super useful.

**Comment by antonioT90** [comment]
It is something that occurs when using the version `org.springframework.cloud:spring-cloud-stream:4.1.0`, the version 4.0.4 of this library is not showing the exception

**Comment by sobychacko** [comment]
Looks like this is related to an [issue](https://github.com/spring-cloud/spring-cloud-stream/issues/2870) we resolved recently due to a regression. I am on PTO right now. I can take a look when I am back next week if there’s still something that is lingering in Spring Cloud Stream.

**Comment by antonioT90** [comment]
@sobychacko I updated to `org.springframework.cloud:spring-cloud-stream:4.1.1-SNAPSHOT` and the exception is not more occurring: thus the fix you made resolved also this issue.

Could you please tell me when the release 4.1.1 should be published?

**Comment by snicoll** [comment]
Thanks for trying out @antonioT90!
