### ISSUE TITLE
HandlerMethod$HandlerMethodParameter#getParameterAnnotations method may be throw java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by antdong** [spring-projects/spring-framework#32037]
version:
org.springframework:spring-web:5.1.4.RELEASE
org.springdoc:springdoc-openapi-webmvc-core:1.4.8

Exception stack:
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.springdoc.core.GenericResponseBuilder.buildContent(GenericResponseBuilder.java:357) [1 skipped]
	at org.springdoc.core.GenericResponseBuilder.buildApiResponses(GenericResponseBuilder.java:449)
	at org.springdoc.core.GenericResponseBuilder.buildApiResponses(GenericResponseBuilder.java:311)
	at org.springdoc.core.GenericResponseBuilder.build(GenericResponseBuilder.java:135)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:375)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:505)
	at org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:262)
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:211)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:268)
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:180)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) [26 skipped]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) [1 skipped]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [2 skipped]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) [5 skipped]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) [14 skipped]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [19 skipped]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) [1 skipped]

it's occur exception when invoke '/v3/api-docs'(org.springdoc.webmvc.api.OpenApiResource#openapiJson) url

notes: delete some company's class

**Comment by bclozel** [comment]
[Spring Framework 5.1.x is out of open source support](https://spring.io/projects/spring-framework/#support). We can reopen this issue if you manage to provide a minimal sample application that reproduces the issue with a supported version of Spring.

Thanks!

**Comment by antdong** [comment]
> [Spring Framework 5.1.x is out of open source support](https://spring.io/projects/spring-framework/#support). We can reopen this issue if you manage to provide a minimal sample application that reproduces the issue with a supported version of Spring.
> 
> Thanks!

ok. I have successfully reproducted this issue. Here's the code:
`@RestController
@RequestMapping(produces = {MediaType.APPLICATION_JSON_VALUE})
@Api(tags = "Swagger测试Demo")
public class SwaggerController implements SwaggerInterface {

    @Override
    @GetMapping({"/advert/getAd"})
    @ApiOperation("测试Demo")
    public Map<String, String> getAd(HttpServletRequest request) {
        return null;
    }
}

public interface SwaggerInterface {

    Map<String, String> getAd(HttpServletRequest request);
}`

depedency:
`<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.1.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webmvc-core</artifactId>
            <version>1.4.8</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.4.8</version>
        </dependency>`

**Comment by bclozel** [comment]
[Spring Boot 2.1.x is also out of open source support](https://spring.io/projects/spring-boot/#support) and depends on Spring Framework 5.1.19.RELEASE.

Please use supported versions.
