### ISSUE TITLE
No class found : ErrorCoded

### ISSUE THREAD

**Issue by sathishkumars-nd** [spring-projects/spring-framework#32283]
Spring : 6.0.0
JDK 17
Tomcat : 10.0.27

While starting the application it throws error : Is it fixable or any solution.
PS : I dont want to upgrade tomcat. Becuz im using same with another project which runs on JDK8

java.lang.NoClassDefFoundError: org/springframework/core/ErrorCoded  
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)  
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)  
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)  
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2510)  
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:877)  
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1413)  
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1257)  
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)  
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)  
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)  
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2510)  
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:877)  
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1413)  
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1257)  
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:197)  
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:127)  
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:672)  
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)  
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:699)  
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:576)  
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)  
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:169)  
	at jakarta.servlet.GenericServlet.init(GenericServlet.java:158)  
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1165)  
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1014)  
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4907)  
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5214)  
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)  
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)  
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)  
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)  
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)  
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)  
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)  
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)  
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)  
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)  
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)  
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)  
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)  
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)  
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)  
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)  
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)  
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)  
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)  
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)  
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)  
	at org.apache.catalina.startup.Catalina.start(Catalina.java:795)  
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)  
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)  
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)

**Comment by bclozel** [comment]
It's likely to be a problem with your application. Maybe it is mixing old Spring Framework versions as the `ErrorCoded` class has been removed in 5.0 (see #19725). I would suggest using [the Spring Framework BOM](https://central.sonatype.com/artifact/org.springframework/spring-framework-bom) to ensure that you're using a consistent set of Spring dependencies.
