### ISSUE TITLE
Application stopping appeared StompBrokerRelayMessageHandler ClosedChannelException

### ISSUE THREAD

**Issue by ifzm** [spring-projects/spring-framework#32672]
**Affects:** \<Spring Framework version> 6.1.6

---

```log
2024-04-19T10:28:38.907+08:00  INFO 24100 --- [basic-api-app] [ionShutdownHook] o.s.m.s.s.StompBrokerRelayMessageHandler : Stopping...
2024-04-19T10:28:38.910+08:00  INFO 24100 --- [basic-api-app] [ionShutdownHook] o.s.m.s.s.StompBrokerRelayMessageHandler : BrokerAvailabilityEvent[available=false, StompBrokerRelay[ReactorNettyTcpClient[reactor.netty.tcp.TcpClientConnect@23f7ed9d]]]
2024-04-19T10:28:38.946+08:00  INFO 24100 --- [basic-api-app] [ient-loop-nio-2] o.s.m.s.s.StompBrokerRelayMessageHandler : TCP connection failure in session _system_: Failed to connect: null

java.nio.channels.ClosedChannelException: null
	at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:507) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:349) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:754) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:838) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:595) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-04-19T10:28:41.033+08:00  INFO 24100 --- [basic-api-app] [ionShutdownHook] o.s.m.s.s.StompBrokerRelayMessageHandler : Stopped.
```

**Comment by snicoll** [comment]
@ifzm thanks for the report but the issue is not actionable without a way for us to reproduce it as the failure can very well related to your environment and `StompBrokerRelayMessageHandler` is merely logging it. 

If you want support, please share a small sample that we can run ourselves with instructions to reproduce the problem. You can attach a zip to this issue or push the code to a GitHub repository.
