### ISSUE TITLE
CoroutineUtils failing when using object or lambda function parameter with webflux

### ISSUE THREAD

**Issue by userquin** [spring-projects/spring-framework#32670]
**Affects:** \<Spring Framework 6.1.5>

---

I need to provide a suspend function as last parameter, my older project version using Spring Boot 2.4 was working properly.

Updating to Spring Boot 3.4, I get an error about `null` parameter when using `xxx: suspend (id: String) -> java.nio.file.Path`:
```shell
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.JvmClassMappingKt.getJavaClass, parameter <this>
	at kotlin.jvm.JvmClassMappingKt.getJavaClass(JvmClassMapping.kt)
	at org.springframework.core.CoroutinesUtils.lambda$invokeSuspendingFunction$2(CoroutinesUtils.java:131)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$4.invokeSuspend(IntrinsicsJvm.kt:270)
```

Converting the lambda function to interface and providing and object also failing:
```shell
java.lang.ClassCastException: class kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to class kotlin.reflect.KClass (kotlin.reflect.jvm.internal.KTypeParameterImpl and kotlin.reflect.KClass are in unnamed module of loader 'app')
	at org.springframework.core.CoroutinesUtils.lambda$invokeSuspendingFunction$2(CoroutinesUtils.java:130)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:203)
	kotlinx.coroutines.reactor.MonoKt.monoInternal(Mono.kt:87)
```

The database logic:

![imagen](https://github.com/spring-projects/spring-framework/assets/6311119/4be4dab9-3184-4b1e-a0b0-ce22ef8852a6)

The corouter calling the database logic:

![imagen](https://github.com/spring-projects/spring-framework/assets/6311119/a44029bf-0632-4c72-99be-43e2b067f204)

**Comment by userquin** [comment]
upps, seems to be this one: https://github.com/spring-projects/spring-framework/issues/32552
