### ISSUE TITLE
restTemplate.exchange have exception "insufficient data written" with springboot 3.3

### ISSUE THREAD

**Issue by automvc** [spring-projects/spring-framework#33015]
The example use springboot 3.0 is normal, but use springboot 3.3 have exception.
Maybe it is different from #31902

detail error:
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://someurl/api/": insufficient data written
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:895)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:830)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:691)

**Comment by automvc** [comment]
try {
			URI uri = getUri(request, method);

			HttpHeaders headers = new HttpHeaders();
			Enumeration<String> headerNames = request.getHeaderNames();
			//set head from request 
			HttpEntity httpEntity = new HttpEntity<>(body, headers);
			ClientHttpRequestFactory clientHttpRequestFactory = (new SimpleClientHttpRequestFactory() {
			     //... 
			});

			ClientHttpRequestFactory factory = new BufferingClientHttpRequestFactory(clientHttpRequestFactory); // already use BufferingClientHttpRequestFactory

			RestTemplate restTemplate = new RestTemplate(factory);
			ResponseEntity serverResponse = null;

			serverResponse = restTemplate.exchange(uri, method, httpEntity, String.class); //this line have ResourceAccessException : insufficient data written

			// ... other
		} catch (Exception e) {
			logger.error("", e);
		}
		return ResponseEntity.badRequest().build();

**Comment by poutsma** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by snicoll** [comment]
@automvc please stop creating duplicate issues. Can you provide the sample that we requested?

**Comment by rajukosna** [comment]
Sample code is like:

@Autowired
RestTemplate restTemplate;

try {
		URI uri = getUri(request, method);

		HttpHeaders headers = new HttpHeaders();
		Enumeration<String> headerNames = request.getHeaderNames();
		//set head from request 
		HttpEntity httpEntity = new HttpEntity<>(body, headers);
		
		ResponseEntity serverResponse = null;

		serverResponse = restTemplate.exchange(uri, method, httpEntity, String.class); //this line have ResourceAccessException : insufficient data written

		// ... other
	} catch (Exception e) {
		logger.error("", e);
	}

**Comment by bclozel** [comment]
@ericdriggs unfortunately this doesn't help much. We can revisit this if you open a new issue with a minimal sample application we can run that reproduces the problem.

**Comment by gearkim0614** [comment]
`restTemplate.setRequestFactory(new HttpComponentsClientHttpRequestFactory());` fixed it for me

**Comment by polatgo1** [comment]
@gearkim0614 suggestion fix "insufficient data" case. But this causes redirection issue. It throws 421 when there is redirection during request because http/2 is forced on background. This is so annoying that there isn't currently a solution that fixes both issues.

**Comment by polatgo1** [comment]
@gearkim0614 suggestion fix "insufficient data" case. But this causes redirection issue. It throws 421 when there is redirection to a public website, for example google.com, during request because http/2 is forced on background. This is so annoying that there isn't currently a solution that fixes both redirection and insufficent data issues.

result is always same ->>>>>> 421 Misdirected Request on GET request for ....
