### ISSUE TITLE
No qualifying bean of type 'java.lang.String' in case of accidental `@Autowired` `@Bean` method with `@Value` parameter

### ISSUE THREAD

**Issue by jimshowalter** [spring-projects/spring-framework#33030]
A few minutes ago ./gradlew dependencyUpdates showed that 6.1.9 is available.

Upgraded to that from 6.1.8, and startup failed like this:

```
2024-06-14 07:13:50,853 DEBUG [main] DefaultListableBeanFactory: Creating shared instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
2024-06-14 07:13:50,854 DEBUG [main] DefaultListableBeanFactory: Creating shared instance of singleton bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration'
2024-06-14 07:13:50,855 DEBUG [main] DefaultListableBeanFactory: Bean creation exception on singleton FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available
2024-06-14 07:13:50,856 DEBUG [main] LoggingFailureAnalysisReporter: Application failed to start due to an exception
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1880)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1406)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:887)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:848)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1421)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1337)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1167)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1687)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1436)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1194)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1194)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1194)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1194)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at com.foo.ServiceApplication.main(ServiceApplication.java:30)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
2024-06-14 07:13:50,863 ERROR [main] LoggingFailureAnalysisReporter: 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method fooClient in com.foo.Bar$$SpringCGLIB$$0 required a bean of type 'java.lang.String' that could not be found.


Action:

Consider defining a bean of type 'java.lang.String' in your configuration.
```

Should be a really easy regression to track down, between those two minor versions.

**Comment by jhoeller** [comment]
What does the `fooClient` method signature look like? Apparently it has a parameter of type `String` which the container tries to resolve as a bean, maybe due to a missing indication that it is rather meant to be some other kind of value?

**Comment by jhoeller** [comment]
Actually, that exception stacktrace is a bit confusing. It actually seems to be an `@Autowired` method that fails to inject that `String`, not a `@Bean` factory method as I originally assumed. In any case, it is unclear what it is trying to obtain there.

**Comment by jimshowalter** [comment]
All we know is that we changed nothing except the one version, and this broke. What went into 6.1.9 that could have caused this regression?

**Comment by snicoll** [comment]
@jimshowalter can you reproduce on several machines? This looks really low-level and nothing that rings a bell. Perhaps a JAR is corrupted?

**Comment by jimshowalter** [comment]
A jar is not corrupted. We trivially upgraded Spring as part of our normal housekeeping, and it blew up our service, which has worked without any Spring-related issues for literally years.

**Comment by jimshowalter** [comment]
Tried another of our services, exact same failure.

**Comment by snicoll** [comment]
Can you reproduce on several machines is my question. We're both trying to help you and your replies are not helpful. Please take the time to process the feedback as it's unclear what your setup is. If this is so easy to reproduce, you should be able to provide us a sample. Also, the above is using Spring Boot so it's unclear why you didn't upgrade that rather tan framework explicitly.

**Comment by jimshowalter** [comment]
This is on several machines. It fails locally on a Mac M1, and in our Jenkins pipeline on RHEL8.

**Comment by jimshowalter** [comment]
It's definitively straightforward to reproduce in our services, but asking us to cut it down to a small reproducible test case is not so straightforward.

We're assuming this will prove to be a systemic problem with the latest 6.1.9, and that others will start reporting the same error.

**Comment by bclozel** [comment]
The entire Spring Boot test suite has upgraded to Spring Framework 6.1.9 and [ran successfully](https://github.com/spring-projects/spring-boot/actions/runs/9499165597), exercising quite a lot of integration tests in the process. We're not asking for a test case, but rather a simple application created on https://start.spring.io that fails. Given your feedback, this should be pretty straigthforward to replicate the bean/injection arrangement and demonstrate the failure.

**Comment by jhoeller** [comment]
There's always a chance for regressions but I'm afraid this is not a very obvious one. We will need your help to reproduce this in some way.

Oh, and thanks for trying 6.1.9 early. Anything to fix here, we can still do so for the corresponding Spring Boot releases next Thursday.

**Comment by jimshowalter** [comment]
2024-06-14 08:18:46,307 DEBUG [main] DefaultListableBeanFactory: Bean creation exception on singleton FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available
2024-06-14 08:18:46,308 DEBUG [main] LoggingFailureAnalysisReporter: Application failed to start due to an exception
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by jimshowalter** [comment]
The problem with trying to create a test case is, you already had a bunch of test cases that didn't catch this, and in the past whenever we've tried to reduce a large git repo to a small test case, the problem went away.

You're asking us to basically spend a couple of days trying to boil this down to something small, when the problem could be due to interactions among many components, none of which are under our control.

./gradlew dependencyUpdates (the ben-manes dependencies plugin) shows that all of our dependencies are on the latest versions, if that helps at all.

**Comment by jhoeller** [comment]
If you see the same failure in several services, do you mean the very same `fooClient` signature leading to a `String` resolution exception? Do you happen to have common dependencies among your services that include this `fooClient` method signature? 

Since I imagine this has been masked with the foo/bar naming there, it would be good to identify what kind of method it is that actually fails there.

**Comment by jimshowalter** [comment]
./gradlew dependencyUpdates

> Task :dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - ch.qos.logback:logback-classic:1.5.6
 - ch.qos.logback:logback-core:1.5.6
 - com.blueconic:browscap-java:1.4.3
 - com.github.ben-manes:gradle-versions-plugin:0.51.0
 - com.github.sherter.google-java-format:com.github.sherter.google-java-format.gradle.plugin:0.9
 - com.google.guava:guava:33.0.0-jre
 - commons-codec:commons-codec:1.17.0
 - io.rest-assured:json-schema-validator:5.4.0
 - io.rest-assured:rest-assured:5.4.0
 - org.apache.logging.log4j:log4j-to-slf4j:2.22.0
 - org.aspectj:aspectjweaver:1.9.22.1
 - org.gradle.test-retry:org.gradle.test-retry.gradle.plugin:1.5.9
 - org.hamcrest:hamcrest:2.2
 - org.jacoco:org.jacoco.agent:0.8.11
 - org.jacoco:org.jacoco.ant:0.8.11
 - org.jboss.resteasy:resteasy-jaxrs:3.15.6.Final
 - org.json:json:20240303
 - org.junit.jupiter:junit-jupiter-api:5.10.2
 - org.junit.jupiter:junit-jupiter-engine:5.10.2
 - org.mapstruct:mapstruct:1.5.5.Final
 - org.mapstruct:mapstruct-processor:1.5.5.Final
 - org.mockito:mockito-core:5.12.0
 - org.mockito:mockito-junit-jupiter:5.12.0
 - org.projectlombok:lombok:1.18.32
 - org.projectlombok:lombok-mapstruct-binding:0.2.0
 - org.slf4j:jcl-over-slf4j:2.0.13
 - org.slf4j:jul-to-slf4j:2.0.13
 - org.slf4j:log4j-over-slf4j:2.0.13
 - org.slf4j:slf4j-api:2.0.13
 - org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:5.0.0.4638
 - org.springframework:spring-tx:6.1.9
 - org.springframework:spring-web:6.1.9
 - org.springframework:spring-webmvc:6.1.9
 - org.springframework.boot:spring-boot-gradle-plugin:3.3.0
 - org.springframework.boot:spring-boot-starter-actuator:3.3.0
 - org.springframework.boot:spring-boot-starter-jersey:3.3.0
 - org.springframework.boot:spring-boot-starter-test:3.3.0
 - org.springframework.boot:spring-boot-starter-validation:3.3.0
 - org.springframework.boot:spring-boot-starter-web:3.3.0
 - org.springframework.data:spring-data-commons:3.3.1

Gradle release-candidate updates:
 - Gradle: [8.8: UP-TO-DATE]

Generated report file build/dependencyUpdates/report.txt

**Comment by snicoll** [comment]
This isn't going anywhere. If you don't want to take the time to provide the info, we unfortunately won't be able to help until someone else does (assuming they're affected by the same issue). I am not sure the exception you've shared is the root cause but rather a cascading effect of something else. You could share the full starting log of your application (by email if you don't want to provide them here) as well as the code that contributed `om.foo.Bar$$SpringCGLIB$$0` (the `fooClient`).

**Comment by jimshowalter** [comment]
Email to where?

**Comment by jimshowalter** [comment]
The exception I provided is the first one in the logs. That's something every user of Spring learns early--later exceptions are noise.

**Comment by jhoeller** [comment]
As for the dependencies, since you have aspectjweaver there: Any use of custom `@Aspect` classes? We did have some recent revisions there fixing other regressions (e.g. #32882, #32970) - maybe this has a side effect in your scenario. Although the real problems were in 6.1.7/6.1.8 there, 6.1.9 is just wrapping it up.

**Comment by snicoll** [comment]
> The exception I provided is the first one in the logs. 

I've never said the opposite. But you sharing 4 log entries and letting us guess what could go wrong isn't going to work. Your attitude isn't helpful (and quite frankly obnoxious IMO). We can reset perhaps and you can appreciate we're trying to help you? If you won't share details here, please email them at `<firstname.lastname@broadcom.com>`

**Comment by jimshowalter** [comment]
Jeez, I thought you'd appreciate knowing about the problem. Not sure what you mean by attitude, and it's pretty obnoxious to call me obnoxious, IMHO. I tried to provide the relevant information, probably cannot boil it down into a small test case based on previous attempts for other bug reports (that were later substantiated by other users reporting in). Anyway, either this is unique to us, and we'll just have to never upgrade, or others will start trying to use the latest and run into this same problem, find it online, and chime in.

I emailed the full startup log to that email address. As I said though, it doesn't contain any more information than I'd already posted. There's only the one exception.

**Comment by jimshowalter** [comment]
Well, tried to mail it anyway:

The response was:
The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. For more information, go to [https://support.google.com/mail/?p=NoSuchUser [support.google.com]](https://urldefense.com/v3/__https://support.google.com/mail/?p=NoSuchUser__;!!IC_USpSfJw!kmUjiaotiV4QFt3MfuKopf_NiGamB915XwCPbNUR1ZiUhI_tVWGYu4XUF2-Av7pHMG3IM9gEhGHlBh5dIp8BKxB2YJw$)

**Comment by snicoll** [comment]
Did you replace firstname and lastname with stephane and nicoll respectively?

**Comment by jimshowalter** [comment]
Doh. Thought you meant my name. Sent.

**Comment by jhoeller** [comment]
Since it might have been lost in the stream of comments above: please see https://github.com/spring-projects/spring-framework/issues/33030#issuecomment-2168312766 - do you have any custom use of AspectJ in your setup? The stacktrace does not indicate so, just checking since there have been some recent regressions and regression fixes in that area.

**Comment by jimshowalter** [comment]
I'm trying to create a cut-down test case. We have some custom aspects. Will try to cut it down enough to be able to see if those are causing it.

**Comment by jhoeller** [comment]
For a bit of context from our side: The key problem in our recent AspectJ support revision is Spring AOP with AspectJ aspects versus compile-time and load-time weaving. We have to accept ajc-compiled aspects for use with Spring AOP now, according to recent AspectJ recommendations for reusable aspect classes, whereas traditionally such ajc-compiled aspects were exclusively encountered with bytecode weaving.

Looking at your provided log, I see no "Ignoring incompatible aspect/advice" entries, so it does not seem to be those two new defensive catch blocks for AspectJ processing that we added in 6.1.9. The only other change in 6.1.9 is that we avoid potential duplicate execution of aspects through not applying ajc-compiled aspect classes to ajc-compiled bean classes in the application, assuming that those have been compile-time or load-time weaved.

**Comment by jimshowalter** [comment]
Managed to boil it down into a simple test case. It's having trouble taking config values from yaml and passing them into a configuration object.

[foo.zip](https://github.com/user-attachments/files/15842953/foo.zip)

**Comment by jimshowalter** [comment]
@snicoll @jhoeller

**Comment by jhoeller** [comment]
Thanks @jimshowalter, we'll sort it out ASAP. Getting late here in European time, might take until Monday to get fully into it.

From a quick glance: That `blowsUp` method should not declare `@Bean` as well as `@Autowired`. Looks like it is primarily a factory method, so `@Bean` alone should be sufficient, with the constructor arguments naturally getting autowired then. With an extra `@Autowired` there, the container tries to call that method separately as a setter-like method, failing in your stacktrace.

Such a plain `@Bean` declaration should work fine on any Spring version, so I strongly recommend that in any case. If this still fails for you, we need to see why `@Value` is not apparently not detected, with the container thinking it needs to autowire a plain String instead. If this works with just `@Bean`, we need to see why we tolerated a superfluous `@Autowired` before but not after.

**Comment by jimshowalter** [comment]
Interesting--that indeed fixed it!

We'll make a pass through our services looking for more examples of unnecessary annotations.

**Comment by jhoeller** [comment]
Glad to hear! We'll try to find out why we tolerated that before then.

Even with the extra annotation, it should still work, so we'll try to restore the previous behavior there in any case... maybe with a warn log entry though, otherwise such an accidental overuse of `@Autowired` is hard to notice.

**Comment by jhoeller** [comment]
This turns out to be a side effect caused by #32888 where bridge method resolution is more capable now. Previously, we did not detect `@Autowired` on CGLIB-processed `@Bean` methods, now we do on the original class... but we still use the CGLIB-overridden method (which does not include any annotations) for parameter resolution which fails for `@Value`.

So we accidentally ignored such an arrangement before, now - for a different accident - we process it and expose a side effect of the mismatch. The correct solution is to never declare `@Autowired` next to `@Bean` on the same method... but since we did effectively tolerate it before, we need to make sure we tolerate it again in 6.1.10 in some form.

**Comment by jimshowalter** [comment]
Or release a breaking change? It's not difficult to fix the breakages.

**Comment by jhoeller** [comment]
We might actually do a breaking change in a future release, forcing such accidental declarations to be cleaned up.

It's just the potential mid-line breakage in 6.1.x - possibly on code that the people affected cannot easily change since it is not in their hands - that we need to find a remedy for. That is totally doable, just a matter of where specifically (`BridgeMethodResolver` or `AutowiredAnnotationBeanPostProcessor`).

**Comment by quaff** [comment]
Another workaround is setting `proxyBeanMethods` of `@Configuration` to false if you are not using "inter-bean references".

**Comment by denAbramoff** [comment]
Hi! I got other example this exception with using 

 @Bean()
 public ArrayList<> .... 

No qualifying bean of type 'java.util.List<?>' available: expected single matching bean but found ... 

And, yes, it stems from @Configuration. After proxyBeanMethods = false this exception was gone.

**Comment by snicoll** [comment]
@quaff thanks for trying to help but there's no workaround needed if you can modify the `@Configuration` class to remove the unnecessary `@Autowired`.

@denAbramoff can you please move that to a new issue  with more details? When you do please add more content than just those two lines as we won't be able to make much of that.

**Comment by denAbramoff** [comment]
We used  @Autowired and @Bean together ... i left only @Bean and exception again was gone.
