### ISSUE TITLE
CRaC support: Checkpoint failing with CheckpointOpenSocketException

### ISSUE THREAD

**Issue by shanmuk256** [spring-projects/spring-framework#33103]
Trying to create check point in spring boot application but failing with the below error

jdk.crac.impl.CheckpointOpenSocketException: tcp6 localAddr :: localPort 8088 remoteAddr :: remotePort 0
at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:88)
at java.base/jdk.crac.Core.checkpointRestore1(Core.java:142)
at java.base/jdk.crac.Core.checkpointRestore(Core.java:237)
at java.base/jdk.crac.Core.lambda$checkpointRestoreInternal$3(Core.java:259)
at java.base/java.lang.Thread.run(Thread.java:833)

I used the spring.context.checkpoint=onRefresh in application.yml file.

Implemented beforeCheckpoint method and close the connection opened by application.
However spring we server is not being closed and throwing exception. 

jdk : openjdk-17-crac+3_linux-x64
springBootVersion = "3.3.0"

**Comment by sdeleuze** [comment]
`spring.context.checkpoint=onRefresh` is not a Spring Boot property you should set in `application.yml` but a JVM system property as documented [here](https://docs.spring.io/spring-framework/reference/integration/checkpoint-restore.html#_automatic_checkpointrestore_at_startup). I suggest you fix your use case accordingly, you should not have to implement `beforeCheckpoint` to close the connection opened by the application. https://github.com/spring-projects/spring-lifecycle-smoke-tests/ provides addition guidance for database etc.

if you still reproduce, please provide a self contained reproducer as a link to a repository or an attached project with the steps to reproduce. If you don't, please close this issue.
