### ISSUE TITLE
Random CancellationException instead of ResourceAccessException after upgrading to Spring Boot 3.4.0

### ISSUE THREAD

**Issue by SimonPNorra** [spring-projects/spring-framework#33973]
Hi Spring-Team,

After upgrading to Spring Boot 3.4.0, we have encountered an issue with RestTemplate where random CancellationExceptions are thrown instead of the expected ResourceAccessException during timeout scenarios.

Observations:
This behavior is inconsistent; sometimes a CancellationException is thrown, and other times a ResourceAccessException is thrown.
This issue did not occur in previous versions of Spring Boot.

Reproduction:
We have created a test case to demonstrate the issue: https://github.com/SimonPNorra/timeout-execption-case

Steps to Reproduce:
Run the test case included in the project and observe the exceptions thrown. You will notice either a CancellationException or a ResourceAccessException occurring randomly.

Expected Behavior:
Consistent behavior with ResourceAccessException thrown during timeout scenarios.

Actual Behavior:
Random exceptions are thrown: either CancellationException or ResourceAccessException.

Please let us know if further information is required.

Thank you.

Regards

**Comment by SimonPNorra** [comment]
Hi there,

I’ve updated my example project to include additional test scenarios:

1. Unit Test (as included previously)
2. Test from within the Spring application, which can be executed locally
3. Test using a distroless Docker image based on `gcr.io/distroless/java21-debian12`, replicating the execution environment where this issue was originally observed

I hope these additions help with your investigation.

Thank you for your support!

**Comment by aldex32** [comment]
I am having the same issue as @SimonPNorra

**Comment by cjrohrbach** [comment]
Hi all
I am facing the same Issue on windows with Spring boot 3.4.6.

@SimonPNorra did you by any chance find a workaround for this issue that you would be willing to share with us all?

**Comment by giampa91** [comment]
Hi, for the moment any workaround worked for me,
so I created a MR but has not been reviewed yet.

**Comment by cjrohrbach** [comment]
Alright then. 
Thanks a lot for taking the time to create a fix and a MR!

**Comment by Nhattd97** [comment]
Hi, I still have this issue on Spring Boot 3.5.3. Any update on this issue please? Thanks

**Comment by rstoyanchev** [comment]
In the TimeoutHandler we call `CompletableFuture#cancel` and the Javadoc for that says:

> If not already completed, completes this CompletableFuture with a CancellationException.

However, in some cases it is wrapped in `ExecutionException` and others it is not. Below is a stracktrace from when it is wrapped, and the cause is identical to when it is not wrapped as shown in comments above.

```
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Request cancelled
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2094)
	at org.springframework.http.client.JdkClientHttpRequest.executeInternal(JdkClientHttpRequest.java:106)
	at org.springframework.http.client.AbstractStreamingClientHttpRequest.executeInternal(AbstractStreamingClientHttpRequest.java:71)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:81)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:900)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:801)
	...
Caused by: java.util.concurrent.CancellationException: Request cancelled
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:278)
	at java.net.http/jdk.internal.net.http.MultiExchange$CancelableRef.cancel(MultiExchange.java:187)
	at java.net.http/jdk.internal.net.http.common.MinimalFuture.cancel(MinimalFuture.java:107)
	at org.springframework.http.client.JdkClientHttpRequest$TimeoutHandler.lambda$new$0(JdkClientHttpRequest.java:234)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire$$$capture(CompletableFuture.java:808)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java)
```

Currently we only handle the wrapped case, but should also handle it not wrapped.

**Comment by rstoyanchev** [comment]
Superseded by #34721.
