### ISSUE TITLE
IOException occurs in Flux Emission When Client Disconnects in Spring Boot WebFlux (Tomcat Server)

### ISSUE THREAD

**Issue by patrickf314** [spring-projects/spring-framework#34005]
## Description
When using Spring Boot with WebFlux and returning a `Flux` from a REST controller, an `IOException` is thrown when the client disconnects. The issue occurs specifically when using the **Tomcat server**. The same code works as expected when using the **Netty server**: Flux is canceled and not exception is passed to the exception handler. The error still occurs with spring boot 3.4.0.

This behavior is problematic because:
1. The Spring Boot exception handler catches the `IOException` (e.g., "Broken pipe" or "Connection reset by peer"), even though this should be handled gracefully.
2. There is no way to detect if the socket is closed before writing to it.
3. The exception clutters the logs and disrupts application workflows, even when the disconnection is a normal client behavior.

I believe this is a bug introduced in **Spring Boot version 3.2.6** or an inconsistency in the handling of disconnections between Tomcat and Netty servers.

## Steps to Reproduce
1. Create a Spring Boot WebFlux application with a REST controller that streams data as a `Flux`.
2. Configure the application to use the **Tomcat server**.
3. Start the application and connect to the endpoint using a client (e.g., `curl` or Postman).
4. Disconnect the client before the stream completes.
5. Observe that an `IOException` is thrown and handled by Spring Boot’s exception handler.

### Sample Application
```xml
<!-- pom.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.spring.bug</groupId>
    <artifactId>spring-flux-bug</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Since 3.2.6 -->
        <spring-boot.version>3.2.6</spring-boot.version>
    </properties>

    <dependencies>
        <!-- Spring Web to have spring boot started with Tomcat -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
    </dependencies>
</project>
```

```java
package de.spring.flux.bug;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.WebExceptionHandler;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.Duration;

@SpringBootApplication
@RestController
public class SpringFluxBugApplication {

    private static final Logger LOG = LoggerFactory.getLogger(SpringFluxBugApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(SpringFluxBugApplication.class, args);
    }

    @ExceptionHandler(Throwable.class)
    public void handleException(Throwable throwable) {
        // No invoked when using Netty.
        LOG.error("Unhandled exception", throwable);
    }

    @GetMapping("bugs")
    public Flux<String> getBugs() {
        return Flux.interval(Duration.ofSeconds(1))
                .map(i -> "Spring flux bug " + i)
                .log();
    }

    @Bean
    public WebExceptionHandler exceptionHandler() {
        return (exchange, ex) -> {
            LOG.info("This exception handler is not called", ex);
            return Mono.empty();
        };
    }
}

```

Start the spring boot application and call `curl -N http://localhost:8080/bugs`, then you should get the first string responses and then you can cancel the curl command. This will cause the following log in the application:
```
2024-12-02T16:07:32.477+01:00  INFO 82220 --- [        task-10] reactor.Flux.Map.2                       : request(1)
2024-12-02T16:07:33.476+01:00  INFO 82220 --- [     parallel-2] reactor.Flux.Map.2                       : onNext(Spring flux bug 5)
2024-12-02T16:07:33.477+01:00  INFO 82220 --- [        task-11] reactor.Flux.Map.2                       : cancel()
2024-12-02T16:07:33.477+01:00 ERROR 82220 --- [nio-8080-exec-5] d.s.flux.bug.SpringFluxBugApplication    : Unhandled exception

java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:102) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.implWrite(SocketChannelImpl.java:566) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:618) ~[na:na]
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:122) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1378) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:764) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:728) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:712) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:559) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:216) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1244) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:400) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.Response.action(Response.java:208) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:299) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:265) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:136) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest$LifecycleServletOutputStream.flush(StandardServletAsyncWebRequest.java:389) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:135) ~[spring-core-6.1.8.jar:6.1.8]
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:128) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:235) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:221) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:188) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$TextEmitterSubscriber.send(ReactiveTypeHandler.java:445) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$AbstractEmitterSubscriber.run(ReactiveTypeHandler.java:332) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[na:na]
```

## Expected Behavior
- It should be possible to explicitly handle this exception.
- Spring boot should behave similarly for Netty and Tomcat.

## Details
In our application, the exception handler logs unexpected exception as IOException as ERROR. Having the client disconnect exception handled this way spams the logs with unwanted exceptions. We can use the `Flux#doOnCancel` method to handle the disconnection in of the Flux. However, there no way of preventing the IOException to be passed to the exception handler.
Also spring boot should behave similarly for Netty and Tomcat. I think, it is not a good practice to filter the exception of the exception handle to specifically look for an IOException with message  `Broken pipe`. Possible solutions might be to suppress this IOException or alternatively wrap it with e.g. a `org.springframework.web.context.request.async.AsyncRequestNotUsableException`, which then can be handled explicitly.

**Comment by bclozel** [comment]
This is unfortunately the expected behavior. For all servers relying on the Servlet API, we do not have an API that notifies when a client disconnects. The only way to find out is to keep writing.

See https://github.com/jakartaee/servlet/issues/44

Now we do suppress a few of these cases in logs. If I understand correctly, you are seeing more of those after a recent upgrade? Which content type is this using? Is this using server sent events?

**Comment by patrickf314** [comment]
> This is unfortunately the expected behavior

Ok, I see. As I suggested, it would be nice to register a distinguished exception handler for those kind of exceptions. However, for those who find this ticket. Here is the way we handled it now: There is a `org.springframework.web.util.DisconnectedClientHelper` which helps identifying those exceptions. So basically we changed to exception handler to
```java
@ExceptionHandler(Throwable.class)
public void handleException(Throwable throwable) {
    if (DisconnectedClientHelper.isClientDisconnectedException(e)) {
        LOG.debug("Client disconnected.", e);
    }else{
        LOG.error("Unhandled exception", throwable);
    }
}
```

> If I understand correctly, you are seeing more of those after a recent upgrade? 

Yes, thats correct. Since the update from spring boot 3.2.5 to 3.2.6, we see those exception regularly in our CI. This also can be reproduced using the example above and changing the spring boot version to 3.2.5. However, using only the spring-boot-starter-webflux (with tomcat) does also log the exception. For both dependencies spring-boot-starter-web and spring-boot-starter-webflux, the IOException is not passed to the exception handler and hence not logged as ERROR. 

This might be a problem in a transitive dependencies. At first glance, I didn't see any version problem: spring-core, spring-web, spring-webmvc and spring-webflux are only included with version 6.1.6. Maybe you can give me a hint where to look. I also don't know which part of spring does the error handling in this case. As @wilkinsona pointed out, the spring-webmvc part takes over.

> Which content type is this using? Is this using server sent events?

Some endpoints use `produces = MediaType.TEXT_EVENT_STREAM_VALUE` other don't specify anything (In both cases, the exception can be observed). I guess, this is the default value as without specifying, the server returns `content-type:
text/event-stream`.

**Comment by rstoyanchev** [comment]
Returning a Flux from a controller method does not mean running on WebFlux. It is also supported on Spring MVC. So despite the title, based on the provided sample code, I will assume the issue is for Spring MVC.

I have run the sample code, and the `@ExceptionHandler` method gets `IOException` sometimes, but also `AsyncRequestNotUsableException`. This is because in this scenario there is a race between us handling the exception and Tomcat notifying us of the same via `AsyncListener#onError`. We protect against this and only one proceeds, but depending on who wins you may see either error.

I've created #34363 to address this. If you could, please subscribe to that for further comments and feedback.
