### ISSUE TITLE
Support Hibernate StatelessSession [SPR-2495]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#7184]
**[WDA](https://jira.spring.io/secure/ViewProfile.jspa?name=firegambler_2000)** opened **[SPR-2495](https://jira.spring.io/browse/SPR-2495?redirect=false)** and commented

Hello,

since Hibernate 3.1 has a 'StatelessSession' class to use for batch jobs (bulk inserts / updates), it wourld be nice, if  a helper class like 'HibernateDaoSupport' could support that new feature.

best regards,
Wolf-Dieter Angerer

---

**Affects:** 1.2.8, 2.0 RC3

**Attachments:**
- [StatelessSessionFactoryBean.java](https://jira.spring.io/secure/attachment/20890/StatelessSessionFactoryBean.java) (_6.41 kB_)

**Issue Links:**
- #7587 Add a HibernateDaoSupport / HibernateTemplate exclusively for handling Hibernate Stateless Sessions

19 votes, 20 watchers

**Comment by wagnerluis1982** [comment]
Is this issue still relevant?

**Comment by hantsy** [comment]
I encountered this issue when integrating with Jakarta Data RC 1 and Hibernate ORM 6.6.0.Alpha1(Jakarta Data provider, which use StatelessSesison in the backgroud).

**Comment by hantsy** [comment]
Found the solution here, https://gist.github.com/jelies/5181262

**Comment by jhoeller** [comment]
Reopened for `StatelessSession´ autowiring with Hibernate ORM 7.0 in Spring Framework 7.0 (see https://github.com/spring-projects/spring-framework/issues/33415#issuecomment-3133643837).

**Comment by jhoeller** [comment]
Spring Framework 7.0's new variant of `LocalSessionFactoryBean` in `org.springframework.orm.jpa.hibernate` automatically exposes a shared `Session` as well as a shared `StatelessSession` reference for dependency injection now (through `SmartFactoryBean`, similar to how `LocalContainerEntityManagerFactoryBean` exposes a shared qualified `EntityManager` in 7.0; see #33414).

These shared session references essentially behave like `SessionFactory#getCurrentSession()`, delegating every method invocation to the current thread-bound transactional session. On the first invocation within a new transaction, a `StatelessSession` will be opened for the current transactional JDBC Connection.

This approach works with `HibernateTransactionManager` (with a side `StatelessSession` managed next to the primary `Session` on the same transactional JDBC Connection) as well as `JdbcTransactionManager`/`DataSourceTransactionManager` (recommended for pure `StatelessSession` usage on top of a transactional JDBC Connection).

**Comment by hantsy** [comment]
@jhoeller, I have tried integrating Jakarta Data/Hibernate into Spring before; the transaction manager is a blocker when I want to control the tx.

It appears that this PR has resolved my transaction issue.


I tried to use the JPA `LocalContainerEntityManagerFactoryBean` to create the `StatelessSession` and `HibernateTrsanctionManager` ,

```java
@Configuration
public class JakartaDataConfig {

    @Bean
    public StatelessSession statelessSession(SessionFactory sessionFactory) {
        return sessionFactory.openStatelessSession();
    }

    @Bean
    public SessionFactory sessionFactory(LocalContainerEntityManagerFactoryBean entityManagerFactoryBean) {
        return entityManagerFactoryBean.getObject().unwrap(SessionFactory.class);
    }

    // Hibernate Data Repositories registered spring bean automatically in the generated impl class.
    // @Bean
    // public JakartaDataPostRepository dataPostRepository(StatelessSession statelessSession) {
    //     return new JakartaDataPostRepository_(statelessSession);
    // }

    @Bean
    public HibernateTransactionManager hibernateTransactionManager(SessionFactory sessionFactory) {
        return new HibernateTransactionManager(sessionFactory);
    }

}
```

Or `JpaTransactionManager` instead.

 When I add Spring `@Transctaional` or Jakarta transaction `@Transactional` to the Jakarta Data repository code, I got the exception like this at runtime:

```bash
	at com.example.demo.repository.data.JakartaDataPostRepository_.deleteAll(JakartaDataPostRepository_.java:88)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:158)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:369)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
```

In the generated `JakartaDataPostRepository_` which is registered as Spring `@Comonponet` and inject a `ObjectProvider<StatelessSession>`.

**Comment by hantsy** [comment]
When I defined a `LocalSessionFactoryBean` instead of `unwrap from EntityManagerFactory`, and I got the following exception instead.

```bash
jakarta.data.exceptions.DataException: Could not obtain transaction-synchronized Session for current thread

	at com.example.demo.repository.data.JakartaDataPostRepository_.findById(JakartaDataPostRepository_.java:144)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy1/jdk.proxy1.$Proxy49.findById(Unknown Source)
	at com.example.demo.JakartaDataPostRepositoryTestWithTestcontainers.testInsertAndQuery(JakartaDataPostRepositoryTestWithTestcontainers.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread
	at org.springframework.orm.jpa.hibernate.SpringSessionContext.currentStatelessSession(SpringSessionContext.java:175)
	at org.springframework.orm.jpa.hibernate.SharedSessionCreator.lambda$createSharedStatelessSession$0(SharedSessionCreator.java:83)
	at org.springframework.orm.jpa.hibernate.SharedSessionCreator$SharedSessionInvocationHandler.invoke(SharedSessionCreator.java:148)
	at jdk.proxy1/jdk.proxy1.$Proxy102.get(Unknown Source)
	at com.example.demo.repository.data.JakartaDataPostRepository_.findById(JakartaDataPostRepository_.java:141)
	... 9 more

```
