### ISSUE TITLE
javax.jms.IllegalStateException: Session closed Under Multi-thread [SPR-5163]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#9836]
**[Kent Chong](https://jira.spring.io/secure/ViewProfile.jspa?name=is_whchong)** opened **[SPR-5163](https://jira.spring.io/browse/SPR-5163?redirect=false)** and commented

I have used the commj "WorkManagerTaskExecutor" to multi-thread my work. The work will perform 2 action, 1 is to update the price record to database and then send the price message to Topics.
Record could update successfully. But some of the threads are unable to send message out.

Stacktrace:
org.springframework.jms.IllegalStateException: Session closed; nested exception is javax.jms.IllegalStateException: Session closed
Caused by:
javax.jms.IllegalStateException: Session closed
at com.ibm.ejs.jms.JMSSessionHandle.getOpenSession(JMSSessionHandle.java:1226)
at com.ibm.ejs.jms.JMSSessionHandle.getOpenUnifiedSession(JMSSessionHandle.java:1263)
at com.ibm.ejs.jms.JMSMessageProducerHandle.\<init>(JMSMessageProducerHandle.java:129)
at com.ibm.ejs.jms.JMSSessionHandle.createProducer(JMSSessionHandle.java:1777)
at org.springframework.jms.core.JmsTemplate.doCreateProducer(JmsTemplate.java:846)
at org.springframework.jms.core.JmsTemplate.createProducer(JmsTemplate.java:827)
at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:505)
at org.springframework.jms.core.JmsTemplate$2.doInJms(JmsTemplate.java:477)
at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:428)
at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:475)

---

**Affects:** 2.0.6

**Attachments:**
- [jms-outbound.xml](https://jira.spring.io/secure/attachment/14686/jms-outbound.xml) (_1.91 kB_)
- [springJMS.log](https://jira.spring.io/secure/attachment/14694/springJMS.log) (_6.82 kB_)

2 votes, 6 watchers

**Comment by spring-issuemaster** [comment]
Bulk closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by sravan2627** [comment]
Hi

facing the same issue with my application. getting the session closed exception even everything is fine.
now I increased the few values on JMS connection pool settings. Let me see how it should work now
